### PR TITLE
Update to fiona 1.9.5

### PR DESCRIPTION
**Pull request by hoodmane**
- [ ] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry

### CODE REVIEW

**Review by ryanking13 — COMMENTED** [review]
Thanks! I'll update the test later so we don't need the test file to run the test.

**Comment by hoodmane** [comment]
Yeah this was a bit high effort for my taste but at least it is less specific to the particular fiona version.

**Comment by ryanking13** [comment]
> Yeah this was a bit high effort for my taste

Sorry, I was lazy when I was first adding fiona. I felt that GDAL (dependency of fiona) was so complex that it needed to be fully tested, but analyzing and porting each test was too cumbersome.

**Comment by hoodmane** [comment]
Yeah these packages are hard work either way. Thanks for porting them! I did notice that there are some C++ exceptions that should probably be wrapped into Python exceptions instead of turning into fatals, like with #4455.

**Pull request merged**
