### PR TITLE
Make executables installed in Pyodide venv run in Pyodide not in host

### PR DESCRIPTION
**Pull request by hoodmane**
- [x] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry
- [x] Add a test

### CODE REVIEW

**Comment by ryanking13** [comment]
What exactly does changing sys.executable do?

**Comment by hoodmane** [comment]
The issue is that pip can't run inside of Pyodide because it needs to do stuff like make requests that don't work inside the virtual environment. So the virtual environment `bin` folder contains a `python-host` executable which is a symlink to the `sys.executable` that created the virtual environment. The shebang for pip uses `python-host`. But then when pip installs an executable it uses `sys.executable` to create the shebang for the installed executable. If that is `python-host` then the installed executable will run outside of Pyodide. For instance, `pytest` will run not in Pyodide but in the host python. This is not really what we want.

**Review by ryanking13 — APPROVED** [review]
Thanks for the explanation! Makes sense.

**Comment by hoodmane** [comment]
This seems to have broken the test. I didn't realize it wasn't running because of the opencv failure.

**Pull request merged**
