### PR TITLE
PKG Add Pysam

### PR DESCRIPTION
**Pull request by rrazaghi**
### Description
     - adding pysam to packages https://github.com/pysam-developers/pysam
     - This package is heavily used by bioinformaticians who mainly code in python

### Checklists
     - Packaging seems to be running smoothly and a success message is shown at the end
     - pysam compiles htslib itself so I decided not to package htslib separately

Ref: https://github.com/pyodide/pyodide/issues/2111

### CODE REVIEW

**Comment by rth** [comment]
Thanks! I think you would need to add zlib to cflags and ldflags as done [here](https://github.com/pyodide/pyodide/blob/main/packages/lxml/meta.yaml)

**Comment by rrazaghi** [comment]
@rth thanks a lot! I tried to put the flags in but it seems like the problem still stands. Do you have an insight what I'm doing wrong here?

**Comment by hoodmane** [comment]
@rrazaghi I think the best approach might be to run the configure script on the host system (needed to disable libcurl and lzma) and then patch the build script for pysam to not rerun configure. A lot of custom feature detection stuff in the htslib configure script doesn't work very well with emscripten.

**Comment by stevenweaver** [comment]
@rrazaghi Were you ever able to get pysam to compile? I'm also having trouble getting this to work.

**Comment by stevenweaver** [comment]
After performing what was recommended by @hoodmane. 

```
package:
  name: pysam
  version: 0.22.0
  top-level:
    - pysam
source:
  url: https://files.pythonhosted.org/packages/35/22/3d01778c13f1103401313f1232c1c0596d97aaee21c1d60564640f3049bd/pysam-0.22.0.tar.gz
  sha256: ab7a46973cf0ab8c6ac327f4c3fb67698d7ccbeef8631a716898c6ba01ef3e45
  patches:
    - patches/0001-remove_config_library.patch
requirements:
  host:
    - zlib
build:
  script: |
    cd htslib 
    emconfigure ./configure CFLAGS="-s USE_ZLIB=1 -s USE_BZIP2=1" --disable-lzma
    TOOLS=("tabix" "htsfile" "bgzip")
    for tool in ${TOOLS[@]}; do
        emmake make $tool CC=emcc AR=emar \
            CFLAGS="-O2 -s USE_ZLIB=1 -s USE_BZIP2=1" \
            LDFLAGS="$EM_FLAGS -O2 -s ERROR_ON_UNDEFINED_SYMBOLS=0"
    done
    cd ..
    export HTSLIB_CONFIGURE_OPTIONS="--disable-libcurl CFLAGS=-L../../../../packages/zlib/build/zlib-1.3.0/include LDFLAGS=-L../../../../packages/zlib/build/zlib-1.3.0/lib/'"
    export HTSLIB_MODE="separate"
    python setup.py build
about:
  home: https://github.com/pysam-developers/pysam
  PyPI: https://pypi.org/project/pysam
  summary: Package for reading, manipulating, and writing genomic data
  license: MIT License
```

Compilation still doesn't work. 

A linker error occurs

```
clang -undefined dynamic_lookup -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk                           
build/temp.macosx-14-x86_64-cpython-311/pysam/htslib_util.o build/temp.macosx-14-x86_64-cpython-311/pysam/libchtslib.o    
htslib/libhts.a -L/Users/sweaver/Programming/hivtrace/hcpy/packages/pysam/build/pysam-0.22.0/pysam                        
-Lbuild/lib.macosx-14-x86_64-cpython-311/pysam -lz -lbz2 -lz -o                                                           
build/lib.macosx-14-x86_64-cpython-311/pysam/libchtslib.cpython-311-darwin.so -dynamiclib -rpath @loader_path             
-Wl,-headerpad_max_install_names -Wl,-install_name,@rpath/libchtslib.cpython-311-darwin.so -Wl,-x                         
ld: warning: ignoring duplicate libraries: '-lz'                                                                          
ld: archive member '/' not a mach-o file in                                                                               
'/Users/sweaver/Programming/hivtrace/hcpy/packages/pysam/build/pysam-0.22.0/htslib/libhts.a'                              
clang: error: linker command failed with exit code 1 (use -v to see invocation)                                           
error: command '/usr/bin/clang' failed with exit code 1                                                                   
ERROR: build script failed                                                                                                
    cd htslib                                                                                                             
    emconfigure ./configure CFLAGS="-s USE_ZLIB=1 -s USE_BZIP2=1" --disable-lzma                                          
    TOOLS=("tabix" "htsfile" "bgzip")                                                                                     
    for tool in ${TOOLS}; do                                                                                              
        emmake make $tool CC=emcc AR=emar \                                                                               
            CFLAGS="-O2 -s USE_ZLIB=1 -s USE_BZIP2=1" \                                                                   
            LDFLAGS="$EM_FLAGS -O2 -s ERROR_ON_UNDEFINED_SYMBOLS=0"                                                       
    done                                                                                                                  
    cd ..                                                                                                                 
    export HTSLIB_CONFIGURE_OPTIONS="--disable-libcurl CFLAGS=-L../../../../packages/zlib/build/zlib-1.3.0/include        
LDFLAGS=-L../../../../packages/zlib/build/zlib-1.3.0/lib/'"                                                               
    export HTSLIB_MODE="separate"                                                                                         
    python setup.py build                                                                                                 
                                                                                                                          
[2023-10-26 19:58:18] Succeeded building package pysam in 68.5 seconds.                                                   
                                                                                                                          
ERROR: cancelling buildall     
```

**Comment by stevenweaver** [comment]
When not calling `make` from the yaml build, linker errors persists but are different.

```
package:
  name: pysam
  version: 0.22.0
  top-level:
    - pysam
source:
  url: https://files.pythonhosted.org/packages/35/22/3d01778c13f1103401313f1232c1c0596d97aaee21c1d60564640f3049bd/pysam-0.22.0.tar.gz
  sha256: ab7a46973cf0ab8c6ac327f4c3fb67698d7ccbeef8631a716898c6ba01ef3e45
  patches:
    - patches/0001-remove_config_library.patch
requirements:
  host:
    - zlib
build:
  script: |
    cd htslib 
    emconfigure ./configure CFLAGS="-s USE_ZLIB=1 -s USE_BZIP2=1" --disable-lzma
    # TOOLS=("tabix" "htsfile" "bgzip")
    # for tool in ${TOOLS[@]}; do
    #     emmake make $tool CC=emcc AR=emar \
    #         CFLAGS="-O2 -s USE_ZLIB=1 -s USE_BZIP2=1" \
    #         LDFLAGS="$EM_FLAGS -O2 -s ERROR_ON_UNDEFINED_SYMBOLS=0"
    # done
    cd ..
    export HTSLIB_CONFIGURE_OPTIONS="--disable-libcurl CFLAGS=-L../../../../packages/zlib/build/zlib-1.3.0/include LDFLAGS=-L../../../../packages/zlib/build/zlib-1.3.0/lib/'"
    #export HTSLIB_MODE="separate"
    python setup.py build
about:
  home: https://github.com/pysam-developers/pysam
  PyPI: https://pypi.org/project/pysam
  summary: Package for reading, manipulating, and writing genomic data
  license: MIT License
```

```
ld: warning: ignoring duplicate libraries: '-lz'                                                                                                                                                                                                     
ld: multiple errors: unknown file type in '/Users/sweaver/Programming/hivtrace/hcpy/packages/pysam/build/pysam-0.22.0/htslib/kstring.o'; unknown file type in                                                                                        
'/Users/sweaver/Programming/hivtrace/hcpy/packages/pysam/build/pysam-0.22.0/htslib/faidx.o'; unknown file type in '/Users/sweaver/Programming/hivtrace/hcpy/packages/pysam/build/pysam-0.22.0/htslib/header.o'; unknown file type in                 
'/Users/sweaver/Programming/hivtrace/hcpy/packages/pysam/build/pysam-0.22.0/htslib/bcf_sr_sort.o'; unknown file type in '/Users/sweaver/Programming/hivtrace/hcpy/packages/pysam/build/pysam-0.22.0/htslib/hfile.o'; unknown file type in            
'/Users/sweaver/Programming/hivtrace/hcpy/packages/pysam/build/pysam-0.22.0/htslib/hts.o'; unknown file type in '/Users/sweaver/Programming/hivtrace/hcpy/packages/pysam/build/pysam-0.22.0/htslib/hts_os.o'; unknown file type in                   
'/Users/sweaver/Programming/hivtrace/hcpy/packages/pysam/build/pysam-0.22.0/htslib/hts_expr.o'; unknown file type in '/Users/sweaver/Programming/hivtrace/hcpy/packages/pysam/build/pysam-0.22.0/htslib/errmod.o'; unknown file type in              
'/Users/sweaver/Programming/hivtrace/hcpy/packages/pysam/build/pysam-0.22.0/htslib/md5.o'; unknown file type in '/Users/sweaver/Programming/hivtrace/hcpy/packages/pysam/build/pysam-0.22.0/htslib/bgzf.o'; unknown file type in                     
'/Users/sweaver/Programming/hivtrace/hcpy/packages/pysam/build/pysam-0.22.0/htslib/multipart.o'; unknown file type in '/Users/sweaver/Programming/hivtrace/hcpy/packages/pysam/build/pysam-0.22.0/htslib/probaln.o'; unknown file type in            
'/Users/sweaver/Programming/hivtrace/hcpy/packages/pysam/build/pysam-0.22.0/htslib/realn.o'; unknown file type in '/Users/sweaver/Programming/hivtrace/hcpy/packages/pysam/build/pysam-0.22.0/htslib/regidx.o'; unknown file type in                 
'/Users/sweaver/Programming/hivtrace/hcpy/packages/pysam/build/pysam-0.22.0/htslib/sam.o'; unknown file type in '/Users/sweaver/Programming/hivtrace/hcpy/packages/pysam/build/pysam-0.22.0/htslib/region.o'; unknown file type in                   
'/Users/sweaver/Programming/hivtrace/hcpy/packages/pysam/build/pysam-0.22.0/htslib/vcf_sweep.o'; unknown file type in '/Users/sweaver/Programming/hivtrace/hcpy/packages/pysam/build/pysam-0.22.0/htslib/sam_mods.o'; unknown file type in           
'/Users/sweaver/Programming/hivtrace/hcpy/packages/pysam/build/pysam-0.22.0/htslib/synced_bcf_reader.o'; unknown file type in '/Users/sweaver/Programming/hivtrace/hcpy/packages/pysam/build/pysam-0.22.0/htslib/thread_pool.o'; unknown file type in
'/Users/sweaver/Programming/hivtrace/hcpy/packages/pysam/build/pysam-0.22.0/htslib/textutils.o'; unknown file type in '/Users/sweaver/Programming/hivtrace/hcpy/packages/pysam/build/pysam-0.22.0/htslib/tbx.o'; unknown file type in                
'/Users/sweaver/Programming/hivtrace/hcpy/packages/pysam/build/pysam-0.22.0/htslib/vcfutils.o'; unknown file type in '/Users/sweaver/Programming/hivtrace/hcpy/packages/pysam/build/pysam-0.22.0/htslib/kfunc.o'; unknown file type in               
'/Users/sweaver/Programming/hivtrace/hcpy/packages/pysam/build/pysam-0.22.0/htslib/cram/cram_codecs.o'; unknown file type in '/Users/sweaver/Programming/hivtrace/hcpy/packages/pysam/build/pysam-0.22.0/htslib/vcf.o'; unknown file type in         
'/Users/sweaver/Programming/hivtrace/hcpy/packages/pysam/build/pysam-0.22.0/htslib/cram/cram_decode.o'; unknown file type in '/Users/sweaver/Programming/hivtrace/hcpy/packages/pysam/build/pysam-0.22.0/htslib/cram/cram_external.o'; unknown file  
type in '/Users/sweaver/Programming/hivtrace/hcpy/packages/pysam/build/pysam-0.22.0/htslib/cram/cram_encode.o'; unknown file type in '/Users/sweaver/Programming/hivtrace/hcpy/packages/pysam/build/pysam-0.22.0/htslib/cram/cram_index.o'; unknown  
file type in '/Users/sweaver/Programming/hivtrace/hcpy/packages/pysam/build/pysam-0.22.0/htslib/cram/cram_io.o'; unknown file type in '/Users/sweaver/Programming/hivtrace/hcpy/packages/pysam/build/pysam-0.22.0/htslib/cram/cram_stats.o'; unknown 
file type in '/Users/sweaver/Programming/hivtrace/hcpy/packages/pysam/build/pysam-0.22.0/htslib/cram/open_trace_file.o'; unknown file type in                                                                                                        
'/Users/sweaver/Programming/hivtrace/hcpy/packages/pysam/build/pysam-0.22.0/htslib/cram/pooled_alloc.o'; unknown file type in '/Users/sweaver/Programming/hivtrace/hcpy/packages/pysam/build/pysam-0.22.0/htslib/cram/mFILE.o'; unknown file type in 
'/Users/sweaver/Programming/hivtrace/hcpy/packages/pysam/build/pysam-0.22.0/htslib/htscodecs/htscodecs/fqzcomp_qual.o'; unknown file type in                           
```

**Comment by stevenweaver** [comment]
Contents of the patch

```
From 0348efc8e8725d618d50d99ae9ffa91fc717b392 Mon Sep 17 00:00:00 2001
From: Steven Weaver <sweaver@temple.edu>
Date: Wed, 25 Oct 2023 19:06:33 -0600
Subject: [PATCH] remove_config_library

---
 setup.py | 21 ---------------------
 1 file changed, 21 deletions(-)

diff --git a/setup.py b/setup.py
index a4bf36d..22f3cb3 100644
--- a/setup.py
+++ b/setup.py
@@ -192,27 +192,6 @@ def set_compiler_envvars():
 
 
 def configure_library(library_dir, env_options=None, options=[]):
-
-    configure_script = os.path.join(library_dir, "configure")
-
-    on_rtd = os.environ.get("READTHEDOCS") == "True"
-    # RTD has no bzip2 development libraries installed:
-    if on_rtd:
-        env_options = "--disable-bz2"
-
-    if not os.path.exists(configure_script):
-        raise ValueError(
-            "configure script {} does not exist".format(configure_script))
-
-    with changedir(library_dir), set_compiler_envvars():
-        if env_options is not None:
-            if run_configure(env_options):
-                return env_options
-
-        for option in options:
-            if run_configure(option):
-                return option
-
     return None
 
 
-- 
2.39.3 (Apple Git-145)

```

**Comment by stevenweaver** [comment]
I was able to get further today, but something is definitely wrong. 

```
package:
  name: pysam
  version: 0.22.0
  top-level:
    - pysam
source:
  url: https://files.pythonhosted.org/packages/35/22/3d01778c13f1103401313f1232c1c0596d97aaee21c1d60564640f3049bd/pysam-0.22.0.tar.gz
  sha256: ab7a46973cf0ab8c6ac327f4c3fb67698d7ccbeef8631a716898c6ba01ef3e45
  patches:
    - patches/0001-remove_config_library.patch
requirements:
  host:
    - zlib
build:
  cross-script: |
    pwd
    echo PYTHONPATH: $PYTHONPATH
    echo _PYTHON_HOST_PLATFORM: $_PYTHON_HOST_PLATFORM
  script: |
    cd htslib 
    emconfigure ./configure CFLAGS="-s USE_ZLIB=1 -s USE_BZIP2=1" --disable-lzma
    # TOOLS=("tabix" "htsfile" "bgzip")
    # for tool in ${TOOLS[@]}; do
    #     emmake make $tool CC=emcc AR=emar \
    #         CFLAGS="-O2 -s USE_ZLIB=1 -s USE_BZIP2=1" \
    #         LDFLAGS="$EM_FLAGS -O2 -s ERROR_ON_UNDEFINED_SYMBOLS=0"
    # done
    cd ..
    export HTSLIB_CONFIGURE_OPTIONS="--disable-libcurl CFLAGS=-L../../../../packages/zlib/build/zlib-1.3.0/include LDFLAGS=-L../../../../packages/zlib/build/zlib-1.3.0/lib/'"
    #export HTSLIB_MODE="separate"
    export CC=emcc
    export CXX=em++
    export CFLAGS="$CFLAGS -s SIDE_MODULE=1"
    python setup.py build
about:
  home: https://github.com/pysam-developers/pysam
  PyPI: https://pypi.org/project/pysam
  summary: Package for reading, manipulating, and writing genomic data
  license: MIT License
```

After specifying `emcc` as the compiler, I am able to reach a point that others have reached in PRs and issues. 

```
In file included from pysam/libchtslib.c:126:                                                                                                                                                                                                        
In file included from /Users/sweaver/miniconda3/envs/pyodide-env/include/python3.11/Python.h:38:                                                                                                                                                     
/Users/sweaver/miniconda3/envs/pyodide-env/include/python3.11/pyport.h:596:2: error: "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."                                                                                       
  596 | #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."                                                                                                                                                             
      |  ^                                                                                                                                                                                                                                           
pysam/libchtslib.c:523:39: error: expression is not an integer constant expression                                                                                                                                                                   
  523 |     enum { __pyx_check_sizeof_voidp = 1 / (int)(SIZEOF_VOID_P == sizeof(void*)) };                                                                                                                                                           
      |                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                              
pysam/libchtslib.c:523:41: note: division by zero                                                                                                                                                                                                    
  523 |     enum { __pyx_check_sizeof_voidp = 1 / (int)(SIZEOF_VOID_P == sizeof(void*)) };                                                                                                                                                           
      |                                         ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                              
pysam/libchtslib.c:24379:21: warning: shift count >= width of type [-Wshift-count-overflow]                                                                                                                                                          
 24379 |         if (uintval >> (PyLong_SHIFT * 2)) {                                                                                                                                                                                                
       |                     ^  ~~~~~~~~~~~~~~~~~~                                                                                                                                                                                                   
pysam/libchtslib.c:24381:125: warning: shift count >= width of type [-Wshift-count-overflow]                              
 24381 |                  | (digits[1] != ((uintval >> (1 * PyLong_SHIFT)) & (unsigned long) PyLong_MASK)) | (digits[2] != ((uintval >> (2 * PyLong_SHIFT)) & (unsigned long) PyLong_MASK));                                                         
       |                                                                                                                             ^  ~~~~~~~~~~~~~~~~~~                                                                                           
2 warnings and 2 errors generated.                                                            
```

The code smell here is terrible, and I would really appreciate some pointers on where to go or my course be corrected.

**Comment by hoodmane** [comment]
"longbit appears wrong for this platform" means that it is pulling in native `Python.h` headers. Somehow the include path is messed up.

**Comment by ryanking13** [comment]
What happens if you remove following lines from `script` key? These things need to be handled by pyodide-build so you don't need to set call it manually. 

```
    export CC=emcc
    export CXX=em++
    export CFLAGS="$CFLAGS -s SIDE_MODULE=1"
    python setup.py build`
```

**Comment by stevenweaver** [comment]
When I remove those items, I receive the same errors as in comment https://github.com/pyodide/pyodide/pull/2115#issuecomment-1782175551. 

For clarity, I'm using the `pyodide` executable that is installed with `pip`. 

```
/Users/sweaver/Programming/hivtrace/env311/bin/pyodide
```

I'm using Python 3.11. When trying to build `pyodide` from source, I receive errors in both my virtual environment and from within Docker. 

[build.log](https://github.com/pyodide/pyodide/files/13196267/build.log)

**Comment by stevenweaver** [comment]
OK, I rebuilt my environment in macOS Sonoma 14.1. I was able to follow the Github Actions workflow to mimic and build `pyodide` to spec perfectly. I also tried in an Ubuntu environment with success. My environment uses the `pyodide-env` conda environment included in the repository. I am using the head branch. Other packages work beautifully and I am able to create wheels from less complex python packages. The issue in https://github.com/pyodide/pyodide/pull/2115#issuecomment-1782175551 remains.

**Comment by stevenweaver** [comment]
OK, now that I'm confident that it isn't something to do with `pyodide`, I'll keep digging. I believe it's an issue with a call to `make` made in their setup.py file here https://github.com/pysam-developers/pysam/blob/master/setup.py#L78.

**Comment by stevenweaver** [comment]
I got pysam to compile. Let me clean things up and test it out then will submit a new PR.

**Comment by ryanking13** [comment]
Superseded by #4268

**Pull request closed without merging**
