### PR TITLE
Bump rust toolchain version

### PR DESCRIPTION
**Pull request by ryanking13**
Bumping up to 2024-12-01. Let's see if it works.

Related: https://github.com/pyodide/pyodide/pull/5235#issuecomment-2511559870

### CODE REVIEW

**Comment by hoodmane** [comment]
This will bring in the rust-libc fix https://github.com/rust-lang/libc/pull/4002 so now we can doubly get rid of `-Z link-native-libraries=no` now. Also, https://github.com/rust-lang/libc/pull/3962 should resolve the problem with ABI mismatches. Could you try pulling in the test from https://github.com/pyodide/pyodide/pull/5112?

**Comment by ryanking13** [comment]
> This will bring in the rust-libc fix https://github.com/rust-lang/libc/pull/4002 so now we can doubly get rid of -Z link-native-libraries=no now. Also, https://github.com/rust-lang/libc/pull/3962 should resolve the problem with ABI mismatches. Could you try pulling in the test from https://github.com/pyodide/pyodide/pull/5112?

Sounds good. We'll need to update `pyodide-build` to remove the default `-Z link-native-libraries=no`. I added test packages that were included in #5112

**Comment by ryanking13** [comment]
Hmm, seems like `os.stat` still shows incorrect output?

**Comment by hoodmane** [comment]
Weird. Well it's not a blocker for this PR since it didn't get any worse. I'll try and do some work on the rust stuff when I get a chance.

**Comment by ryanking13** [comment]
Thanks. I'll xfail the test for now then.

**Review by hoodmane — APPROVED** [review]

**Comment by kleisauke** [comment]
> Hmm, seems like file size is still incorrect?

This needs commit https://github.com/rust-lang/rust/commit/ec7caabe9774a056cb21cd47b4489aed7a9c3659, which landed on December 1, 2024 at 8:15 AM GMT+1, so too late to be included in the `2024-12-01` nightly.

Bumping the Rust toolchain to `2024-12-02` should fix this.
```diff
    Compiling compiler_builtins v0.1.138
-   Compiling libc v0.2.162
-   Compiling std v0.0.0 (/usr/local/rustup/toolchains/nightly-2024-12-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std)
+   Compiling libc v0.2.167
+   Compiling std v0.0.0 (/usr/local/rustup/toolchains/nightly-2024-12-02-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std)
...
```

**Comment by ryanking13** [comment]
Thanks for letting us know @kleisauke !

**Pull request merged**
