### PR TITLE
BLD Add a file holding cross build environment metadata

### PR DESCRIPTION
**Pull request by ryanking13**
### Description

Related: #4557

This adds a file `pyodide-cross-build-environments.json` in the root directory of this repository. This file holds metadata for each version of pyodide cross build environments per version. This file will be used in pyodide-build to find compatible cross build versions and urls.

Regarding where to put this file, it might be better to create a separate repository (like the emsdk) and put it there in the future, but for now I think it is better keep it in this repository to keep the complexity down.

### Checklists

- [x] Add / update tests

### CODE REVIEW

**Comment by hoodmane** [comment]
Thanks @ryanking13. What's our strategy for keeping this up to date?

**Comment by ryanking13** [comment]
> What's our strategy for keeping this up to date?

We'll need to update this file after making a release. But yes, I think we need to automate it. Let me see if I can automate it easily.

**Comment by ryanking13** [comment]
I made a GHA that updates the JSON file after a release is made. It will create a draft PR [like this](https://github.com/ryanking13/pyodide/pull/24) so maintainers can update a few parts and merge the PR. WDYT? There still exists a human-involved part but it is quite trivial.

**Comment by hoodmane** [comment]
Sounds great, thanks @ryanking13!

**Review by hoodmane — APPROVED** [review]

**Comment by ryanking13** [comment]
Thanks for the review!

**Pull request merged**
