### PR TITLE
PKG added sqlalchemy

### PR DESCRIPTION
**Pull request by clstaudt**
### Description

Add package `sqlalchemy` to pyodide distribution.

### Note

I was not able to build and test the package yet due to an issue with the Docker image. As discussed with @hoodmane, I am sending the PR anyway. Thank you for integrating `sqlalchemy` quickly.

### CODE REVIEW

**Comment by bartbroere** [comment]
I'm afraid running `prettier` on the yaml has removed everything from the file.

**Comment by hoodmane** [comment]
We really should fix `mkpkg` so that it runs `prettier` automatically...

**Comment by clstaudt** [comment]
@bartbroere @hoodmane  Sorry, I made it worse by trying to also make the linter happy. Do you need me to fix the PR?

**Comment by rth** [comment]
Thanks @clstaudt ! Yes, we would need to fix this PR to merge it. The first commit looked good aside from the linting issue. To apply linters, the easiest is to use pre-commit https://pyodide.org/en/stable/development/contributing.html#development-workflow

**Review by rth — APPROVED** [review]
Thanks LGTM.

**Comment by hoodmane** [comment]
@rth is this okay to add to the next patch release? Not sure what our policy regarding package additions / updates and patch releases is. Seems like updates could be problematic, but adding a package isn't likely to break much existing code?

**Comment by rth** [comment]
Agreed. I don't think there is a reason not to include it.

**Comment by clstaudt** [comment]
@rth @hoodmane  Thank you. When do you plan to release the next patch?

**Comment by rth** [comment]
A few weeks to a month I think. But you can already use it now from the dev channel https://pyodide.org/en/stable/usage/downloading-and-deploying.html#cdn

**Pull request merged**
