### PR TITLE
Use original tblib instead of pyodide-tblib

### LINKED ISSUE #4237: Drop pyodide-tblib and switch to tblib 3.0
tblib 3.0 has been released with upstream support for serializing locals so we can return to using the upstream verson:
https://github.com/ionelmc/python-tblib/issues/41

### PR DESCRIPTION
**Pull request by ryanking13**
Close #4237

### CODE REVIEW

**Comment by hoodmane** [comment]
We need to add some code here:
https://github.com/pyodide/pytest-pyodide/blob/5da94f5ca47d9d7cb63af43518bdecbd29739e6f/pytest_pyodide/_decorator_in_pyodide.py#L128

```py
def pickle_locals(frame):
   result = {}
   tbhide = frame.f_locals.get("__tracebackhide__")
   if tbhide:
      result["__tracebackhide__"] = tbhide
   return result

pickling_support.install(pickle_locals=pickle_locals)
```

**Comment by hoodmane** [comment]
Opened a PR for this:
https://github.com/pyodide/pytest-pyodide/pull/122
That PR fixes the CI here.

**Comment by ryanking13** [comment]
> Opened a PR for this:
> [pyodide/pytest-pyodide#122](https://github.com/pyodide/pytest-pyodide/pull/122)
> That PR fixes the CI here.

Thanks!

**Comment by hoodmane** [comment]
Thanks @ryanking13!

**Pull request merged**
