### PR TITLE
Simplify js2python string conversion code a bit

### PR DESCRIPTION
**Pull request by hoodmane**

### CODE REVIEW

**Review by rth — APPROVED** [review]
Assuming CI is OK, thanks!

**Comment by hoodmane** [comment]
There are problems in Firefox in the CI. I do not yet understand why.

**Comment by hoodmane** [comment]
Problem was just a sporadic failure.

**Comment by hoodmane** [comment]
We might want to revert this, it seems to be inconsistently breaking up firefox-core tests on CI (cannot reproduce test failures locally though).

**Comment by rth** [comment]
Yes, it does look like there are more timeouts after the last few commits. Thoughg it could be also due to CircleCI having larger loads and being slower as well.

**Pull request merged**
