### PR TITLE
Run core tests in Safari

### PR DESCRIPTION
**Pull request by rth**
Partially addresses https://github.com/pyodide/pyodide/issues/989

It runs, but there are several test failures, I'll open separate issues about those.

### CODE REVIEW

**Comment by rth** [comment]
One blocker for this is that Safari apparently only supports 1 session at a time https://github.com/SeleniumHQ/selenium/issues/5057, (from https://developer.apple.com/documentation/webkit/about_webdriver_for_safari)
> One Session at a Time, to Mimic User Interaction
>
> Only one Safari browser instance can be active at any given time, and only one WebDriver session at a time can be attached to the browser instance. These constraints ensure that the simulated behavior (mouse, keyboard, touch, and so forth) accurately reflects what a user can do in a macOS windowing environment and prevents tests from competing with each other for window and keyboard focus.

so when we initialize the selenium module fixtures and then use a `selenium_standalone` fixture somewhere, we end up with 2 sessions and it fails with,
```
selenium.common.exceptions.SessionNotCreatedException: Message: Could not create a session: 
     The Safari instance is already paired with another WebDriver session.
```
I'm not sure what we can do about that. I suppose we could keep a global list of sessions, and close previous sessions when a new session is opened, but I don't think it would easily work with pytest fixture caching. 

Maybe @ryanking13 would have some ideas. I guess with playwright it would be the same issue.

**Comment by ryanking13** [comment]
> I'm not sure what we can do about that. I suppose we could keep a global list of sessions,

Maybe we can adjust the test running order (I'm not sure pytest has that feature) so that tests that use `selenium_standalone` can be executed in advance?

One other option can be instantiating multiple Pyodide instances inside a single selenium session.
I've once tried that in #2406 but it was not very successful then...

> Maybe @ryanking13 would have some ideas. I guess with playwright it would be the same issue.

Playwright does not have that issue. Probably because it is not based on web drivers.

Speaking of playwright, I also did some experiments [on safari (webkit) tests with playwright in May](https://github.com/ryanking13/pyodide/tree/playwright-webkit). It is blocked because playwright sometimes hangs and I wasn't able to find a way to fix it (I believe that it is partially related to #2660).

**Comment by rth** [comment]
> Maybe we can adjust the test running order (I'm not sure pytest has that feature) so that tests that use selenium_standalone can be executed in advance?

Thanks, @ryanking13 , very good point and that's actually rather straightforward to do. Though are are still a bunch of hard to debug issues with,
```
../miniforge3/envs/pyodide/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py:247: in check_response
    raise exception_class(message, screen, stacktrace)
E   selenium.common.exceptions.InvalidSessionIdException: Message:
```

**Comment by rth** [comment]
OK, so I got it down to 9 failing core tests but it still needs some work.

**Comment by ryanking13** [comment]
I synced with upstream main / pytest-pyodide and fixed some failing tests.

**Comment by rth** [comment]
Aww, great so you manage to make tests pass! You have more persistance than me :) 

Code wise LGTM, so feel free to merge if you are OK with it. I'm just going to move the changelog entry to the next release.

**Comment by ryanking13** [comment]
> Aww, great so you managed to make tests pass! You have more persistence than me :)

I only did the last 10% and you did the rest 90% of jobs :)

**Pull request merged**
