### PR TITLE
Run scipy tests as part of the Github Action CI

### PR DESCRIPTION
**Pull request by lesteve**
### Description

It would make a lot of sense to have Pyodide developers be able to run Scipy tests rather than asking me to do it manually based on https://github.com/lesteve/scipy-tests-pyodide when needed. Last time this happened is for the f2c fork PR https://github.com/pyodide/pyodide/pull/4920#issuecomment-2217581640. You could imagine that the Scipy 1.13 PR https://github.com/pyodide/pyodide/pull/4719 would benefit from this as well as potentially many other PRs.

I am testing this on my fork, see [GH logs from my PR branch](https://github.com/lesteve/pyodide/actions/workflows/main.yml?query=branch%3Afull-scipy-tests) in particular this [GH log](https://github.com/lesteve/pyodide/actions/runs/9937311988) where the scipy tests ran without error.

This is a bit of a draft PR as there are a few questions:
1. when do we want to trigger the full Scipy tests? There was a Hood's [comment](https://github.com/pyodide/pyodide/pull/4499#issuecomment-1936361540) that suggested when some files changes in a few folders e.g. scipy, f2c, etc .... do we want to always run it on main? Do we want a commit-based trigger like `[full-scipy]` (in scikit-learn we use them for a few things, like forcing a full doc-build, running the Pyodide CI in a PR, etc ...)
2. this would simplify my life if it was OK to to always build scipy in the "core" build (I would estimate maybe 15-20 minutes added to build time) ... tests would only be run on some specific triggers. Right now, I separated scipy build from the core build but right now it is compiling everything again. I guess because I need to add more things in the cache although I don't know exactly which ones (emsdk, cpython, packages at the very least). I guess CircleCI does that with workspaces. 
3. test strategy is the same as the one I currently use in https://github.com/lesteve/scipy-tests-pyodide, i.e. run with node and a js wrapper script. One of the reason of still having this wrapper script is that I have some work-arounds to remove some Scipy test files whose import is problematic.

Side-comment: I am using `-m 'not slow'` because otherwise I saw some weird memory issue towards the end of Scipy tests, see this [build log](https://github.com/lesteve/pyodide/actions/runs/9934164081/job/27439073308) where some tests can not allocate enough memory for the numpy arrays. Locally I get a Pyodide fatal error at 97% of the test, not sure whether this is related.

<details>

<summary>One of the error</summary>

```
 _______________ TestGoodnessOfFit.test_against_anderson_gumbel_r _______________

self = <scipy.stats.tests.test_fit.TestGoodnessOfFit object at 0xeda4d90>

    @pytest.mark.slow
    def test_against_anderson_gumbel_r(self):
        rng = np.random.default_rng(7302761058217743)
        # c that produced critical value of statistic found w/ root_scalar
        x = stats.genextreme(0.051896837188595134, loc=0.5,
                             scale=1.5).rvs(size=1000, random_state=rng)
>       res = goodness_of_fit(stats.gumbel_r, x, statistic='ad',
                              random_state=rng)

/lib/python3.12/site-packages/scipy/stats/tests/test_fit.py:849: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/lib/python3.12/site-packages/scipy/stats/_fit.py:1138: in goodness_of_fit
    res = stats.monte_carlo_test(data, rvs, statistic_fun, vectorized=True,
/lib/python3.12/site-packages/scipy/_lib/_util.py:779: in wrapper
    return fun(*args, **kwargs)
/lib/python3.12/site-packages/scipy/stats/_resampling.py:910: in monte_carlo_test
    null_distribution.append(statistic(*resamples, axis=-1))
/lib/python3.12/site-packages/scipy/stats/_fit.py:1136: in statistic_fun
    return compare_fun(rfd_dist, data)
/lib/python3.12/site-packages/scipy/stats/_fit.py:1217: in _anderson_darling
    Si = (2*i - 1)/n * (dist.logcdf(x) + dist.logsf(x[..., ::-1]))
/lib/python3.12/site-packages/scipy/stats/_distn_infrastructure.py:499: in logsf
    return self.dist.logsf(x, *self.args, **self.kwds)
/lib/python3.12/site-packages/scipy/stats/_distn_infrastructure.py:2207: in logsf
    place(output, cond, self._logsf(*goodargs))
/lib/python3.12/site-packages/scipy/stats/_distn_infrastructure.py:1007: in _logsf
    return log(self._sf(x, *args))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <scipy.stats._continuous_distns.gumbel_r_gen object at 0x1f2111b0>
x = array([11.92907778,  9.6840553 ,  6.65586868, ..., -1.75948008,
       -1.77058159, -1.92686803])

    def _sf(self, x):
>       return -sc.expm1(-np.exp(-x))
E       numpy.core._exceptions._ArrayMemoryError: Unable to allocate 76.3 MiB for an array with shape (9999000,) and data type float64

/lib/python3.12/site-packages/scipy/stats/_continuous_distns.py:4024: MemoryError
```

### Checklists

I am guessing none of the checklist items apply here so I ticked all of them ...

- [X] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry
- [X] Add / update tests
- [X] Add new / update outdated documentation

### CODE REVIEW

**Comment by ryanking13** [comment]
Thanks @lesteve! I really needed this :)

> Do we want a commit-based trigger like [full-scipy]

I prefer this one.

> this would simplify my life if it was OK to to always build scipy in the "core" build.

I think it is okay to do that. We don't build all packages in GHA, as we already build everything in CricleCI. But adding scipy seems reasonable to me. The situation will change if we unvendor recipes later anyways (#4918).

**Comment by lesteve** [comment]
OK thanks for your inputs, in https://github.com/pyodide/pyodide/pull/4935/commits/b2ef91a8d230b69af3005b8624aea983c0bb83c9 I now build scipy in the "core" build.

I will look at adding a trigger based on commit message next.

**Comment by hoodmane** [comment]
Thanks @lesteve!

**Comment by lesteve** [comment]
Summary:
- precommit.ci is unhappy but this should be fixed by #4938 I think
- right now test-scipy is triggered on push and on PR commits if `[scipy]` is in the commit message. I can change the commit marker as you wish, let me know if you have suggestions! It feels like triggering on push is a good idea because a PR can be merged without thinking it may break scipy tests but then you have test-scipy run on `main` so you have a chance to notice.
- the commit based trigger inside a PR seems to be working: test-scipy is run if `[scipy]` is in the commit message in https://github.com/pyodide/pyodide/pull/4935/commits/3e9386308174d867a394c40d2b537468e608640c [build URL](https://github.com/pyodide/pyodide/actions/runs/9950795300?pr=4935) test-scipy is skipped in https://github.com/pyodide/pyodide/pull/4935/commits/bbd36ec699c395599d9ad65437c7dcd6be261521 [build URL](https://github.com/pyodide/pyodide/actions/runs/9951854501?pr=4935).
- this roughly adds 15 minutes to build-core on ubuntu-latest (from ~15 minutes to ~30 minutes)
- test-scipy is an additional 20 minutes when triggered

**Comment by hoodmane** [comment]
I'll go ahead and merge this since the firefox test is a flake and pre-commit is hopefully fixed on main by #4938.

**Comment by hoodmane** [comment]
Thanks @lesteve!

**Comment by lesteve** [comment]
Yeah pre-commit.ci is green, I figured that the issue with codespell was actually to use small letters in the ignore file, oh well ...

At least the last commit is a good test to show that when the `[scipy]` marker is not in the commit message, scipy is not built and the scipy tests is skipped.

**Review by ryanking13 — APPROVED** [review]
Thanks @lesteve!

**Comment by lesteve** [comment]
The `build-libraries` step timed out after 1 hour in my previous commit see [build log](https://app.circleci.com/pipelines/github/pyodide/pyodide/7527/workflows/80d6d6ac-e14f-499d-80a2-a8e10bc29bd7/jobs/107567), this seems to happen in `main` as well recently: see [this](https://app.circleci.com/pipelines/github/pyodide/pyodide?branch=main)

**Comment by hoodmane** [comment]
Scipy tests pass so I'll merge it. Thanks again @lesteve!

**Comment by hoodmane** [comment]
Thanks so much for your help with scipy! It makes my life a lot easier and I think we are getting better outcomes.

**Pull request merged**
