### PR TITLE
Bump pydantic version used in pyodide-build to v2

### PR DESCRIPTION
**Pull request by ryanking13**
### Description

Bumps pydantic version in pyodide-build to make further changes easier.

### Checklists

- [x] Add / update tests

### CODE REVIEW

**Comment by ryanking13** [comment]
Oh... sphinx-js also use pydantic v1...

**Comment by hoodmane** [comment]
Now sphinx-js is no longer using pydantic, so I guess you could merge main and merge this?

**Comment by ryanking13** [comment]
Great thanks!

**Review by hoodmane — APPROVED** [review]
Thanks for this maintenance work @ryanking13!

**Comment by ryanking13** [comment]
Thanks for the review!

**Pull request merged**
