### PR TITLE
CI Build with M1 runner

### PR DESCRIPTION
**Pull request by ryanking13**
Test M1 runner as suggested by @cclauss.

### CODE REVIEW

**Comment by cclauss** [comment]
Pre-commit fixes in
* #4677

**Comment by ryanking13** [comment]
The build seems 2x faster, which is very impressive.

**Comment by cclauss** [comment]
Please rebase to get pre-commit fixes.

**Comment by cclauss** [comment]
GitHub Actions blog:
> Over the next 12 weeks, jobs using the `macos-latest` runner label will migrate from macOS 12 (Monterey) to macOS 14 (Sonoma).

https://github.blog/changelog/2024-04-01-macos-14-sonoma-is-generally-available-and-the-latest-macos-runner-image

**Review by cclauss — APPROVED** [review]

**Comment by hoodmane** [comment]
Thanks @ryanking13 and @cclauss!

**Pull request merged**
