### PR TITLE
Fix Robot Raconteur -Wenum-constexpr-conversion build error

### PR DESCRIPTION
**Pull request by johnwason**
### Description

Fixes build failure in the Robot Raconteur package. This failure was caused by a `-Wenum-constexpr-conversion` error that appears to be in a boost header file. LLVM recently added this error check. This fix disables the error check.

### CODE REVIEW

**Comment by johnwason** [comment]
@hoodmane do you have any suggestions why the tests are failing?

**Comment by hoodmane** [comment]
Looks like another missing Emscripten signature. Should be possible to figure out what's going on by adding some logging to the Emscripten dynamic linking code.

**Comment by johnwason** [comment]
Will `PYODIDE_ASSERTIONS` show more detail?

**Comment by hoodmane** [comment]
Probably `EXTRA_LDFLAGS=-sDYLINK_DEBUG` together with `PYODIDE_ASSERTIONS` would be sufficient.

**Comment by johnwason** [comment]
It looks like `0002-library-eventloop-signatures.patch` was deleted. This would explain why the signatures are incorrect. They haven't updated the upstream emscripten source.

**Comment by hoodmane** [comment]
Oh sorry, I think I saw the rebase conflict and mistakenly thought the `eventloop-signatures` patch had been upstreamed. That explains why this package wasn't working.

**Comment by johnwason** [comment]
I updated the upstream https://github.com/emscripten-core/emscripten/pull/17264 and added the patch back.

**Comment by johnwason** [comment]
This should be ready

**Comment by hoodmane** [comment]
Thanks @johnwason@

**Pull request merged**
