### PR TITLE
using javascript native response.json()

### PR DESCRIPTION
**Pull request by pandian912**
### Description

For large responses converting to string and then back to json adds a lot of overhead.
Instead the json can be directly fetched from the javascript fetch response object.
https://developer.mozilla.org/en-US/docs/Web/API/Response/json 

### Checklists

- [ ] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry
- [ ] Add / update tests
- [ ] Add new / update outdated documentation

### CODE REVIEW

**Comment by hoodmane** [comment]
Thanks for making the PR. This completely changes the return value: instead of returning a Python mix of dicts and lists, it returns a JsProxy. Maybe we could add another method that does this. But the point of `pyfetch` is to return Python objects, if you want a JsProxy, you can do 
```py
from js import fetch
resp = await fetch(url)
json = await resp.json()
```
so I'm not completely sure that one is needed.

Perhaps another approach would be to do `self.js_response.json().to_py()` but I think converting the string is likely to be more efficient.

 @rth

**Comment by ryanking13** [comment]
I think we need some benchmark for this, comparing the speed of:

1. `resp.json()`
2. `json.loads(resp.string())`
3. `resp.json().to_py()`

**Comment by pandian912** [comment]
1) the type output in the console put me off a bit. I actually thought that pyfetch was returning a Proxy
`  
    js.console.log(response.status, type(resp_json), resp_json, resp_json.keys())
      js.console.log(response.status, to_js(type(resp_json)), to_js(resp_json), to_js(resp_json.keys()))
`
`200 Proxy {arguments: null, caller: null, prototype: undefined, $$: {…}} Proxy {$$: {…}} Proxy {$$: {…}}
pyodide.asm.js:14 
200 Proxy {arguments: null, caller: null, prototype: undefined, $$: {…}} Map(4) {'userId' => 1, 'id' => 1, 'title' => 'delectus aut autem', 'completed' => false} Proxy {$$: {…}}`


2) I ran basic perf test with tiny and huge json files, I dont see any noticeable changes in either of the 2 approaches

**Comment by rth** [comment]
> I dont see any noticeable changes in either of the 2 approaches

In that case, should we close this PR? If performance is comparable,  I would also say that `json.loads(response.text())` should give easier to debug error messages when in fail, as compared to recursively converting js objects to python dict.

**Comment by pandian912** [comment]
Yeah sounds good to me.

**Pull request closed without merging**
