### PR TITLE
ENH Simplify shared library loading process

### PR DESCRIPTION
**Pull request by ryanking13**
Instead of calling `loadWebAssemblyModule` and save it to `preloadedWasm`, directly call `loadDynamicLibrary` with proper fs args to locate other shared libs that are dependent.

This PR also removes one partially related scipy patch (I think is was okay to remove that patch even before this PR)

### CODE REVIEW

**Comment by hoodmane** [comment]
I don't think we should load all dynamic libraries globally. What if two of them define the same symbol? Does it not work to use the `shared` flag to control whether the library is loaded globally?

**Comment by ryanking13** [comment]
> I don't think we should load all dynamic libraries globally. What if two of them define the same symbol? Does it not work to use the `shared` flag to control whether the library is loaded globally?

Good point! Fixed it.

**Comment by ryanking13** [comment]
Opened a separate issue about the `reboundx` failure: #2960

**Review by hoodmane — APPROVED** [review]
Nice work @ryanking13!

**Pull request merged**
