### PR TITLE
Add `clingo` package

### PR DESCRIPTION
**Pull request by peter-gy**
### Description

Adds https://pypi.org/project/clingo/, a powerful Answer Set Programming (ASP) solver.
Other projects also brought Clingo to web via WASM:

- https://github.com/Aluriak/webclingo-example
- https://github.com/domoritz/wasm-clingo
- https://github.com/domoritz/clingo-wasm
- https://github.com/cmudig/draco2 (custom Pyodide build, deployed to https://dig.cmu.edu/draco2/jupyterlite/static/pyodide/console.html)

However, it would be the nicest to have the recipe as part of the official Pyodide repo.

### Checklists

- [x] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry
- [x] Add / update tests
- [x] Add new / update outdated documentation

### CODE REVIEW

**Review by agriyakhetarpal — APPROVED** [review]
Thanks, @peter-gy! I'd like to note that in case you need a later version of `clingo` for `draco2`'s JupyterLite playground later on, you'd need to build it for WASM yourself as it is prior to this PR, because the version of `clingo` in Pyodide would be coupled with the Pyodide version. There are plans to change this by unvendoring recipes to separate repositories with #4918.

**Comment by peter-gy** [comment]
> Thanks, @peter-gy! I'd like to note that in case you need a later version of `clingo` for `draco2`'s JupyterLite playground later on, you'd need to build it for WASM yourself as it is prior to this PR, because the version of `clingo` in Pyodide would be coupled with the Pyodide version. There are plans to change this by unvendoring recipes to separate repositories with #4918.

Thanks for the heads up, @agriyakhetarpal! That's completely OK.
We have been building `clingo` ourselves, but the maintenance of the associated CI/CD pipeline is a massive headache. I am opening these PRs (this is companion of #5183) so that slowly but surely we can rely more and more on the official pipeline here, in the Pyodide repo.

**Comment by peter-gy** [comment]
Hey @agriyakhetarpal, can you see anything specific to this PR causing 
[ci/circleci: test-core-node](https://app.circleci.com/jobs/github/pyodide/pyodide/117862) to fail?

**Comment by hoodmane** [comment]
Thanks @peter-gy!

**Pull request merged**
