### PR TITLE
Add package `brotli`

### PR DESCRIPTION
**Pull request by MuTsunTsai**
### Description

This is related to issue #2921. Add compression package `brotli`.

### Checklists

- [x] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry
- [x] Add / update tests
- [x] Add new / update outdated documentation

### CODE REVIEW

**Comment by MuTsunTsai** [comment]
Um, not sure why `test-python` failed... I suppose I didn't touch anything related?

**Review by ryanking13 — COMMENTED** [review]
Thanks, @MuTsunTsai! 

> Um, not sure why test-python failed... I suppose I didn't touch anything related?

Don't worry, the error is not related to your PR.

The error in `test-packages...` seems to be related to the pytest importing mechanism. I opened a PR that (hopefully) fixes it (#2926).

**Comment by ryanking13** [comment]
#2926 is merged. Could you merge upstream main branch to your PR @MuTsunTsai?

**Comment by MuTsunTsai** [comment]
Alright, looks like it's all OK now 😀

**Comment by ryanking13** [comment]
Thanks a lot, @MuTsunTsai!

**Comment by MuTsunTsai** [comment]
@ryanking13 Awesome, thanks! I saw that PR for 0.21.0 is also on its way so I assume a release containing this PR is coming soon?

**Comment by ryanking13** [comment]
> @ryanking13 Awesome, thanks! I saw that PR for 0.21.0 is also on its way so I assume a release containing this PR is coming soon?

Yes 0.21.0 release will include this PR.

**Pull request merged**
