### PR TITLE
MAINT Switch to pytest-pyodide

### PR DESCRIPTION
**Pull request by rth**
Use https://github.com/pyodide/pytest-pyodide instead of the repo included in this file.

The constraint this adds is that if some changes are necessary to that package one would need to make a PR to pytest-pyodide first.

Closes https://github.com/pyodide/pyodide/issues/2878 
Closes https://github.com/pyodide/pyodide/issues/2741

### CODE REVIEW

**Comment by ryanking13** [comment]
```
INTERNALERROR>     item.config.option.runtime != "host" and "runtime" not in item.fixturenames
INTERNALERROR> AttributeError: 'DoctestItem' object has no attribute 'fixturenames'
```

Oops...

**Comment by ryanking13** [comment]
It seems like the test `pyodide-build/pyodide_build/tests/test_pywasmcross.py::exports_node FAILED [ 96%]` was not running previously because its name contains "node" so it was filtered by -k "not node".

**Comment by rth** [comment]
Yeah, those are tricky. Maybe let's xfail it for now and fix separately.

**Comment by ryanking13** [comment]
> Yeah, those selectors are tricky. Maybe let's xfail it for now and fix it separately.

Yes, let's do it that way.

**Comment by ryanking13** [comment]
Thanks, @rth!

**Comment by hoodmane** [comment]
Do we need to update the instructions for how to test Pyodide/set up the development environment? People have been confused about this lately. Presumably the first time you use the docker environment you need `pip install pytest-pyodide-git-url`?

**Comment by ryanking13** [comment]
> Do we need to update the instructions for how to test Pyodide/set up the development environment? People have been confused about this lately. Presumably the first time you use the docker environment you need `pip install pytest-pyodide-git-url`?

Yes, we should now mention in docs that `pytest-pyodide` is a test dependency.

**Pull request merged**
