### PR TITLE
Add `crc32c`

### LINKED ISSUE #4787: `crc32c`
## 🐍 Package Request

- Package Name and Version : `crc32c`, version 2.4
- Package URL : https://pypi.org/project/crc32c/, https://github.com/ICRAR/crc32c
- Package Dependencies that needs to be resolved first: [none](https://github.com/ICRAR/crc32c/blob/master/setup.py) – this is a package written in C with Python bindings.

## 📝 Additional context

xref: https://github.com/zarr-developers/zarr-python/pull/1903, i.e., this is a required dependency of the upcoming version 3 for Zarr at the time of writing.

### PR DESCRIPTION
**Pull request by agriyakhetarpal**
### Description

This PR adds the `crc32c` package and closes #4787. `crc32c` is a required dependency for the upcoming version 3 for Zarr.

### Checklists

- [x] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry
- [x] Add / update tests
- [ ] Add new / update outdated documentation

### Additional context

xref: zarr-developers/zarr-python#1903

### CODE REVIEW

**Comment by agriyakhetarpal** [comment]
The [logs](https://github.com/pyodide/pyodide/actions/runs/9215577958/job/25354633728?pr=4789#step:7:187) are reporting a `ModuleNotFound` error for `import crc32c`, and there is no error trace. Maybe I need to do `import crc32c` inside `@run_in_pyodide(packages=["crc32c"])`? I just pushed f2d1cdf96357cfccb258c1fb3604ab06440bffeb, let me see if that fixes it.

**Review by ryanking13 — COMMENTED** [review]
Thanks! The pytest is complaining about the `NameError: name 'as_individual_bytes' is not defined`.

**Comment by agriyakhetarpal** [comment]
The tests should pass now, thanks, @ryanking13! I guess `@run_in_pyodide` is sandboxed from the rest of the code or something – I moved `as_individual_bytes()` to inside the test so that it can be accessed by `test_piece_by_piece` directly. Ready for review/merging.

**Comment by hoodmane** [comment]
Thanks!

**Pull request merged**
