### PR TITLE
0.22.0

### PR DESCRIPTION
**Pull request by ryanking13**
Close: #3340 

### Checklists

- [x] Update version strings
- [x] Check which files are included in JS package:

<details>
    <summary>NPM deploy dry run result</summary>

```sh
DRY_RUN=1 ./deploy_to_npm.sh
Dry run: npm publish --tag 0.22.0
npm notice 
npm notice 📦  pyodide@0.22.0
npm notice === Tarball Contents === 
npm notice 2.7kB   README.md       
npm notice 7.4kB   console.html    
npm notice 3.3kB   package.json    
npm notice 153.6kB pyodide_py.tar  
npm notice 5.0MB   pyodide.asm.data
npm notice 1.5MB   pyodide.asm.js  
npm notice 7.5MB   pyodide.asm.wasm
npm notice 24.7kB  pyodide.d.ts    
npm notice 21.4kB  pyodide.js      
npm notice 77.9kB  pyodide.js.map  
npm notice 20.9kB  pyodide.mjs     
npm notice 77.7kB  pyodide.mjs.map 
npm notice 8.2kB   repodata.json   
npm notice === Tarball Details === 
npm notice name:          pyodide                                 
npm notice version:       0.22.0                                  
npm notice filename:      pyodide-0.22.0.tgz                      
npm notice package size:  6.1 MB                                  
npm notice unpacked size: 14.5 MB                                 
npm notice shasum:        77794bd4faec626cac866380f3a04bd93f1ba026
npm notice integrity:     sha512-grdqjaUl3Lpq1[...]rR0cA7p4ALg5g==
npm notice total files:   13                                      
npm notice 
npm WARN This command requires you to be logged in to https://registry.npmjs.org/ (dry-run)
npm notice Publishing to https://registry.npmjs.org/ (dry-run)
+ pyodide@0.22.0
```

</details>

- [x] Cleanup Changelog
- [x] Add list of contributors
- [x] Check documentation warnings  #3391

<details>
    <summary>Doc warnings</summary>

```
/home/docs/checkouts/readthedocs.org/user_builds/pyodide/checkouts/3389/docs/project/changelog.md:94: WARNING: more than one target found for 'any' cross-reference 'JsBuffer': could be :py:class:`pyodide.ffi.JsBuffer` or :py:class:`pyodide.JsBuffer`
/home/docs/checkouts/readthedocs.org/user_builds/pyodide/checkouts/3389/docs/project/changelog.md:94: WARNING: more than one target found for 'any' cross-reference 'JsPromise': could be :py:class:`pyodide.ffi.JsPromise` or :py:class:`pyodide.JsPromise`
/home/docs/checkouts/readthedocs.org/user_builds/pyodide/checkouts/3389/docs/project/changelog.md:124: WARNING: 'any' reference target not found: shorten
/home/docs/checkouts/readthedocs.org/user_builds/pyodide/checkouts/3389/docs/project/changelog.md:142: WARNING: 'any' reference target not found: captureThis
/home/docs/checkouts/readthedocs.org/user_builds/pyodide/checkouts/3389/docs/project/changelog.md:416: WARNING: 'any' reference target not found: loadPyodide
/home/docs/checkouts/readthedocs.org/user_builds/pyodide/checkouts/3389/docs/project/changelog.md:912: WARNING: 'any' reference target not found: JsProxy.to_string
/home/docs/checkouts/readthedocs.org/user_builds/pyodide/checkouts/3389/docs/project/changelog.md:912: WARNING: 'any' reference target not found: JsProxy.to_bytes
/home/docs/checkouts/readthedocs.org/user_builds/pyodide/checkouts/3389/docs/project/changelog.md:912: WARNING: 'any' reference target not found: JsProxy.to_memoryview
/home/docs/checkouts/readthedocs.org/user_builds/pyodide/checkouts/3389/docs/project/changelog.md:916: WARNING: 'any' reference target not found: JsProxy.to_file
/home/docs/checkouts/readthedocs.org/user_builds/pyodide/checkouts/3389/docs/project/changelog.md:916: WARNING: 'any' reference target not found: JsProxy.from_file
/home/docs/checkouts/readthedocs.org/user_builds/pyodide/checkouts/3389/docs/project/changelog.md:1661: WARNING: Failed to create a cross reference. A title or caption not found: micropip
/home/docs/checkouts/readthedocs.org/user_builds/pyodide/checkouts/3389/docs/project/release-notes/v0.17.0.md:105: WARNING: 'any' reference target not found: JsProxy.then
/home/docs/checkouts/readthedocs.org/user_builds/pyodide/checkouts/3389/docs/project/release-notes/v0.17.0.md:105: WARNING: 'any' reference target not found: JsProxy.catch
/home/docs/checkouts/readthedocs.org/user_builds/pyodide/checkouts/3389/docs/project/release-notes/v0.17.0.md:105: WARNING: 'any' reference target not found: JsProxy.finally_
/home/docs/checkouts/readthedocs.org/user_builds/pyodide/checkouts/3389/docs/project/release-notes/v0.17.0.md:148: WARNING: 'any' reference target not found: JsProxy.assign
/home/docs/checkouts/readthedocs.org/user_builds/pyodide/checkouts/3389/docs/project/release-notes/v0.17.0.md:148: WARNING: 'any' reference target not found: JsProxy.assign_to
/home/docs/checkouts/readthedocs.org/user_builds/pyodide/checkouts/3389/docs/sphinx_pyodide/README.md:18: WARNING: Could not lex literal_block as "pyodide". Highlighting skipped.
/home/docs/checkouts/readthedocs.org/user_builds/pyodide/checkouts/3389/docs/usage/type-conversions.md:470: WARNING: 'any' reference target not found: JsProxy.assign
/home/docs/checkouts/readthedocs.org/user_builds/pyodide/checkouts/3389/docs/usage/type-conversions.md:481: WARNING: 'any' reference target not found: JsProxy.assign
/home/docs/checkouts/readthedocs.org/user_builds/pyodide/checkouts/3389/docs/usage/type-conversions.md:481: WARNING: 'any' reference target not found: JsProxy.assign_to
``` 

</details>

- [ ] Release notes https://github.com/pyodide/pyodide-blog/pull/34
- [x] Fix cli tests #3390 

- [x] #3396 
- [x] #3404

### CODE REVIEW

**Comment by rth** [comment]
Thanks for working on the release!

**Comment by rth** [comment]
Thanks again for managing the release! As far as I can tell all items on the TODO list are done (and the release notes also look good). Should we just go ahead an merge it? 

For https://github.com/pyodide/pyodide/pull/3405 we can cherry pick it after the release, since it's mostly doc rendering related so it's not a blocker.

**Comment by ryanking13** [comment]
Yeah, I think we can make a release now.

**Comment by ryanking13** [comment]
Okay, I hope the release CI will have no problem this time :pray: 😅

**Comment by hoodmane** [comment]
I think I have it locally.

**Comment by rth** [comment]
Thanks!

**Comment by hoodmane** [comment]
Thanks everyone!

**Comment by ryanking13** [comment]
> Just a minor thing, looks like we forgot to create the 0.21.X branch before dropping it

Hmm, I think I pushed to 0.21.X... probably I should missed something. Anyway, thanks and enjoy your vacation!

> Everything looks good thanks!

Actually, releasing `pyodide-py` failed (https://github.com/pyodide/pyodide/actions/runs/3829966769/jobs/6517241654)

I guess the reason for the failure is that the name of the package in src/py/setup.cfg is set to "pyodide" not "pyodide-py"?

https://github.com/pyodide/pyodide/blob/57d4412b747b695521debb47e012a6a74b2fb320/src/py/setup.cfg#L2

**Pull request merged**
