### PR TITLE
Improve pyodide.loadPackage docs

### PR DESCRIPTION
**Pull request by rth**
Improve `pyodide.loadPackage` documentation which was a bit outdated.

Though in https://github.com/pyodide/pyodide/issues/2045 there is a proposal to,
> Remove support for loading from URLs in pyodide.loadPackage

while this goes in a bit different direction of documenting the current behavior.

### CODE REVIEW

**Comment by hoodmane** [comment]
> Remove support for loading from URLs in pyodide.loadPackage

I am pretty sure we are not going to do this.

**Comment by rth** [comment]
Agreed.

**Comment by hoodmane** [comment]
Someone needs to filter through that and locate the ideas that we should still discuss or implement and make a new issue with just these action items. But it takes a while to get around to these things...

**Review by ryanking13 — APPROVED** [review]
Thanks @rth!

**Pull request merged**
