### PR TITLE
DOCS: Help Spinx find ffi types

### PR DESCRIPTION
**Pull request by hoodmane**
Two fixes:

The `pyodide.ffi` stuff is defined in `_pyodide._core_docs`. We don't want `_pyodide._core_docs` to appear in the documentation because this isn't where you should import things from so we override the `__name__` of `_pyodide._core_docs` to be `pyodide.ffi`. But then Sphinx fails to locate the source for the stuff defined in `_pyodide._core_docs`. This patches `ModuleAnalyzer` to tell it to look for the source of things from `pyodide.ffi` in `_pyodide._core_docs`.

If a function has a typing.overload then the code path that sphinx-autodoc takes is not one that sphinx-autodoc-typehints can handle.
See https://github.com/tox-dev/sphinx-autodoc-typehints/issues/296

### CODE REVIEW

**Comment by ryanking13** [comment]
> We don't want _pyodide._core_docs to appear in the documentation

Where does this appear in docs? I can't find an example.

**Comment by hoodmane** [comment]
It doesn't appear in the docs because of the hack here:
https://github.com/pyodide/pyodide/blob/main/src/py/_pyodide/_core_docs.py?plain=1#L38
But that hack confuses the sphinx analyzer.

I think this change actually makes no difference in the docs right now because there are no attributes in `_core_docs.py`. But depending on what you put in there, there are sometimes examples where the docs are rendered inconsistently with other files because of the `__name__` hack.

**Review by ryanking13 — APPROVED** [review]
Great, thanks for the explanation!

**Comment by hoodmane** [comment]
Thanks for the review!

**Pull request merged**
