### PR TITLE
Update zengl to 2.5.0

### PR DESCRIPTION
**Pull request by szabolcsdombi**
### Checklists

- [x] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry
- [x] Add / update tests
- [x] Add new / update outdated documentation

### CODE REVIEW

**Comment by ryanking13** [comment]
Thanks @szabolcsdombi! There was a timeout in CI, so I re-ran it. Let's see if it passes.

**Comment by ryanking13** [comment]
Could you merge the main branch + fix the conflict? I just fixed the safari CI issue.

**Comment by szabolcsdombi** [comment]
@ryanking13 thank you for the quick reply, I have squashed all changes and rebased on top of the main branch.

**Comment by ryanking13** [comment]
Thanks!

**Comment by szabolcsdombi** [comment]
thank you!

**Pull request merged**
