### PR TITLE
Bump emscripten to 3.1.15

### PR DESCRIPTION
**Pull request by ryanking13**
### Description

There are 3 packages (opencv-python, xgboost and pyproj) that were broken when we tried to update Emscripten to 3.1.15.
The error happens in `__wasm_call_ctors`, which is a constructor function called during the initialization of the WASM module.

Between emscripten 3.1.14 and 3.1.15, the behavior related to `__wasm_call_ctors` has been slightly changed.

Before 3.1.15, the data relocation happened "before" `__wasm_call_ctors`, while in 3.1.15, it happens "after" the `__wasm_call_ctors`. To be honest, I don't fully understand the rationale for this change.
(See: https://github.com/llvm/llvm-project/commit/53217ecb882c25bb69e6065512a0627828d6e870)

~So I added a patch that retries `__wasm_call_ctors` after data relocation if it fails. It works, but I'm not sure whether this is a proper fix though.~

_Edit:_

Used upstream commit: https://github.com/emscripten-core/emscripten/pull/17628

### Checklists

- [x] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry

### CODE REVIEW

**Comment by ryanking13** [comment]
Upstream issue about this error: https://github.com/emscripten-core/emscripten/issues/17601

**Comment by hoodmane** [comment]
Great!

**Comment by ryanking13** [comment]
@hoodmane can we merge this?

**Comment by hoodmane** [comment]
I suppose so. I guess we'll switch to doing #2951 when we release 0.22.0?

**Comment by ryanking13** [comment]
> I suppose so. I guess we'll switch to doing #2951 when we release 0.22.0?

Yes probably. Though I'm not 100% sure that we can follow it as Python releases annually while emscripten develops much faster than that.

> As a followup we can presumably update to 3.1.18 without further issue.

I hope that 3.1.18 update will be much smoother 😂

**Pull request merged**
