### PR TITLE
Add wabt to docker image

### PR DESCRIPTION
**Pull request by hoodmane**
This is needed for #3210. It is also a really helpful dev tool, so it will be nice to have it. This PR adds ~10mb to the docker image.

### CODE REVIEW

**Review by ryanking13 — APPROVED** [review]
Thanks!

**Comment by hoodmane** [comment]
I guess I'll push the new docker image and open a follow-up pr to switch to using it.

**Comment by hoodmane** [comment]
Okay looks like you're going to do it.

**Comment by ryanking13** [comment]
> I guess I'll push the new docker image and open a follow-up pr to switch to using it.

I opened a PR which also updates the docker image #3219, let's push a new docker image after merging it too.

**Pull request merged**
