### PR TITLE
Bump main to 0.18.0dev0

### PR DESCRIPTION
**Pull request by rth**
We really should automate some of these replacements in the docs. The issue last time I tried was that sphinx replacements didn't work inside code blocks.

### CODE REVIEW

**Comment by hoodmane** [comment]
I can write a shell script if you like?

**Comment by rth** [comment]
> I can write a shell script if you like?

I think https://pypi.org/project/bumpversion/ should work for this. We already have a partial config in `setup.cfg`, we just need to start using it. And maybe pick a maintained fork since it's no longer maintained.

**Comment by hoodmane** [comment]
Darn that would have been fun.

**Comment by rth** [comment]
OK, version warning failed building docs on main with,
```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyodide/envs/latest/lib/python3.8/site-packages/sphinx/events.py", line 111, in emit
    results.append(listener.handler(self.app, *args))
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyodide/envs/latest/lib/python3.8/site-packages/versionwarning/signals.py", line 40, in generate_versionwarning_data_json
    message=message.format(
AttributeError: 'tuple' object has no attribute 'format'
```
and I can't reproduce locally so far.

**Pull request merged**
