### PR TITLE
Canonicalize requirement names in micropip

### PR DESCRIPTION
**Pull request by hoodmane**
Use canonicalize_name rather than our own custom version.
Use canonicalize_name also on requirements.

- [ ] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry
- [ ] Add / update tests

### CODE REVIEW

**Review by rth — APPROVED** [review]
Yes, makes sense, thanks!

**Comment by ryanking13** [comment]
Thanks, @hoodmane. I read the original bug report in the Gitter, and I can confirm that there is a bug in processing the package name.

However, I don't think this change is what we intended. What `normalize_package_name` was doing is to normalize package names to wheel filename format following [PEP 427](https://peps.python.org/pep-0427/#escaping-and-unicode). For example, it converts `keras-Preprocessing` to `keras_preprocessing`. On the other hand, `canonicalize_name` does the opposite: converts underscore to dash (`keras_preprocessing` to `keras-preprossing`).

I think the correct place to be fixed is here:

https://github.com/pyodide/pyodide/blob/663459e26b71c7bbc6808b955c91398009de6803/packages/micropip/src/micropip/_micropip.py#L359-L363

These lines were meant to retrieve the correct project name from the wheel metadata file. It is needed when micropip installs a package from a wheel file directly. But I think it is not working as intended somehow.

**Comment by hoodmane** [comment]
Well I guess we need better test coverage. But pip itself uses `canonicalize_name` so if we're going based on what pip does it would make sense. Does it matter which way we go as long as we're consistent?

**Comment by rth** [comment]
OK, I should have waited before merging. 

Yes, though as long as the projection allows to disambiguate common variations in package names, it shouldn't matter if `Keras-Preprocessing` is converted to `keras_preprocessing` or `keras-preprocessing`, should it? It's an internal key anyway.

**Comment by ryanking13** [comment]
I read how PyPI normalizes package names in [PEP 503](https://peps.python.org/pep-0503/) and I think Hood was right. Using caconicalized name seems more suitable for this case.

> It's an internal key anyway.

We still need to correct way to retrieve and save "original" name of the package from the wheel file for `micropip.list()` though, since we don't want to show canonicalized name to users.

**Comment by hoodmane** [comment]
Do we show them the name they asked for? What if it showed up because of a transitive requirement? Showing the canonicalized name in micropip.list doesn't seem terrible to me but I guess it's not ideal if the user specifically asked for a different name.

**Comment by ryanking13** [comment]
> Showing the canonicalized name in micropip.list doesn't seem terrible to me but I guess it's not ideal if the user specifically asked for a different name.

Yes, it's not terrible but it can be improved.

```py
>>> import micropip
>>> await micropip.install("weeby.py")
>>> micropip.list()
Name               | Version   | Source
------------------ | --------- | -------
...
weeby-py           | 0.1.6     | pypi
...
>>> "weeby.py" in micropip.list()
True
>>> "weeby-py" in micropip.list()
True
>>> "weeby_py" in micropip.list()
True
>>> "WEEBY_PY" in micropip.list()
True
```

**Comment by hoodmane** [comment]
I think the one with `weeby.py` should be false all others true. This would be consistent with the behavior of importlib.metadata.

**Pull request merged**
