### PR TITLE
MNT Update scikit-learn to 1.3.0

### PR DESCRIPTION
**Pull request by glemaitre**
### Description

Trying to update the version of scikit-learn to 1.3.0

### Checklists

- [x] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry

### CODE REVIEW

**Comment by lesteve** [comment]
The CI failures (netCDF4) are not related to this PR (netCDF4-related) and are also in `main` (e.g. see [build log](https://app.circleci.com/pipelines/github/pyodide/pyodide/6038/workflows/4d59b8f8-4921-4373-90a2-4b5623341e94/jobs/77007)

**Review by rth — APPROVED** [review]
Thanks @glemaitre ! The CI issue should be fixed with https://github.com/pyodide/pyodide/pull/3977. Could you sync with `main`?

**Comment by glemaitre** [comment]
@rth I just sync with `main`.

**Comment by ogrisel** [comment]
@rth could you please add a comment to https://github.com/scikit-learn/scikit-learn/issues/26763 once the next pyodide version is out?

What is the typical release frequency of pyodide?

**Comment by hoodmane** [comment]
We do 3-4 "major" releases a year. We're planning a release in the next couple of weeks.

**Pull request merged**
