### PR TITLE
also lowercase when normalizing micropip package names

### PR DESCRIPTION
**Pull request by bollwyvl**
### Checklists

- [x] Add / update tests

This extends #2414 to include uppercase characters.

### CODE REVIEW

**Review by hoodmane — APPROVED** [review]
Thanks @bollwyvl! Looks good aside from linter error.

**Comment by rth** [comment]
Or you could just sync with main and pre-commit.ci should take care of it.

**Comment by bollwyvl** [comment]
Thanks for the quick review, all: looks like the linter has been appeased!

**Comment by ryanking13** [comment]
Thanks for catching this, @bollwyvl!

**Pull request merged**
