### PR TITLE
Backports for 0.22.1

### PR DESCRIPTION
**Pull request by hoodmane**

### CODE REVIEW

**Comment by rth** [comment]
Thanks for fixing a lot of those 0.22.0 issues! It looks like nothing is left in 0.21.1 milestone, do you plan to add more fixes before merging this?

**Comment by hoodmane** [comment]
There's a few more that need to be cherry picked but then I think we can release 0.21.1.

**Comment by hoodmane** [comment]
Maybe we can include #3496. We should also fix the console deploy...

**Comment by ryanking13** [comment]
> We should also fix the console deploy...

It seems like readthedocs changed the output directory from `_build` to `_readthedocs`, which broke our console.html deploy.

- https://github.com/readthedocs/readthedocs.org/pull/9888

**Pull request merged**
