### PR TITLE
Add gmpy2 and its dependencies

### PR DESCRIPTION
**Pull request by eagleoflqj**
### Description

Add gmpy2 and its dependencies libmpc, libmpfr and libgmp. gmpy2 is an optional dependency of SymPy.
I don't know how building parameters should be configured for the dependencies, so I keep them minimal.
I tested the built gmpy2 package with SymPy. It generally works fine and test errors are all due to SymPy code.
### Checklists

- [x] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry
- [x] Add / update tests

### CODE REVIEW

**Comment by hoodmane** [comment]
Looks good to me. Could you add a few more tests?

**Comment by hoodmane** [comment]
I guess this already has pretty good test coverage on sympy though. Thanks for adding us to sympy CI!

**Comment by eagleoflqj** [comment]
Now tests cover main parts of gmpy2: mpc, mpz, mpq and mpfr.
I also corrected a previous changelog PR number.

**Comment by hoodmane** [comment]
Thanks @eagleoflqj!

**Pull request merged**
