### PR TITLE
DOC Update Github Actions example to latest versions

### PR DESCRIPTION
**Pull request by viblo**
### Description

This PR updates the github actions example to build a library in the docs to use latest version of the actions used. (I tested this on my own library, here: https://github.com/viblo/pymunk/actions/runs/7860843245/job/21448495731 )

### Checklists

- [X] Add new / update outdated documentation

### CODE REVIEW

**Comment by hoodmane** [comment]
Thanks!

**Comment by hoodmane** [comment]
@ryanking13 it might be good to have a reminder somewhere to update this, perhaps as part of release notes...

**Comment by ryanking13** [comment]
> @ryanking13 it might be good to have a reminder somewhere to update this, perhaps as part of release notes...

Yes, probably. But I think it's not really critical to keep the action version up-to-date unless the old actions are broken. So I think it's positive that new contributors sometimes find things like this and raise PRs to fix the documentation.

**Review by ryanking13 — APPROVED** [review]

**Comment by hoodmane** [comment]
But for instance the Python version here is still 3.11.

**Comment by viblo** [comment]
Ah, I didnt update the python version since I only tried with the stable release of pyodide and not the upcoming version, and didnt reflect on the version of documentation or that the new version supports 3.12..

**Comment by hoodmane** [comment]
Reasonably enough. I think this is good because as-is I can cherry-pick this commit to update the existing docs.

**Comment by ryanking13** [comment]
> But for instance the Python version here is still 3.11.

Oh yeah, the Python version needs to be updated...

**Pull request merged**
