### PR TITLE
Use rich for status bar

### PR DESCRIPTION
**Pull request by hoodmane**
As suggested in #2074. Turns out it's very simple. The docker environment needs to be updated to include rich though.

### CODE REVIEW

**Comment by hoodmane** [comment]
This works very nicely locally, in CI I think the original code without either #2064 or this works best.

**Comment by rth** [comment]
Interesting. It's also more code than I thought it would be. But I suppose it's also more robust and has better UI at least putting aside the CI rendering issues (tough I think this should be a known problem with possible solutions). Let's look back at it after the release.

**Comment by ryanking13** [comment]
Maybe let's add rich to the requirements first  in a seperate PR, instead of putting `pip install rich` everywhere?

**Comment by ryanking13** [comment]
> Maybe let's add rich to the requirements first in a seperate PR, instead of putting `pip install rich` everywhere to make CI pass.

Actually, adding rich to the dependency of `pyodide-build` would be better.

**Pull request closed without merging**
