### PR TITLE
Raise error when trying to install a non-pure python wheel

### PR DESCRIPTION
**Pull request by ryanking13**
Related Issue: #1683

This PR makes micropip raise an error when trying to install a non-pure (platform-dependent) python wheel.

### CODE REVIEW

**Comment by hoodmane** [comment]
Thanks @ryanking13! Looks like a decent solution to me.

I was looking at [PEP 425](https://www.python.org/dev/peps/pep-0425/) and the [packaging](https://packaging.pypa.io/en/latest/tags.html#packaging.tags.sys_tags) apis. It seems that technically we can accept a lot more target triples, since we do implement the cpython ABI, so technically a wheel labeled e.g., `cp39-cp39-any` would work fine. I don't know if there are any wheels actually labeled like this in the wild. Of course a package could be written in pure Python but use some CPython implementation details. Likely such a wheel in the wild would just be labeled `py3-none-any`. If these are indeed vanishingly rare, then it's not worth worrying about.

But we could consider only requiring that the platform be `any` instead of the whole triple being `py3-none-any`.

In the future we could consider distributing Pyodide extensions as wheels with triple`cp39-cp39-emscripten_wasm32`.

**Review by hoodmane — APPROVED** [review]

**Comment by ryanking13** [comment]
> But we could consider only requiring that the platform be any instead of the whole triple being py3-none-any.

According to PEP425, there can be a pypy/jython targeted package (I have never seen such cases in the wild though).

Maybe we can try something like:

```python
(
    python_tag.startswith(["py2.py3", "py3", "cp3"]) and \
    abi_tag.startswith(["none", "abi3", "cp3"]) and \
    platform_tag == "any"
)
```

**Comment by hoodmane** [comment]
> we can update the label checking logic later if needed?

Yes.

**Comment by hoodmane** [comment]
Thanks again!

**Pull request merged**
