### PR TITLE
DOCS Some edits to Python update documentation

### PR DESCRIPTION
**Pull request by hoodmane**
I added a reference to @vstinner's upgrade_pythoncapi tool which I learned about from his talk. I also added a table with links to previous python upgrades.

### CODE REVIEW

**Review by rth — APPROVED** [review]
Very nice indeed!

**Comment by hoodmane** [comment]
I guess I could use {pr}`####` style refs

**Comment by vstinner** [comment]
> I added a reference to @vstinner's upgrade_pythoncapi tool which I learned about from his talk

Aha, my talk at Pycon US was useful :-)

> Remove the `#include pythoncapi_compat.h` headers

Are you aware of the ``--no-compat`` command line option to not add ``#include <pythoncapi_compat.h>`` lines?

**Comment by hoodmane** [comment]
> Are you aware of the ``--no-compat`` command line option to not add ``#include <pythoncapi_compat.h>`` lines?

Well no. I'll have to update the instructions again thanks!

**Pull request merged**
