### PR TITLE
Rename out of tree CLI entrypoint

### PR DESCRIPTION
**Pull request by ryanking13**
Related: #2879

This PR renames the `pyodide` CLI entrypoint used for out-of-tree build to `pyodide-xbuild` (no strong opinion, please suggest a better name), so we can reserve the `pyodide` entrypoint for the future.

@hoodmane

### CODE REVIEW

**Comment by hoodmane** [comment]
Maybe keep it as `pyodide` but make an `xbuild` subcommand? I thought the plan was to have `pyodide` be the entrypoint for everything but then have various subcommands.

**Comment by ryanking13** [comment]
Perhaps then use `pyodide-build xbuild`  for now? I think `pyodide` entry point will be defined in a new package `pyodide-cli` and `pyodide-build` will be plugged into it, so we can separate a package that defines CLI interface and a package that does the build job.

**Comment by hoodmane** [comment]
Well I guess xbuild is also not a descriptive name since they are all cross builds. I guess we could call it `pyodide-build out-of-tree` and that would be more accurate.

**Comment by ryanking13** [comment]
> Well I guess xbuild is also not a descriptive name since they are all cross builds. I guess we could call it `pyodide-build out-of-tree` and that would be more accurate.

Okay, let's go with `pyodide-build out-of-tree` (or `out_of_tree` for consistency with other commands).

**Comment by rth** [comment]
Can we hold this for a day or two? Thinking about a better name and experimenting with a single entry point.

**Comment by jobovy** [comment]
Just the two cents of an outsider, but it seems weird to me to overly focus on 'out-of-tree', because long-term presumably almost all packages will be built 'out of tree' and that will be the normal build process (as it is for regular Python packages). So I would assume that 'out-of-tree' will be the normal 'build-package' going forward and reserve a more specialized name for 'in-tree' builds, which would only happen in this repository.

**Comment by hoodmane** [comment]
Well I think the goal here is to reserve the better Pyodide namespace for later. My thought with using the `pyodide` top level command for this is that `pyodide-build` can continue to be more or less private to the project and `pyodide` can be public. This is more or less holding over the public namespace for later. But until we fix the name it probably isn't wise to start adding this to the CI of many different packages because that will create a large amount of work if we decide to rename in the future.

**Comment by jobovy** [comment]
> But until we fix the name it probably isn't wise to start adding this to the CI of many different packages because that will create a large amount of work if we decide to rename in the future.

Right. Once you release the 'out-of'tree' capability, people will probably start using this (I'm planning to), so you should probably figure out the public API before releasing that if you can.

**Comment by hoodmane** [comment]
> you should probably figure out the public API before releasing that

Yeah I agree it needs to be a release blocker. Thanks for your feedback @jobovy!

**Comment by ryanking13** [comment]
> Can we hold this for a day or two? Thinking about a better name and experimenting with a single entry point.

Sure, I opened a draft PR for a single entry point (#2904)

> Right. Once you release the 'out-of'tree' capability, people will probably start using this (I'm planning to), so you should probably figure out the public API before releasing that if you can.

Right, I think we should be careful about releasing this capability in public. @hoodmane do you think we should document `create_xbuildenv`, `install_xbuildenv` in release `0.21.0`? Otherwise, we can keep it in private until it becomes more mature.

**Comment by hoodmane** [comment]
I intend for both `create_xbuildenv` and `install_xbuildenv` to remain private, at least until there is need for them to be public. I think any modification to the cross build environment can be done in tree because creating it involves multiple packages which depend on each other. The public out of tree build entry point can automatically download and install the cross build environment as needed.

**Comment by ryanking13** [comment]
> I intend for both `create_xbuildenv` and `install_xbuildenv` to remain private, at least until there is need for them to be public. I think any modification to the cross build environment can be done in tree because creating it involves multiple packages which depend on each other. The public out of tree build entry point can automatically download and install the cross build environment as needed.

Sounds good to me. In that case, probably it would be better to hide them [from the docs](https://pyodide.org/en/latest/usage/api/pyodide-build-cli.html).

**Comment by rth** [comment]
I proposed a few names in https://github.com/pyodide/pyodide/issues/2879#issuecomment-1195088519.

I think once we agree on the name, for this release it doesn't matter if the pyodide entrypoint is defined in pyodide-build (and not in a separate package which would take more work). As long as the name is forward compatible how it is implemented should be more or less transparent to users.

**Comment by ryanking13** [comment]
> I think once we agree on the name, for this release it doesn't matter if the pyodide entrypoint is defined in pyodide-build (and not in a separate package which would take more work). As long as the name is forward compatible how it is implemented should be more or less transparent to users.

That sounds reasonable to me.

**Comment by ryanking13** [comment]
Closing as this is not required for 0.21.0 release.

**Pull request closed without merging**
