### PR TITLE
Expose `optimize` and `dont_inherit` to `Console` and `CodeRunner`

### PR DESCRIPTION
**Pull request by CNSeniorious000**
### Description

Resolves https://github.com/pyodide/coderunner/issues/2

### Checklists

- [x] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry
- [x] Add / update tests
- [x] Add new / update outdated documentation

### CODE REVIEW

**Review by ryanking13 — APPROVED** [review]
Looks good to me. Thanks @CNSeniorious000, could you please update the changelog?

**Comment by CNSeniorious000** [comment]
OK. I just came up with a question, do we have linter or formatter for line width of docstrings / markdown files?

**Comment by ryanking13** [comment]
>  do we have linter or formatter for line width of docstrings

We let black to format the code whatever it wants :) All rules are defined in [pre-commit](https://github.com/pyodide/pyodide/blob/main/.pre-commit-config.yaml) and [pyproject.toml](https://github.com/pyodide/pyodide/blob/main/pyproject.toml).

> markdown files

I don't think we have specific rule for markdown files. I guess spellcheck will run against markdown files, but there aren't any rules.

**Comment by CNSeniorious000** [comment]
Just not sure where to insert line breaks in a long paragraph.

**Comment by ryanking13** [comment]
> Just not sure where to insert line breaks in a long paragraph sometimes.

We don't have a lint rule for line length in markdown files, but I think it would be nice to have one so we don't need to adjust the line length manually. Feel free to open a PR to add a lint rule for it.

**Pull request merged**
