### PR TITLE
Add `replace_nbsp` parameter to Console.push

### LINKED ISSUE #3337: REPL Copy-paste with spaces doesn't work
In Firefox if one writes anything with spaces then tries to copy-paste the input to a standard Python REPL, one gets,
```
SyntaxError: invalid non-printable character U+00A0
```
this is because spaces are replaced by this character in Firefox as least.

In Pyodide REPL,
```py
>>> 1 + 1
```
Copy-pasting quoted in the host Python REPL,
```py
>>> '1 + 1'
'1\xa0+\xa01'
```
Likely due to https://github.com/jcubic/jquery.terminal/blob/b23a628283e12bd8996a3a2d8676cff6d1587a7a/__tests__/terminal.spec.js#L264 but unclear if it's due to a issue on they side (can't find anything in their repo) or a misconfiguration on our side. So might need to investigate more before reporting it upstream.

I'm pretty sure it worked OK before, so it might also be due to browser update, as currently even old Pyodide releases have this behavior.

### PR DESCRIPTION
**Pull request by ryanking13**
### Description

Resolve #3337

Add `replace_nbsp` parameter to Console.push, and use it in console.html.
If the parameter is set to True, replace all nbsp letters to regular space.

### Checklists

- [ ] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry
- [x] Add / update tests

### CODE REVIEW

**Comment by hoodmane** [comment]
I think it would be better to make it a keyword only argument.

**Comment by ryanking13** [comment]
> I think it would be better to make it a keyword only argument.

Sounds good to me. Can we pass keyword only argument in JS side?

**Comment by hoodmane** [comment]
You have to use `push.callKwargs(s, {replace_nbsp: true});`. But are we sure this is better than `push(s.replaceAll("nbsp", " "))`?

**Comment by ryanking13** [comment]
> But are we sure this is better than push(s.replaceAll("nbsp", " "))?

I think your idea is better.

**Comment by ryanking13** [comment]
Closing in favor of #3558, thanks for the suggesion Hood!

**Pull request closed without merging**
