### PR TITLE
Emscripten 3.1.25

### PR DESCRIPTION
**Pull request by hoodmane**
Hard to keep up with these. We just got up to latest and then there's a new release. I am loving not having to migrate patches anymore!

### CODE REVIEW

**Comment by hoodmane** [comment]
C++ trouble. @ryanking13 I hope you'll fix it =)

**Comment by ryanking13** [comment]
I'll see if I can fix it :^)

**Comment by ryanking13** [comment]
```
./boost/container_hash/hash.hpp:132:33: error: no template named 'unary_function' in namespace 'std'; did you mean '__unary_function'?
        struct hash_base : std::unary_function<T, std::size_t> {};
                           ~~~~~^~~~~~~~~~~~~~
                                __unary_function
/root/repo/emsdk/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1/__functional/unary_function.h:46:1: note: '__unary_function' declared here
using __unary_function = __unary_function_keep_layout_base<_Arg, _Result>;
```

The Emscripten 3.1.25 [updated LLVM version to 15](https://github.com/emscripten-core/emscripten/pull/18113), and it seems like it is an upstream issue of LLVM15 and boost incompatibility.

- https://github.com/fnalacceleratormodeling/synergia2/issues/80
- https://github.com/boostorg/container_hash/issues/22

**Comment by ryanking13** [comment]
Oh, actually [boost already released 1.80.0 with a fix](https://www.boost.org/users/history/version_1_80_0.html). So we will just have to update boost to 1.80.0

**Comment by hoodmane** [comment]
Hmm it's still not working. Maybe try updating boost as a separate pr?

I also am slightly worried whether rust will work. I guess we should disable boost and see if anything else breaks.

**Comment by ryanking13** [comment]
Oh, right. The Boost team mentioned that it was "found too late to be fixed in the release", but they provided a patch file instead: https://www.boost.org/patches/1_80_0/0005-config-libcpp15.patch

**Comment by hoodmane** [comment]
> built boost-cpp in 202.90

Great work @ryanking13 =D

**Comment by hoodmane** [comment]
I think the crash in matplotlib is happening via Pillow via freetype. It's pretty hard to tell but my best guess is the error is happening here:
https://gitlab.freedesktop.org/freetype/freetype/-/blob/master/src/autofit/afloader.c#L128

The `call_indirect` instruction declares type `(param i32 i32 i32) -> void` but is defined with type `(param i32 i32 i32) -> i32`. The function being called in the source looks like it is defined to return void...

**Comment by hoodmane** [comment]
I think the key thing here is to build freetype with debug symbols. Not sure how to do that though.

**Comment by ryanking13** [comment]
It looks like the emscripten team [switched freetype repo](https://github.com/emscripten-core/emscripten/pull/18095/files) and they dropped a patch which modifies function signatures: https://github.com/emscripten-ports/FreeType/commit/40a760c963bc2b76575918ff91a515c8474db4e0. Maybe we can revert that change and see what happens?

**Comment by hoodmane** [comment]
```patch
- typedef void
+ typedef FT_Error
  (*AF_WritingSystem_ApplyHintsFunc)( AF_GlyphHints    hints,
                                      FT_Outline*      outline,
                                      AF_StyleMetrics  metrics );
```
That's the one!

**Comment by ryanking13** [comment]
@sbc100 I think we found that the patch in https://github.com/emscripten-ports/FreeType/commit/40a760c963bc2b76575918ff91a515c8474db4e0 was useful.

**Comment by sbc100** [comment]
Oh, my mistake i didn't realize we how downstream freetype patches, we should revert that change.

**Comment by hoodmane** [comment]
I really don't understand the current traceback.

**Comment by ryanking13** [comment]
> I really don't understand the current traceback. The hash value is correct and there seems to be only one `sha512hash` argument.

Well, it seems like the signature of `fetch_project` has been changed too (https://github.com/emscripten-core/emscripten/pull/18148)

**Review by ryanking13 — APPROVED** [review]
Now it seems it is working well. Thanks, @hoodmane!

**Pull request merged**
