### PR TITLE
DOC Rename repo links under the Pyodide org

### PR DESCRIPTION
**Pull request by rth**
Checking the situation with CI following the org migration in https://github.com/pyodide/pyodide/issues/1217

### CODE REVIEW

**Comment by rth** [comment]
OK, so unsurprisingly CircleCI now runs under a different account https://app.circleci.com/pipelines/github/pyodide/pyodide . For now we should be fine with the OSS offering I think, we need to see if this repo could be added back to the Mozilla plan.

Changed links to the new repo in this PR.

**Comment by hoodmane** [comment]
The tests do seem to be flakier since the migration, particularly `test_webworker.py` doesn't seem to work now.

**Comment by rth** [comment]
Yes, it's really puzzling,
 - all tests that use larger packages (pandas, scipy etc) now fail on both browsers

```
FAILED test_common.py::import[firefox-mne] - selenium.common.exceptions.Timeo...
FAILED test_common.py::import[firefox-scikit-image] - selenium.common.excepti...
FAILED test_common.py::import[firefox-scikit-learn] - selenium.common.excepti...
FAILED test_common.py::import[firefox-scipy] - selenium.common.exceptions.Tim...
FAILED test_common.py::import[firefox-statsmodels] - selenium.common.exceptio...
FAILED test_common.py::import[firefox-pandas] - selenium.common.exceptions.Ti...
FAILED test_common.py::import[firefox-yt] - selenium.common.exceptions.Timeou...
FAILED test_common.py::import[firefox-pywavelets] - selenium.common.exception...
FAILED numpy/test_numpy.py::runwebworker_numpy[firefox] - selenium.common.exc...
FAILED scikit-image/test_skimage.py::skimage[firefox] - selenium.common.excep...
```
 - on Chrome following tests failed,
```
FAILED test_jsproxy.py::unregister_jsmodule[chrome] - assert -4 == 0
FAILED test_jsproxy.py::mixins_feature_presence[chrome] - assert -2 == 0
ERROR test_asyncio.py::then_jsproxy[chrome] - selenium.common.exceptions.Time...
ERROR test_asyncio.py::eval_code_await_jsproxy[chrome] - selenium.common.exce...
ERROR test_asyncio.py::await_jsproxy[chrome] - selenium.common.exceptions.Tim...
ERROR test_asyncio.py::await_error[chrome] - selenium.common.exceptions.Timeo...
ERROR test_asyncio.py::ensure_future_memleak[chrome] - selenium.common.except...
ERROR test_asyncio.py::eval_code_await_error[chrome] - selenium.common.except...
ERROR test_asyncio.py::await_pyproxy_async_def[chrome] - selenium.common.exce...
ERROR test_asyncio.py::await_fetch[chrome] - selenium.common.exceptions.Timeo...
ERROR test_asyncio.py::eval_code_await_fetch[chrome] - selenium.common.except...
ERROR test_asyncio.py::await_pyproxy_eval_async[chrome] - selenium.common.exc...
ERROR test_package_loading.py::load_packages_multiple[chrome-pyparsing-packaging]
ERROR test_python.py::import_js[chrome] - selenium.common.exceptions.SessionN...
ERROR test_python.py::globals_get_multiple[chrome] - selenium.common.exceptio...
ERROR test_python.py::globals_get_same[chrome] - selenium.common.exceptions.S...
ERROR test_python.py::open_url[chrome] - selenium.common.exceptions.SessionNo...
ERROR test_python.py::load_package_after_convert_string[chrome] - selenium.co...
ERROR test_python.py::version_info[chrome] - selenium.common.exceptions.Sessi...
ERROR test_python.py::eval_nothing[chrome] - selenium.common.exceptions.Sessi...
ERROR test_python.py::unknown_attribute[chrome] - selenium.common.exceptions....
ERROR test_package_loading.py::load_twice_same_source[chrome] - selenium.comm...
```
most with timeouts.

At the same time as far as I can tell we are using exactly the same docker container runner. This reminds me a bit of the issues we had after emscreipten upstream migration where due to server load some tests timed out https://github.com/pyodide/pyodide/issues/1204 . Here the load average is 36 with 36 CPU cores which is fine (you can connect to CircleCI jobs with SSH). 


Merging these doc changes as they would necessary in any case, but need to investigate these CI failures further.

**Comment by hoodmane** [comment]
These two were caused by #1340:
```
FAILED test_jsproxy.py::unregister_jsmodule[chrome] - assert -4 == 0
FAILED test_jsproxy.py::mixins_feature_presence[chrome] - assert -2 == 0
```
What's happening is that I couldn't figure out how to make `test_nested_import` and `test_register_jsmodule_docs_example` reference count neutral so I marked them with `@pytest.mark.skip_refcount_check` but only after trying pretty hard to reclaim the references. For whatever reason 6 of the "leaked" reference counts from the `skip_refcount_check` tests are getting reclaimed during `unregister_jsmodule` and `mixins_feature_presence`.

**Comment by rth** [comment]
Still it's very strange that it's not reproducible in the same docker image between the previous and the current org.

BTW, @hoodmane Could you please accept the GH invite for this org? I re-sent it yesterday.

**Comment by rth** [comment]
And what's even stranger is that @dalcde has been building/testing pyodide with CircleCI on [his fork fine](https://github.com/pyodide/pyodide/pull/1223). So it should be fine on a regular CircleCI account. Then in https://github.com/pyodide/pyodide/pull/1223 we start seeing some CI failures, but I don't think those are related.

**Pull request merged**
