### PR TITLE
Update Emscripten to 3.1.60

### PR DESCRIPTION
**Pull request by hoodmane**
### Checklists

- [x] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry

### CODE REVIEW

**Review by ryanking13 — APPROVED** [review]
Thanks!

**Comment by hoodmane** [comment]
Was this okay to merge? I'd have wanted to see the package ci actually pass for an emscripten bump. But we can revert it if there's a problem.

**Comment by ryanking13** [comment]
Oh... I didn't check the CI status carefully 😅 Looks like the package build is failing in the main branch, so let's revert and check.

**Comment by hoodmane** [comment]
I guess this is what I get for not marking things as draft.

**Pull request merged**
