### PR TITLE
Update protobuf to 5.29.0

### PR DESCRIPTION
**Pull request by bartbroere**
Update the `protobuf` package to 5.29.0

- [x] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry

### CODE REVIEW

**Comment by ryanking13** [comment]
Hmm, looks like there is some indentation error in the protobuf package?

```
PyCompileError: Sorry: IndentationError: unindent does not match any outer 
indentation level (service.py, line 78)
```

**Comment by ryanking13** [comment]
This line: https://github.com/protocolbuffers/protobuf/blob/2d4414f384dc499af113b5991ce3eaa9df6dd931/python/google/protobuf/service.py#L78C3-L78C4

**Comment by bartbroere** [comment]
> Hmm, looks like there is some indentation error in the protobuf package?
> 
> ```
> PyCompileError: Sorry: IndentationError: unindent does not match any outer 
> indentation level (service.py, line 78)
> ```

Thanks! Since the entire `service.py` file seems to be deprecated I guess we can just wait it out until it's gone from `protobuf` releases. For now I introduced a new patch in the `meta.yaml`. Let's see if it builds.

**Review by ryanking13 — APPROVED** [review]
Thanks!

**Pull request merged**
