### PR TITLE
FIX TextDecoder is not a left inverse for TextEncoder

### PR DESCRIPTION
**Pull request by hoodmane**
Strings on which decode(encode(s)) !== s will fail these tests
due to no fault of Pyodide. Took Hypothesis a long time to find this
though.

Counter example: '\ufeff'
https://app.circleci.com/pipelines/github/hoodmane/pyodide/3238/workflows/ca2c0d13-db82-43b3-b8e4-d4aad7c1cd3b/jobs/37480

### CODE REVIEW

**Comment by hoodmane** [comment]
I added `ignoreBOM` in two places in the code too because I think it's the more expected behavior (it's good for decoding to be injective when possible).

**Review by ryanking13 — APPROVED** [review]

**Comment by ryanking13** [comment]
Thanks, @hoodmane!

**Comment by rth** [comment]
Shouldn't it be `ignoreBOM = false` though, if we want to decode exactly the same string (with BOM)?

**Comment by hoodmane** [comment]
Apparently not -- try it.

**Comment by rth** [comment]
Ahh, yes, indeed, 

> [if True]
> The parser will ignore that BOM mark, meaning it will treat it as a normal character sequence. 

that's rather confusing.

**Comment by hoodmane** [comment]
Yeah it's confusing.

**Pull request merged**
