### PR TITLE
Bump protobuf package to 5.27.3

### PR DESCRIPTION
**Pull request by bartbroere**
~Protobuf gets a major version bump, so let's start running CI against the release candidate(s) to see what might break early on.~

~Protobuf is moving to version 26, and the Python package to major version 5. This means that the Python package moves from `4.25.*` to `5.26.*`. Due to some build issues, we're going straight from `4.24.*` to `5.26.*` in Pyodide.~

~The new version is [expected (but not guaranteed) to appear somewhere this month](https://protobuf.dev/support/version-support/).~

Some time passed since I last worked on this, and now we can skip straight to 5.27.3

### CODE REVIEW

**Comment by ryanking13** [comment]
It looks like there is a signature mismatch again

**Comment by bartbroere** [comment]
I'll be mostly offline during April, so this is just a heads up that this PR will not see much progress for a few weeks. I didn't forget about it though, and plan to continue working on it in May.

**Comment by hoodmane** [comment]
We have a bunch of ancient stale PRs, it's no problem =)

**Comment by cclauss** [comment]
https://pypi.org/project/protobuf

**Comment by bartbroere** [comment]
https://app.circleci.com/pipelines/github/pyodide/pyodide/7791/workflows/665b34c7-1c05-4428-8447-71312b3eb88c/jobs/112161

I don't believe the changes in this PR are to blame for the failing CI check; it's just a CircleCI timeout.

**Comment by hoodmane** [comment]
I restarted the CI. Hopefully it will make it further this time =)

**Review by cclauss — APPROVED** [review]

**Comment by hoodmane** [comment]
Hmm looks like there's a regression.

**Review by cclauss — CHANGES_REQUESTED** [review]
Three failing tests...
ci/circleci: test-packages-chrome-no-numpy-dependents — Your tests failed on CircleCI [Details](https://circleci.com/gh/pyodide/pyodide/112277)
ci/circleci: test-packages-firefox-no-numpy-dependents — Your tests failed on CircleCI [Details](https://circleci.com/gh/pyodide/pyodide/112279)
ci/circleci: test-packages-node-no-numpy-dependents — Your tests failed on CircleCI [Details](https://circleci.com/gh/pyodide/pyodide/112276)

**Comment by hoodmane** [comment]
I think this should fix it:
https://github.com/protocolbuffers/protobuf/pull/17959

**Review by ryanking13 — APPROVED** [review]
Thanks @bartbroere!

**Pull request merged**
