### PR TITLE
Add missing backtick in the faq docs

### PR DESCRIPTION
**Pull request by jtpio**
Follow-up to https://github.com/pyodide/pyodide/pull/1525

### CODE REVIEW

**Comment by hoodmane** [comment]
Oops the thanks was supposed to go in the comment not in the commit message...

**Comment by rth** [comment]
Thanks ! I should have checked rendered docs. We should also remember to add `[skip ci]` to the documentation commit messages :) Particuarly if we are going to backport it to the stable branch.

**Comment by hoodmane** [comment]
oh.

**Comment by hoodmane** [comment]
I shouldn't be doing this in the middle of the night.

**Comment by hoodmane** [comment]
Also why am I listed as a coauthor of the commit?

**Comment by rth** [comment]
If you cherry-pick it, that's expected.

**Pull request merged**
