### PR TITLE
DOC replace Gitter links with discord

### PR DESCRIPTION
**Pull request by ryanking13**
cc: @agriyakhetarpal

### CODE REVIEW

**Review by agriyakhetarpal — APPROVED** [review]
Thank you, @ryanking13! Just to let you know, I was going to do this indeed, but was planning on the best time to do so, so it's great you did it yourself :) I saw that you posted the deprecation notice in the Gitter room. Could we pin the Discord link on the issues page in some way (maybe by pinning this PR and editing its description)?

I double-checked that the invite link added is permanent, so we're good on that part as well.

**Comment by agriyakhetarpal** [comment]
Also, I hope it is okay to tag @pyodide/community-members and @pyodide/emeritus-core-devs. If anyone is inactive, I'll chase them and email them to get the invite out.

**Comment by ryanking13** [comment]
> I was going to do this indeed, but was planning on the best time to do so, so it's great you did it yourself :)

Ohhh, sorry if I was overtaking your plan. Anyway, I think it is a good timing to deprecate Gitter.

> Could we pin the Discord link on the issues page in some way (maybe by pinning this PR and editing its description)?

Hmm, it seems like I cannot pin the pull request. I'll make a new issue and pin it instead.

**Comment by hoodmane** [comment]
Thanks!

**Pull request merged**
