### PR TITLE
Update scikit-learn to 1.5

### PR DESCRIPTION
**Pull request by lesteve**
### Description

Update scikit-learn to 1.5

### Checklists

- [x] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry

### CODE REVIEW

**Comment by lesteve** [comment]
The CI failures do not seem related, probably? I triggered a new CI build.

**Comment by ryanking13** [comment]
Yes, it's a network connection issue.

**Comment by lesteve** [comment]
Hmmm the error seems genunine, needs a closer look:
```
___________________________ test_train_predict[node] ___________________________
conftest.py:230: in pytest_runtest_call
    yield from extra_checks_test_wrapper(
conftest.py:276: in extra_checks_test_wrapper
    assert (delta_proxies, delta_keys) == (0, 0) or delta_keys < 0
E   assert ((0, 1) == (0, 0)
E     At index 1 diff: 1 != 0
E     Full diff:
E     - (0, 0)
E     ?     ^
E     + (0, 1)
E     ?     ^ or 1 < 0)
```

**Comment by ryanking13** [comment]
It means that there is some kind of memory leak. To be honest, I often just turn that check off when it happens since it is often hard to debug, but probably @hoodmane would have some idea how to debug.

https://github.com/pyodide/pyodide/blob/880c9a8487f6c87459f418f41b3d0ced8719c684/docs/development/testing.md?plain=1#L57-L61

**Comment by hoodmane** [comment]
+1 for turn off the leak check.

**Review by hoodmane — APPROVED** [review]
Thanks @lesteve! Please resolve changelog conflict then I'll merge.

**Pull request merged**
