### PR TITLE
upgrade to SQLIte-3.38.5

### PR DESCRIPTION
**Pull request by stonebig**
### Checklists

- [x] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry
- [x] Add / update tests
- [x] Add new / update outdated documentation

### CODE REVIEW

**Comment by stonebig** [comment]
don't know if we have to remove changelog entry

-  {{ Enhancement }} Update sqlite version to latest stable release
  {pr}`2477`

**Review by rth — APPROVED** [review]
Thanks! You can add 
```
and {pr}`2518`
```
at the end of the previous SQLite changelog entry instead of adding a new one.

**Comment by stonebig** [comment]
done

**Comment by ryanking13** [comment]
Thanks, @stonebig!

**Pull request merged**
