### PR TITLE
Scipy: Fix recursive functions

### LINKED ISSUE #4818: scipy.integrate.dblquad gives very wrong result even for the simplest integrations
## 🐛 Bug

Using the pyodide kernel, the `scipy.integrate.dblquad` gives very wrong results even for the simplest integrations.
The integrations are correct outside of pyodide.

### To Reproduce
Enter the following code into [jupyterlite](https://jupyterlite.github.io/demo/lab/index.html)
```python
import scipy
print(scipy.__version__)
print(pyodide.__version__)

unit_square_area = scipy.integrate.dblquad(lambda y,x: 1, 0, 1, lambda x: 0, lambda x: 1)
assert abs(unit_square_area[0]-1) < unit_square_area[1], 'Unit square area calculated using scipy.integrate.dblquad of {} (+- {}) is too far from 1.0'.format(unit_square_area[0], unit_square_area[0])
```
### Expected behavior

accurate result. pass above test.

### Tested Environments

- `pyodide.__version__`: '0.25.0' with `scipy.__version__`: '1.11.2' and jupyterlite: '0.3.0' 
- `pyodide.__version__`: '0.23.0' with `scipy.__version__`: '1.9.3' and jupyterlite: '0.1.0' 
- Independent of browser. Happens in Edge (Version 124.0.2478.105 (Official build) (64-bit) and Firefox (115.11.0esr (64-bit)) and Chrome.
- Any other relevant information:

### Additional context

Related issues (unclear if related, sound similar):
- https://github.com/scipy/scipy/issues/17413 
- https://github.com/scipy/scipy/issues/6882
- https://github.com/scipy/scipy/pull/15997
- https://github.com/lfortran/lfortran/issues/1377

### PR DESCRIPTION
**Pull request by hoodmane**
Non recursive functions declare all their locals as static, ones marked "recursive" need them to be proper local variables. Not sure if non recursive funcs need static locals, let's try making all locals non-static first. If this doesn't work, we can locate functions marked recursive and only modify them.

Fixes #4818.

@lesteve can you check the status of the scipy tests here?

- [x] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry
- [x] Add a test

### CODE REVIEW

**Comment by lesteve** [comment]
Looks like I get Pyodide fatal errors on this PR, for example:

```
node scipy-pytest.js --pyargs scipy.integrate.tests.test_quadrature -v
```

End of the output:
```
::TestQMCQuad::test_basic[8-256] Exit: Program terminated with exit(0)
    at ensureCaughtObjectIsError (/home/lesteve/dev/scipy-tests-pyodide/node_modules/pyodide/pyodide.asm.js:994:693)
    at API.fatal_error (/home/lesteve/dev/scipy-tests-pyodide/node_modules/pyodide/pyodide.asm.js:998:925)
    at API.maybe_fatal_error (/home/lesteve/dev/scipy-tests-pyodide/node_modules/pyodide/pyodide.asm.js:998:1751)
    at callPyObjectKwargs (/home/lesteve/dev/scipy-tests-pyodide/node_modules/pyodide/pyodide.asm.js:1000:884)
    at Module.callPyObject (/home/lesteve/dev/scipy-tests-pyodide/node_modules/pyodide/pyodide.asm.js:1000:2115)
    at Function.apply (/home/lesteve/dev/scipy-tests-pyodide/node_modules/pyodide/pyodide.asm.js:1000:17630)
    at Object.apply (/home/lesteve/dev/scipy-tests-pyodide/node_modules/pyodide/pyodide.asm.js:1000:14926)
    at main (/home/lesteve/dev/scipy-tests-pyodide/scipy-pytest.js:72:24) {
  status: 0,
  pyodide_fatal_error: true
}
```

**Comment by hoodmane** [comment]
The problem is that if you say `static int x;` it gets automatically zero-initialized. When I remove the `static` it becomes an uninitialized variable hence accesses are undefined behavior. Have to change it to `int x = {0}`.

**Comment by lesteve** [comment]
Still the same issue as https://github.com/pyodide/pyodide/pull/4822#issuecomment-2141284045 in the last iteration of the PR. Quicky looking it seems like `scipy.special.stdtrit` is the one creating the Pyodide fatal error.

Here is a snippet that reproduces the issue in this PR (simplified from `scipy/integrate/tests/test_quadrature.py`)

```py
import numpy as np
from numpy import cos, sin, pi
from numpy.testing import (assert_equal, assert_almost_equal, assert_allclose,
                           assert_, suppress_warnings)
from scipy.integrate import qmc_quad
from scipy import stats, special

def func(x):
    return stats.multivariate_normal.pdf(x.T, mean, cov)

n_points=2**8
n_estimates=8
signs=np.ones(2)
ndim = 2
mean = np.zeros(ndim)
cov = np.eye(ndim)
rng = np.random.default_rng(2879434385674690281)
qrng = stats.qmc.Sobol(ndim, seed=rng)
a = np.zeros(ndim)
b = np.ones(ndim) * signs
print('before qmc_quad', flush=True)
res = qmc_quad(func, a, b, n_points=n_points,
                n_estimates=n_estimates, qrng=qrng)
print('after qmc_quad', flush=True)

ref = stats.multivariate_normal.cdf(b, mean, cov, lower_limit=a)
print('before stdtdrit', flush=True)
atol = special.stdtrit(n_estimates-1, 0.995) * res.standard_error  # 99% CI
print('after stdtdrit', flush=True)
assert_allclose(res.integral, ref, atol=atol)
assert np.prod(signs)*res.integral > 0

rng = np.random.default_rng(2879434385674690281)
qrng = stats.qmc.Sobol(ndim, seed=rng)
print('before qmc_quad', flush=True)
logres = qmc_quad(lambda *args: np.log(func(*args)), a, b,
                    n_points=n_points, n_estimates=n_estimates,
                    log=True, qrng=qrng)
print('after qmc_quad', flush=True)
assert_allclose(np.exp(logres.integral), res.integral, rtol=1e-14)
assert np.imag(logres.integral) == (np.pi if np.prod(signs) < 0 else 0)
assert_allclose(np.exp(logres.standard_error),
                res.standard_error, rtol=1e-14, atol=1e-16)
```


This happens with test_quadrature.py::TestQMCQuad::test_basic[8-256] and I get this kind of info `STOP  SMALL, X, BIG not monotone in INVR statement executed`. Here is the stack-trace I get when running with node:

```
../../mnt/test_quadrature.py::TestQMCQuad::test_basic[8-256] before qmc_quad
after qmc_quad
before stdtdrit
STOP  SMALL, X, BIG not monotone in INVR statement executed
Exit: Program terminated with exit(0)
    at ensureCaughtObjectIsError (/home/lesteve/dev/scipy-tests-pyodide/node_modules/pyodide/pyodide.asm.js:994:693)
    at API.fatal_error (/home/lesteve/dev/scipy-tests-pyodide/node_modules/pyodide/pyodide.asm.js:998:925)
    at API.maybe_fatal_error (/home/lesteve/dev/scipy-tests-pyodide/node_modules/pyodide/pyodide.asm.js:998:1751)
    at callPyObjectKwargs (/home/lesteve/dev/scipy-tests-pyodide/node_modules/pyodide/pyodide.asm.js:1000:884)
    at Module.callPyObject (/home/lesteve/dev/scipy-tests-pyodide/node_modules/pyodide/pyodide.asm.js:1000:2115)
    at Function.apply (/home/lesteve/dev/scipy-tests-pyodide/node_modules/pyodide/pyodide.asm.js:1000:17630)
    at Object.apply (/home/lesteve/dev/scipy-tests-pyodide/node_modules/pyodide/pyodide.asm.js:1000:14926)
    at main (/home/lesteve/dev/scipy-tests-pyodide/scipy-pytest.js:72:24) {
  status: 0,
  pyodide_fatal_error: true
}
```

**Comment by hoodmane** [comment]
Thanks for the reproduction @lesteve.

**Comment by hoodmane** [comment]
Okay I think I got it.

**Comment by lesteve** [comment]
The dblquad test does not seem to pass with your latest fixes :sweat_smile: ...

For example, [node build log](https://app.circleci.com/pipelines/github/hoodmane/pyodide/6349/workflows/29892ca1-4ec3-49bd-b0ed-46572e8c0bc5/jobs/95811):
```
FAILED scipy/test_scipy.py::dblquad[node] - AssertionError: Unit square area calculated using scipy.integrate.dblquad of -1.7763568394002363e-15 (+- -1.7763568394002363e-15) is too far from 1.0
assert 1.0000000000000018 < 1.1102230246251565e-14
```

There is this warning as well just before that is likely relevant:
```
/lib/python3.12/site-packages/scipy/integrate/_quadpack_py.py:1272: IntegrationWarning: The integral is probably divergent, or slowly convergent.
  quad_r = quad(f, low, high, args=args, full_output=self.full_output,
```

**Comment by hoodmane** [comment]
Hmm still doesn't work. It's just a matter of futzing with it at this point I think, some of the commits make the dblquad test pass so I definitely have the right approach.

**Review by ryanking13 — COMMENTED** [review]
Thanks for handling fortran issues @hoodmane! Let me port the f2c fixes to `pyodide/pyodide-build`.

**Comment by lesteve** [comment]
FYI looks like this fixed quite a number of issues see https://github.com/lesteve/scipy-tests-pyodide/pull/37. In particular:
- there does not seem to be "memory corruption"-like issue anymore, i.e. non-deterministic errors that can be anything between Pyodide fatal errors, Python error that does not make any sense or wrong results
- a lot less tests need to be xfailed

**Pull request merged**
