### PR TITLE
DOCS Add faq on redirecting staandard streams

### PR DESCRIPTION
**Pull request by hoodmane**
I meant for this to go into 0.17.0 but it got lost.

### CODE REVIEW

**Comment by rth** [comment]
Thanks ! You can manually cherry-pick this commit to `stable` upstream branch if you want it to be included in the stable documentation branch.

**Comment by hoodmane** [comment]
Okay I will do that.

**Comment by hoodmane** [comment]
I guess then if we make an 0.17.0 examples folder we could cherry-pick that to stable too.

**Comment by hoodmane** [comment]
Btw I think the reason I couldn't commit to other peoples' PRs may have been because my upstream remote was using https rather than ssh.

**Pull request merged**
