### PR TITLE
Fix `eval_code`

### LINKED ISSUE #3578: Global namespace not accessible within a function
## 🐛 Bug

A globally declared variable cannot be read in a function:

```
globVar = "Hello"
def test():
    print(globVar)

test()
```
gives error:
```
NameError: name 'globVar' is not defined
```
Interestingly, when used with the `global` keyword, it works:

```
globVar = "Hello"
def test():
    global globVar
    print(globVar)

test()
```
prints
```
Hello
```

This issue only happens when the python code is passed to the function `pyodide.pyodide_py.code.eval_code`. The bug is not present when the code is executed with `pyodide.runPython`, such as in the [console.html](https://pyodide.org/en/stable/console.html).

### To Reproduce

Run a slightly modified demo from the [Getting Started page](https://pyodide.org/en/stable/usage/quickstart.html) of pyodide:

```
<!doctype html>
<html>
  <head>
      <script src="https://cdn.jsdelivr.net/pyodide/v0.22.1/full/pyodide.js"></script>
  </head>
  <body>
    Pyodide test page <br>
    Open your browser console to see Pyodide output
    <script type="text/javascript">
      async function main(){
        let pyodide = await loadPyodide();
        console.log(pyodide.pyodide_py.code.eval_code(`
            globVar = "Hello"
            def test():
                print(globVar)

            test()
        `));
      }
      main();
    </script>
  </body>
</html>
```

### Expected behavior

When the page above is opened in a web browser, it should print "Hello" to console. Instead, it throws a NameError: name 'globVar' is not defined:

```
pyodide.asm.js:10 Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python3.10/_pyodide/_base.py", line 460, in eval_code
    .run(globals, locals)
  File "/lib/python3.10/_pyodide/_base.py", line 306, in run
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 6, in <module>
  File "<exec>", line 4, in test
NameError: name 'globVar' is not defined

    at new_error (pyodide.asm.js:10:180810)
    at pyodide.asm.wasm:0xe78a8
    at pyodide.asm.wasm:0xe79ad
    at Module._pythonexc2js (pyodide.asm.js:10:929422)
    at Module.callPyObjectKwargs (pyodide.asm.js:10:123563)
    at Module.callPyObject (pyodide.asm.js:10:123772)
    at PyProxyClass.apply (pyodide.asm.js:10:134742)
    at Object.apply (pyodide.asm.js:10:133736)
    at main (bug.html:12:45)
new_error	@	pyodide.asm.js:10
$wrap_exception	@	pyodide.asm.wasm:0xe78a8
$pythonexc2js	@	pyodide.asm.wasm:0xe79ad
Module._pythonexc2js	@	pyodide.asm.js:10
Module.callPyObjectKwargs	@	pyodide.asm.js:10
Module.callPyObject	@	pyodide.asm.js:10
apply	@	pyodide.asm.js:10
apply	@	pyodide.asm.js:10
main	@	bug.html:12
await in main (async)		
(anonymous)	@	bug.html:20
```

### Environment

- Pyodide Version 0.22.1:
- Browser version : Version 110.0.5481.77 (Official Build) (64-bit)

Build from commit `5ef5622414f0fe8ab8c54694e04ab1b13939b7d4` (tagged `0.22.1`), but can be reproduced as well with the CDN build on https://cdn.jsdelivr.net/pyodide/v0.22.1/full/pyodide.js

### Additional context

The issue only happens when the code is invoked using the [eval_code](https://github.com/pyodide/pyodide/blob/main/src/py/_pyodide/_base.py#L362) function. 

The documentation for the function assumes the `eval_code` can be called with `globals` argument set to `None`, and then an empty dictionary will be created. We relied on this feature since pyodide v0.17. In pyodide v0.18, the issue with global variables appeared and we tested and encountered the issue again in version v0.22.1. Is this behavior of hiding global variables a bug?
```
    globals :
        The global scope in which to execute code. This is used as the
        ``globals`` parameter for :py:func:`exec`. If ``globals`` is absent, a new
        empty dictionary is used.
```

### PR DESCRIPTION
**Pull request by hoodmane**
This fixes `eval_code` / `eval_code_async` / `CodeRunner.run` / `CodeRunner.runAsync` so that the defaults for globals and locals work as documented. Resolves #3578.

- [x] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry
- [x] Add / update tests

### CODE REVIEW

**Review by ryanking13 — APPROVED** [review]

**Comment by ryanking13** [comment]
@hoodmane Is there some reason closing this?

**Comment by hoodmane** [comment]
Accident, I was cleaning up old branches in hoodmane/Pyodide. I wonder if I removed any other open ones ...

**Comment by ryanking13** [comment]
#3581 and #3381 are also removed )

**Comment by hoodmane** [comment]
Thanks @ryanking13!

**Comment by hoodmane** [comment]
Well #3381 doesn't really work. Boo scipy =(

**Pull request merged**
