### PR TITLE
Release 0.17.0

### PR DESCRIPTION
**Pull request by rth**
Final changes for the 0.17.0 release. We really should automate version replacements in the docs.

Depends on https://github.com/pyodide/pyodide/pull/1514 fixing the Firefox CI.

Closes https://github.com/pyodide/pyodide/issues/1331

### CODE REVIEW

**Comment by hoodmane** [comment]
I'm going to open a PR about #1516 and then another PR putting a link to that PR in the `InteractiveConsole` docs so people will know that any code that touches it will break in v0.17.1.

**Comment by hoodmane** [comment]
Guess I'll grep to see if I can catch any suspicious looking version data anywhere.

**Comment by rth** [comment]
Yes, I think it should be fine, but if you could double check it would be good.

**Comment by hoodmane** [comment]
One minute.

**Comment by daoxian** [comment]
Great work! It's a big step forward.

**Pull request merged**
