### PR TITLE
Bumping numpy 1.25.2 > 1.26.1

### LINKED ISSUE #4213: Numpy-1.26.0
I've encountered a situation where the current `numpy-1.25.2` which is available in Pyodide doesn't allow the dependencies of other packages to be resolved since they require `numpy>=1.26.0` and `numpy<2.0.0`. I'd be very grateful if a version of `numpy-1.26.0` could be made and provisioned for Pyodide, I'll have a go at working through the [new packages](https://pyodide.org/en/stable/development/new-packages.html#new-packages) instructions myself.

## 🐍 Package Request

- Package Name and Version : numpy-1.26.0
- Package URL : https://github.com/numpy/numpy
- Package Dependencies that needs to be resolved first:

### PR DESCRIPTION
**Pull request by slackline**
Closes #4213 

### Description

I've a package I wish to setup a JupyterLite Notebook for people to run, one of the dependencies is `numpy-1.26.0` but currently only `numpy-1.25.2` is available for Pyodide (see #4213).

I've bumped the version in the relevant `meta.yaml` and tried building locally but failed, figured a PR to bump the version might be useful.

### Checklists

- [x] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry

### CODE REVIEW

**Comment by ryanking13** [comment]
It looks like numpy changed their default build backend to `meson`. I'm working on adding meson support in pyodide-build (#4204), so I'll take a look at this soon.

**Comment by ryanking13** [comment]
Resolved by #4240. You will be able to use numpy 1.26.1 from the dev URL (https://cdn.jsdelivr.net/pyodide/dev/full/) a few hours later from now.

**Comment by slackline** [comment]
@ryanking13 Could you point me to any documentation on how to configure which CDN / stream is used by pyodide please?  

I tried including `await micropip.install("https://cdn.jsdelivr.net/pyodide/dev/full/numpy-1.26.1.whl")` but I haven't guessed at the wheel name correctly as I get....

```
InvalidWheelFilename: Invalid wheel filename (wrong number of parts): numpy-1.26.1
```

I wonder if there is a way of setting the location `micropip` downloads from?

**Comment by ryanking13** [comment]
> I wonder if there is a way of setting the location micropip downloads from?

@slackline You need to change the indexURL when loading Pyodide.

```javascript
pyodide = await loadPyodide({ indexURL: "https://cdn.jsdelivr.net/pyodide/dev/full/" })
await pyodide.loadPackage("numpy")
```

If this is not suitable, you can load from the CDN directly,

```python
await micropip.install("https://cdn.jsdelivr.net/pyodide/dev/full/numpy-1.26.1-cp311-cp311-emscripten_3_1_45_wasm32.whl")
```

but this might not work if we update numpy or emscripten version. So it is not recommended.

**Comment by slackline** [comment]
Thank you @ryanking13 :+1: 

I'm trying to develop some JupyterLite notebooks, the first didn't work and reading [here](https://pyodide.org/en/latest/usage/quickstart.html) suggests that is maybe JavaScript.

Anyway, the second works for now, and I'm still in the process of developing things, but how did you determine the full package name for the second? I can't browse `https://cdn.jsdelivr.net/pyodide/dev/full/` as its forbidden and 
I tried looking through the builds but could find in the [build log](https://github.com/pyodide/pyodide/actions/runs/6602255047/job/17934099496?pr=4240) where the fully qualified package name is stored.

**Comment by slackline** [comment]
Ah, I think after reading the [API](https://micropip.pyodide.org/en/stable/project/api.html#micropip.set_index_urls) docs I can use...

```
micropip.set_index_urls("https://cdn.jsdelivr.net/pyodide/dev/full/")
```

Will give that a whirl, would still be useful to know how to find what the built package names are though.

**Comment by ryanking13** [comment]
> but how did you determine the full package name for the second? I can't browse https://cdn.jsdelivr.net/pyodide/dev/full/ as its forbidden and
I tried looking through the builds but could find in the [build log](https://github.com/pyodide/pyodide/actions/runs/6602255047/job/17934099496?pr=4240)

For now, you can access `https://cdn.jsdelivr.net/pyodide/dev/full/pyodide-lock.json` and see the name in it. pyodide-lock.json contains all packages included in the pyodide distribution.

> micropip.set_index_urls("https://cdn.jsdelivr.net/pyodide/dev/full/")

This will not work correctly since Pyodide CDN URL does not fully implement Simple API. But it may work later.

**Comment by slackline** [comment]
Thanks for the pointers and help @ryanking13

**Pull request closed without merging**
