### PR TITLE
Correct `PyodideAPI.FS` type declaration

### PR DESCRIPTION
**Pull request by CNSeniorious000**
### Description

typescript declaration for `pyodide.FS` is missing

### Checklists

- [ ] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry
- [ ] Add / update tests
- [ ] Add new / update outdated documentation

### CODE REVIEW

**Comment by CNSeniorious000** [comment]
I also wonder if this type declaration is hand-written and maybe it is out of date:

https://github.com/pyodide/pyodide/blob/22b667019a2dce02a1f458f43af11c15270c59f6/src/js/types.ts#L213-L262

Useful methods like `FS.unmount` is not there.

**Comment by hoodmane** [comment]
Yeah we only include methods that are used somewhere in our code.

**Comment by CNSeniorious000** [comment]
Why not just use emscripten's type declaration itself from [@types/emscripten](https://www.npmjs.com/package/@types/emscripten)?

**Comment by hoodmane** [comment]
Yeah we could use `@types/emscripten`.

**Review by hoodmane — APPROVED** [review]

**Comment by ryanking13** [comment]
`@types/emscripten` was based on Emscripten 1.39 (though it is occasionally updated), and we need to check if those types still work for the latest Emscripten.

**Comment by hoodmane** [comment]
I wonder if we're getting confused and the version number is just a coincidence? There's been commits in the last few months:
https://github.com/DefinitelyTyped/DefinitelyTyped/commits/master/types/emscripten/index.d.ts

But it isn't versioned with Emscripten so there are definitely going to be some incorrect definitions.

**Comment by ryanking13** [comment]
Yep, maintaining `@types/emscripten` has been discussed for a long time. If I remember correctly, even at the Jupyterlite workshop in 2022, there was a discussion about maintaining an Emscripten types so that libraries like Pyodide, Jupyterlite, and PyScript could all utilize it. However, it is not that interesting task that most people want to do, so it got lost in the discussion.

So, @CNSeniorious000, if you are interested in upstreaming and maintaining Emscripten types, I highly appreciate it.

**Pull request merged**
