### PR TITLE
Update bcrypt to 4.1.2

### PR DESCRIPTION
**Pull request by hoodmane**
- [ ] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry

### CODE REVIEW

**Comment by hoodmane** [comment]
@alex any ideas why this upgrade might be causing test failures? I might have to git bisect it.

**Comment by alex** [comment]
This looks vaguely like running a new bcrypt against an old test file.

**Comment by hoodmane** [comment]
Oh fantastic! Should have checked that. I assumed that the output of functions would be stable between minor versions even though I don't know anything about bcrypts stability guarantees or versioning scheme. I was worried it would be some strange miscompilation.

**Comment by alex** [comment]
The old tests rely on the ability to monkey patch things, and thus are
sensitive to implementation details

**Pull request merged**
