### PR TITLE
SciPy v1.13.1

### PR DESCRIPTION
**Pull request by agriyakhetarpal**
### Description

This PR updates SciPy to version `1.13.1`. Tagging recipe maintainers: @lesteve, @steppi; and @rgommers, for visibility. SciPy was previously updated in #4719 to version `1.13.0`.

### Checklists

- [x] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry

### CODE REVIEW

**Comment by agriyakhetarpal** [comment]
[SciPy builds successfully](https://app.circleci.com/pipelines/github/pyodide/pyodide/7718/workflows/f98072b1-fe4d-4fef-b533-0b22eaaa855d/jobs/110900?invite=true#step-104-14391_80) and [all tests are passing](https://github.com/pyodide/pyodide/actions/runs/10407867935/job/28825282377?pr=5011) for its test suite. I'll look at the `test-packages-chrome` and `test-packages-node` jobs when they finish since they are running some additional tests (I think), and if there is nothing concerning, I shall merge this PR.

**Comment by agriyakhetarpal** [comment]
Tests are passing for [Chrome](https://app.circleci.com/pipelines/github/pyodide/pyodide/7718/workflows/f98072b1-fe4d-4fef-b533-0b22eaaa855d/jobs/110929?invite=true#step-102-126133_79) and [Node](https://app.circleci.com/pipelines/github/pyodide/pyodide/7718/workflows/f98072b1-fe4d-4fef-b533-0b22eaaa855d/jobs/110925?invite=true#step-102-125724_79) – I shall update the CHANGELOG and merge

**Comment by agriyakhetarpal** [comment]
Passing for [Firefox](https://app.circleci.com/pipelines/github/pyodide/pyodide/7718/workflows/f98072b1-fe4d-4fef-b533-0b22eaaa855d/jobs/110928?invite=true#step-102-126297_79) as well. [PyArrow's test failed](https://app.circleci.com/pipelines/github/pyodide/pyodide/7718/workflows/f98072b1-fe4d-4fef-b533-0b22eaaa855d/jobs/110928?invite=true#step-102-148079_94) for Firefox (passed elsewhere), albeit due to a timeout – if it fails more often, we can increase the timeout.

**Comment by hoodmane** [comment]
@agriyakhetarpal I'm getting a scipy build failure in CI:
```
'scipy/stats/_stats_pythran.cpython-312-wasm32-emscripten.so.p/_stats_pythran.cp
p'                                                                              
FAILED:                                                                         
scipy/stats/_stats_pythran.cpython-312-wasm32-emscripten.so.p/_stats_pythran.cpp
/tmp/build-env-nnsn2be9/bin/pythran -E ../scipy/stats/_stats_pythran.py -o      
scipy/stats/_stats_pythran.cpython-312-wasm32-emscripten.so.p/_stats_pythran.cpp
Traceback (most recent call last):                                              
  File "/tmp/build-env-nnsn2be9/bin/pythran", line 8, in <module>               
    sys.exit(run())                                                             
             ^^^^^                                                              
  File "/tmp/build-env-nnsn2be9/lib/python3.12/site-packages/pythran/run.py",   
line 181, in run                                                                
    pythran.compile_pythranfile(args.input_file,                                
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                 
  File                                                                          
"/tmp/build-env-nnsn2be9/lib/python3.12/site-packages/pythran/__init__.py", line
127, in __getattr__                                                             
    import pythran.toolchain                                                    
  File                                                                          
"/tmp/build-env-nnsn2be9/lib/python3.12/site-packages/pythran/toolchain.py",    
line 11, in <module>                                                            
    from pythran.dist import PythranExtension, PythranBuildExt                  
  File "/tmp/build-env-nnsn2be9/lib/python3.12/site-packages/pythran/dist.py",  
line 139, in <module>                                                           
    class PythranBuildExt(PythranBuildExtMixIn, LegacyBuildExt,                 
metaclass=PythranBuildExtMeta):                                                 
TypeError: metaclass conflict: the metaclass of a derived class must be a       
(non-strict) subclass of the metaclasses of all its bases     
```

**Comment by hoodmane** [comment]
I wonder if pythran released an update in the last five days?

**Comment by hoodmane** [comment]
Nope looks like last update to Pythran was 2024-05-14.

**Comment by agriyakhetarpal** [comment]
That does look new. I'm sure SciPy was built without issues and passed successfully before I merged. The latest Pythran on PyPI is https://pypi.org/project/pythran/0.16.1/

**Comment by agriyakhetarpal** [comment]
Ah, @ryanking13 opened #5018 for this, just noticed 😄

**Pull request merged**
