### PR TITLE
PKG Add shapely and geos

### PR DESCRIPTION
**Pull request by ryanking13**
### Description

This is on top of #2721 and #1892.

Close #1892 (I think I am pretty bad at pushing to someone elses PR...)

### Checklists

- [x] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry
- [x] Add / update tests

### CODE REVIEW

**Review by hoodmane — APPROVED** [review]

**Comment by oeway** [comment]
Great! Thanks @ryanking13 !

**Comment by majinge7846** [comment]
@ryanking13 Hi, I want to build shapely 2.0.1 by myself, (our project need 2.0.1 version). And I met error. Can you help me.
‘’‘
_Could not find geos-config executable. Either append the path to geos-config to PATH or manually provide the include_dirs, library_dirs, libraries and other link args for compiling against a GEOS version >=3.5._ 
’‘’
I do not know how to set GEOS_CONFIG of env, because pyodide build in a isolate env.

**Comment by ryanking13** [comment]
@majinge7846

> I do not know how to set GEOS_CONFIG of env, because pyodide build in a isolated env.

Are you sure? I am pretty sure that we pass host environment variables into the build env.

**Comment by majinge7846** [comment]
> @majinge7846
> 
> > I do not know how to set GEOS_CONFIG of env, because pyodide build in a isolated env.
> 
> Are you sure? I am pretty sure that we pass host environment variables into the build env.

Thank you very much, it's my mistake. I tried agian. but get another compile error

_INFO: cc build/temp.emscripten_3_1_27_wasm32-cpython-310/src/c_api.o build/temp.emscripten_3_1_27_wasm32-cpython-310/src/coords.o build/temp.emscripten_3_1_27_wasm32-cpython-310/src/geos.o build/temp.emscripten_3_1_27_wasm32-cpython-310/src/lib.o build/temp.emscripten_3_1_27_wasm32-cpython-310/src/pygeom.o build/temp.emscripten_3_1_27_wasm32-cpython-310/src/strtree.o build/temp.emscripten_3_1_27_wasm32-cpython-310/src/ufuncs.o build/temp.emscripten_3_1_27_wasm32-cpython-310/src/vector.o -L/path/to/cached/prefix/lib -lgeos_c -o build/lib.emscripten_3_1_27_wasm32-cpython-310/shapely/lib.cpython-310-wasm32-emscripten.so
wasm-ld: error: unknown file type: /path/to/cached/prefix/lib/libgeos_c.so_

**Comment by hoodmane** [comment]
Well that's because you gave it a native libgeos you need to build an emscripten libgeos.

**Comment by majinge7846** [comment]
@ryanking13 How did you build shapely 1.8.2 ?  Did you build libgeos to wasm before build shapely? I found that it is hard for me to build libgeos to wasm.

**Comment by majinge7846** [comment]
I built geos and shapley 1.8.2 succussfully. but after my changes yaml config to 2.0.1 , I meet _ModuleNotFoundError: No module named 'numpy'_ error when build

**meta.yaml**
`
package:
  name: shapely
  version: **2.0.1**
  top-level:
    - shapely
source:
  url: **https://files.pythonhosted.org/packages/10/a7/de139da3ce303101c357a9ba801328cba85cf6ace157da31a4007bca85e4/shapely-2.0.1.tar.gz
  sha256: 66a6b1a3e72ece97fc85536a281476f9b7794de2e646ca8a4517e2e3c1446893**
build:
  vendor-sharedlib: true
  script: |
    export GEOS_CONFIG=${WASM_LIBRARY_DIR}/bin/geos-config
requirements:
  run:
    - numpy
  host:
    - geos
test:
  imports:
    - shapely
    - shapely.geos
    - shapely.geometry
    - shapely.ops
    - shapely.prepared
    - shapely.validation
    - shapely.strtree
about:
  home: https://github.com/shapely/shapely
  PyPI: https://pypi.org/project/shapely
  summary: Geometric objects, predicates, and operations
  license: BSD

`
**the error I met**


pyodide build-recipes shapely --install
The following packages are already built: geos, liblzma, micropip, openssl, packaging, and pydecimal
Building the following packages: distutils, hashlib, lzma, numpy, pydoc_data, shapely, sqlite3, ssl,
and test
[1/9] (thread 1) building numpy ⠼
[2/9] (thread 2) building lzma ⠼
[3/9] (thread 3) building test ⠼
[4/9] (thread 4) building distutils ⠼
[5/9] (thread 5) building hashlib ⠼
[6/9] (thread 6) building ssl ⠼
[7/9] (thread 7) building sqlite3 ⠼
[8/9] (thread 8) building pydoc_data ⠼
[9/9] (thread 9) building shapely ⠴
Building packages... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/9   0% Time elapsed: 0:00:11
Error building shapely. Printing build logs.
Running source pyodide_env in /home/majinge/pyodide-main/packages/shapely
Running build script in /home/majinge/pyodide-main/packages/shapely/build/shapely-2.0.1
<string>:8: DeprecationWarning: pkg_resources is deprecated as an API. See
https://setuptools.pypa.io/en/latest/pkg_resources.html
Compiling shapely/_geometry_helpers.pyx because it changed.
Compiling shapely/_geos.pyx because it changed.
[1/2] Cythonizing shapely/_geometry_helpers.pyx
[2/2] Cythonizing shapely/_geos.pyx
/tmp/build-env-y3v_66dm/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py:66:
_BetaConfiguration: Support for `` in `pyproject.toml` is still *beta*.
  config = read_configuration(filepath, True, ignore_option_errors, dist)
running egg_info
writing shapely.egg-info/PKG-INFO
writing dependency_links to shapely.egg-info/dependency_links.txt
writing requirements to shapely.egg-info/requires.txt
writing top-level names to shapely.egg-info/top_level.txt
Traceback (most recent call last):
  File "/home/majinge/.local/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line
351, in <module>
    main()
  File "/home/majinge/.local/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line
333, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/home/majinge/.local/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line
118, in get_requires_for_build_wheel
    return hook(config_settings)
  File "/tmp/build-env-y3v_66dm/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in
get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
  File "/tmp/build-env-y3v_66dm/lib/python3.10/site-packages/setuptools/build_meta.py", line 323, in
_get_build_requires
    self.run_setup()
  File "/tmp/build-env-y3v_66dm/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in
run_setup
    exec(code, locals())
  File "<string>", line 212, in <module>
  File "/tmp/build-env-y3v_66dm/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in
setup
    return distutils.core.setup(**attrs)
  File "/tmp/build-env-y3v_66dm/lib/python3.10/site-packages/setuptools/_distutils/core.py", line
185, in setup
    return run_commands(dist)
  File "/tmp/build-env-y3v_66dm/lib/python3.10/site-packages/setuptools/_distutils/core.py", line
201, in run_commands
    dist.run_commands()
  File "/tmp/build-env-y3v_66dm/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line
969, in run_commands
    self.run_command(cmd)
  File "/tmp/build-env-y3v_66dm/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in
run_command
    super().run_command(command)
  File "/tmp/build-env-y3v_66dm/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line
988, in run_command
    cmd_obj.run()
  File "/tmp/build-env-y3v_66dm/lib/python3.10/site-packages/setuptools/command/egg_info.py", line
314, in run
    self.find_sources()
  File "/home/majinge/pyodide-main/packages/shapely/build/shapely-2.0.1/versioneer.py", line 1995, in
find_sources
    super().find_sources()
  File "/tmp/build-env-y3v_66dm/lib/python3.10/site-packages/setuptools/command/egg_info.py", line
322, in find_sources
    mm.run()
  File "/tmp/build-env-y3v_66dm/lib/python3.10/site-packages/setuptools/command/egg_info.py", line
551, in run
    self.add_defaults()
  File "/tmp/build-env-y3v_66dm/lib/python3.10/site-packages/setuptools/command/egg_info.py", line
589, in add_defaults
    sdist.add_defaults(self)
  File "/tmp/build-env-y3v_66dm/lib/python3.10/site-packages/setuptools/command/sdist.py", line 104,
in add_defaults
    super().add_defaults()
  File "/tmp/build-env-y3v_66dm/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py",
line 251, in add_defaults
    self._add_defaults_ext()
  File "/tmp/build-env-y3v_66dm/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py",
line 335, in _add_defaults_ext
    build_ext = self.get_finalized_command('build_ext')
  File "/tmp/build-env-y3v_66dm/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 305,
in get_finalized_command
    cmd_obj.ensure_finalized()
  File "/tmp/build-env-y3v_66dm/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 111,
in ensure_finalized
    self.finalize_options()
  File "<string>", line 134, in finalize_options
ModuleNotFoundError: No module named 'numpy'
<string>:8: DeprecationWarning: pkg_resources is deprecated as an API. See
https://setuptools.pypa.io/en/latest/pkg_resources.html
/tmp/build-env-y3v_66dm/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py:66:
_BetaConfiguration: Support for `` in `pyproject.toml` is still *beta*.
  config = read_configuration(filepath, True, ignore_option_errors, dist)
running egg_info
writing shapely.egg-info/PKG-INFO
writing dependency_links to shapely.egg-info/dependency_links.txt
writing requirements to shapely.egg-info/requires.txt
writing top-level names to shapely.egg-info/top_level.txt
Traceback (most recent call last):
  File "/home/majinge/.local/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line
351, in <module>
    main()
  File "/home/majinge/.local/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line
333, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/home/majinge/.local/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line
118, in get_requires_for_build_wheel
    return hook(config_settings)
  File "/tmp/build-env-y3v_66dm/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in
get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
  File "/tmp/build-env-y3v_66dm/lib/python3.10/site-packages/setuptools/build_meta.py", line 323, in
_get_build_requires
    self.run_setup()
  File "/tmp/build-env-y3v_66dm/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in
run_setup
    exec(code, locals())
  File "<string>", line 212, in <module>
  File "/tmp/build-env-y3v_66dm/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in
setup
    return distutils.core.setup(**attrs)
  File "/tmp/build-env-y3v_66dm/lib/python3.10/site-packages/setuptools/_distutils/core.py", line
185, in setup
    return run_commands(dist)
  File "/tmp/build-env-y3v_66dm/lib/python3.10/site-packages/setuptools/_distutils/core.py", line
201, in run_commands
    dist.run_commands()
  File "/tmp/build-env-y3v_66dm/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line
969, in run_commands
    self.run_command(cmd)
  File "/tmp/build-env-y3v_66dm/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in
run_command
    super().run_command(command)
  File "/tmp/build-env-y3v_66dm/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line
988, in run_command
    cmd_obj.run()
  File "/tmp/build-env-y3v_66dm/lib/python3.10/site-packages/setuptools/command/egg_info.py", line
314, in run
    self.find_sources()
  File "/home/majinge/pyodide-main/packages/shapely/build/shapely-2.0.1/versioneer.py", line 1995, in
find_sources
    super().find_sources()
  File "/tmp/build-env-y3v_66dm/lib/python3.10/site-packages/setuptools/command/egg_info.py", line
322, in find_sources
    mm.run()
  File "/tmp/build-env-y3v_66dm/lib/python3.10/site-packages/setuptools/command/egg_info.py", line
551, in run
    self.add_defaults()
  File "/tmp/build-env-y3v_66dm/lib/python3.10/site-packages/setuptools/command/egg_info.py", line
589, in add_defaults
    sdist.add_defaults(self)
  File "/tmp/build-env-y3v_66dm/lib/python3.10/site-packages/setuptools/command/sdist.py", line 104,
in add_defaults
    super().add_defaults()
  File "/tmp/build-env-y3v_66dm/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py",
line 251, in add_defaults
    self._add_defaults_ext()
  File "/tmp/build-env-y3v_66dm/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py",
line 335, in _add_defaults_ext
    build_ext = self.get_finalized_command('build_ext')
  File "/tmp/build-env-y3v_66dm/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 305,
in get_finalized_command
    cmd_obj.ensure_finalized()
  File "/tmp/build-env-y3v_66dm/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 111,
in ensure_finalized
    self.finalize_options()
  File "<string>", line 134, in finalize_options
ModuleNotFoundError: No module named 'numpy'

**Comment by ryanking13** [comment]
It looks like shapely now requires numpy in the buildstep, which means you need to add `numpy` to `requirements/host` in the shapely recipe.

> does pyodide support shapely 2.0 in future version?

**Comment by ryanking13** [comment]
> does pyodide support shapely 2.0 in future version?

I'll try and open a PR if the version bump works well :)

**Comment by ryanking13** [comment]
Sorry for the very late response @majinge7846, I tried to bump shapely version and it builds, but I am getting the following error when [testing geopandas](https://app.circleci.com/pipelines/github/ryanking13/pyodide/1852/workflows/c9f2d455-5722-42d4-8300-2e2490d82f10/jobs/35123) (which uses shapely internally):

```
CppException geos::util::IllegalArgumentException: IllegalArgumentException: Overlay input is mixed-dimension
CppException geos::util::IllegalArgumentException: IllegalArgumentException: Overlay input is mixed-dimension
```

**Comment by majinge7846** [comment]
@ryanking13 
image
It seems that shapely treat the error from GEOS as a normal warning (as a kind of compute result).  but pyodide can not handle cppException ? Why the error in c could make pyodide break down?

**Comment by ryanking13** [comment]
@majinge7846 I think we need to set `-fexceptions`. Could you open a separate issue for this? It's hard to track updates in the closed PR.

**Pull request merged**
