### PR TITLE
Upgrades packaging version to v23.0 and micropip to 0.2.2

### PR DESCRIPTION
**Pull request by arpitnath**
### Description

- Updates the packaging version to v23.0 
- Updates micropip Version 0.2.1
Removed patches as per https://github.com/pyodide/pyodide/pull/3253/files#diff-daf52c87866bf9ff09de6c4bdc6788915cd8bf3de8a4471418bfdda667607ebbR6

### CODE REVIEW

**Comment by rth** [comment]
Thanks!

Looks like there is a genuine test failure we need to address,
<details>

```
___________________ test_install_different_version2[chrome] ____________________
packages/micropip/test_micropip.py:130: in test_install_different_version2
    selenium.run_js(
/usr/share/miniconda/envs/pyodide-env/lib/python3.11/site-packages/pytest_pyodide/runner.py:249: in run_js
    return self.run_js_inner(code, check_code)
/usr/share/miniconda/envs/pyodide-env/lib/python3.11/site-packages/pytest_pyodide/runner.py:404: in run_js_inner
    raise JavascriptException(retval[1], retval[2])
E   pytest_pyodide.runner.JavascriptException: PythonError: Traceback (most recent call last):
E     File "/lib/python3.11/_pyodide/_base.py", line 532, in eval_code_async
E       await CodeRunner(
E     File "/lib/python3.11/_pyodide/_base.py", line 357, in run_async
E       await coroutine
E     File "<exec>", line 3, in <module>
E     File "/lib/python3.11/site-packages/micropip/_micropip.py", line 566, in install
E       await transaction.gather_requirements(requirements)
E     File "/lib/python3.11/site-packages/micropip/_micropip.py", line 332, in gather_requirements
E       await gather(*requirement_promises)
E     File "/lib/python3.11/site-packages/micropip/_micropip.py", line 339, in add_requirement
E       return await self.add_requirement_inner(Requirement(req))
E              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E     File "/lib/python3.11/site-packages/micropip/_micropip.py", line 434, in add_requirement_inner
E       wheel = find_wheel(metadata, req)
E               ^^^^^^^^^^^^^^^^^^^^^^^^^
E     File "/lib/python3.11/site-packages/micropip/_micropip.py", line 272, in find_wheel
E       candidate_versions = sorted(
E                            ^^^^^^^
E     File "/lib/python3.11/site-packages/micropip/_micropip.py", line 273, in <genexpr>
E       (Version(v) for v in req.specifier.filter(releases)),
E       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E     File "/lib/python3.11/site-packages/packaging/specifiers.py", line 616, in filter
E       parsed_version = _coerce_version(version)
E                        ^^^^^^^^^^^^^^^^^^^^^^^^
E     File "/lib/python3.11/site-packages/packaging/specifiers.py", line 36, in _coerce_version
E       version = Version(version)
E                 ^^^^^^^^^^^^^^^^
E     File "/lib/python3.11/site-packages/packaging/version.py", line 197, in __init__
E       raise InvalidVersion(f"Invalid version: '{version}'")
E   packaging.version.InvalidVersion: Invalid version: '2004d'
```
</details>

Not really sure where that `2004d` version is coming from. The  [`packages/micropip/test_micropip.py::test_install_different_version2`](https://github.com/pyodide/pyodide/blob/main/packages/micropip/test_micropip.py#L128) looks ok and we have exactly the same [test in micropip](https://github.com/pyodide/micropip/blob/main/tests/test_micropip.py#L648) which passes. But indeed that situation of having the same tests copied twice is not ideal, maybe something else got out of sync in that test file which would explain it.

**Comment by ryanking13** [comment]
The error happens when we loop through all versions listed in PyPI. There is a version [`pytz==2004d`](https://pypi.org/project/pytz/2004d/) which was released in 2005. Packaging handled this by a `LegacyVersion` class, but they [dropped it recently](https://github.com/pypa/packaging/pull/407/files).

I guess we should just ignore invalid versions?

> we have exactly the same [test in micropip](https://github.com/pyodide/micropip/blob/main/tests/test_micropip.py#L648) which passes.

Tests in `pyodide/micropip` downloads pyodide distribution 0.22.1 or 0.23.0a1 during the test so it will use packaging 21.3.

**Comment by rth** [comment]
Indeed, thanks for looking into it @ryanking13 !  A fix is in https://github.com/pyodide/micropip/pull/54, once that is merged and micropip released we can use that version here.

**Comment by rth** [comment]
Thanks @arpitnath !

**Comment by arpitnath** [comment]
Hi @rth, at what point in time can we anticipate the acceptance of a new release featuring the updated packaging?

**Pull request merged**
