### PR TITLE
Add bump2version

### PR DESCRIPTION
**Pull request by andreysmelter**
WIP PR: 

Partially addresses [issue 2438](https://github.com/pyodide/pyodide/issues/2438)
by bumping up source code files.

Next steps:
- automate version bumpup in docs/*.md files

### CODE REVIEW

**Comment by ryanking13** [comment]
Thanks, @andreysmelter! `bump2version` looks like very cool stuff.

I have a question. For alpha/dev versions, Python packages and JS packages have different version schemes. For example, we use `0.20.0a1` for Python package while `0.20.0-alpha.1` for JS package.

Can we deal with this in a single command? For example, it would be great if we can do this in a config file:

```cfg
# inside .bumpversion.cfg  / setup.cfg
[bumpversion]
current_version = 0.20.1
new_version_python = 0.20.1a1
new_version_js = 0.20.1-alpha.1
```

**Comment by hoodmane** [comment]
It might be better to use `setuptools-scm` since it has a Python interface and so we could do whatever complicated stuff we need to in a Python script rather than having to have a config file.

**Comment by rth** [comment]
> It might be better to use setuptools-scm since it has a Python interface and so we could do whatever complicated stuff we need to in a Python script rather than having to have a config file.

Generally, I like bump2version for Python packages, but I'm not sure that's the best option here. setuptools-scm  is not really going to work on non Python files (e.g. run_docker) without significant development  where you provide it with some list of lines to replace and how to do that, which is what bump2version does.
Also e.g. the format `{next_version}.dev{distance}+{scm letter}{revision hash}` of setuptools-scm is not really appropriate for
 - js package
 - docker image
 - for the docs when pushing on the stable branch fixes after the release

So I think keeping things simple with a simple setuptools-scm config is a start (and is already way better than what we had before). Though yes, this means that the alpha versions for the JS package need manual adjustment. If we want to go further later, we can always create a custom Python script calling  bump2version in more custom ways. 
BTW, it's also already parsing the latest git tag https://github.com/c4urself/bump2version/blob/bc95374d0dff73e610bed520846f88859815e532/bumpversion/cli.py#L231 though I haven't looked in detail what it does with it.

**Comment by rth** [comment]
Edited the above comment to avoid confusion between the two tools :)

**Comment by andreysmelter** [comment]
@rth I can take a look at this next week and continue iterating on this PR. Thanks for the comments and ideas!

**Review by rth — APPROVED** [review]
OK, I can confirm this works as expected. I pushed a few extra minor improvements.  But yeah anyway one has to look at the git diff and often make manual adjustments before committing/tagging. Still, it's much better than the system we have now.

Merging this as a partial solution, and we can always improve it in follow up MRs (in particular to also do this in the docs with sphinx). Thanks, @andreysmelter !

**Pull request merged**
