### PR TITLE
Update numpy to v1.22.3

### PR DESCRIPTION
**Pull request by hoodmane**
Trying to build this locally I get an Assertion failure inside LLVM. *sigh*

### CODE REVIEW

**Comment by hoodmane** [comment]
<details>
<summary>Clang backtrace</summary>

```C++
clang++: /b/s/w/ir/cache/builder/emscripten-releases/llvm-project/llvm/include/llvm/MC/MCAsmMacro.h:116: int64_t llvm::AsmToken::getIntVal() const: Assertion `Kind == Integer && "This token isn't an integer!"' failed.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /src/emsdk/emsdk/upstream/bin/clang++ -target wasm32-unknown-emscripten -Werror=implicit-function-declaration -Werror=mismatched-parameter-types -Werror=return-type -O2 -std=c++14 numpy/core/src/umath/svml/linux/avx512/svml_z0_cbrt_d_la.s -c -o /tmp/emscripten_temp_h1gbuzva/svml_z0_cbrt_d_la_0.o
 #0 0x00007ff0797c0ef3 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/src/emsdk/emsdk/upstream/bin/../lib/libLLVM-14git.so+0x19b0ef3)
 #1 0x00007ff0797bec9e llvm::sys::RunSignalHandlers() (/src/emsdk/emsdk/upstream/bin/../lib/libLLVM-14git.so+0x19aec9e)
 #2 0x00007ff0797c026d llvm::sys::CleanupOnSignal(unsigned long) (/src/emsdk/emsdk/upstream/bin/../lib/libLLVM-14git.so+0x19b026d)
 #3 0x00007ff0796f1ee3 (anonymous namespace)::CrashRecoveryContextImpl::HandleCrash(int, unsigned long) CrashRecoveryContext.cpp:0:0
 #4 0x00007ff0796f208e CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #5 0x00007ff077dfa730 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x12730)
 #6 0x00007ff073dc17bb raise (/lib/x86_64-linux-gnu/libc.so.6+0x377bb)
 #7 0x00007ff073dac535 abort (/lib/x86_64-linux-gnu/libc.so.6+0x22535)
 #8 0x00007ff073dac40f (/lib/x86_64-linux-gnu/libc.so.6+0x2240f)
 #9 0x00007ff073dba102 (/lib/x86_64-linux-gnu/libc.so.6+0x30102)
#10 0x00007ff07b98fd28 (anonymous namespace)::WebAssemblyAsmParser::ParseInstruction(llvm::ParseInstructionInfo&, llvm::StringRef, llvm::SMLoc, llvm::SmallVectorImpl<std::unique_ptr<llvm::MCParsedAsmOperand, std::default_delete<llvm::MCParsedAsmOperand> > >&) WebAssemblyAsmParser.cpp:0:0
#11 0x00007ff07b104d6f (anonymous namespace)::AsmParser::parseAndMatchAndEmitTargetInstruction((anonymous namespace)::ParseStatementInfo&, llvm::StringRef, llvm::AsmToken, llvm::SMLoc) AsmParser.cpp:0:0
#12 0x00007ff07b0f888f (anonymous namespace)::AsmParser::parseStatement((anonymous namespace)::ParseStatementInfo&, llvm::MCAsmParserSemaCallback*) AsmParser.cpp:0:0
#13 0x00007ff07b0f222f (anonymous namespace)::AsmParser::Run(bool, bool) AsmParser.cpp:0:0
#14 0x0000000000217bf4 cc1as_main(llvm::ArrayRef<char const*>, char const*, void*) (/src/emsdk/emsdk/upstream/bin/clang+++0x217bf4)
#15 0x00000000002123c1 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#16 0x00007ff076f02da2 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const::$_1>(long) Job.cpp:0:0
#17 0x00007ff0796f1df7 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/src/emsdk/emsdk/upstream/bin/../lib/libLLVM-14git.so+0x18e1df7)
#18 0x00007ff076f028f7 clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const (/src/emsdk/emsdk/upstream/bin/../lib/libclang-cpp.so.14git+0x2e1a8f7)
#19 0x00007ff076ecde18 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&) const (/src/emsdk/emsdk/upstream/bin/../lib/libclang-cpp.so.14git+0x2de5e18)
#20 0x00007ff076ece0e7 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) const (/src/emsdk/emsdk/upstream/bin/../lib/libclang-cpp.so.14git+0x2de60e7)
#21 0x00007ff076ee7f01 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) (/src/emsdk/emsdk/upstream/bin/../lib/libclang-cpp.so.14git+0x2dfff01)
#22 0x00000000002119c6 main (/src/emsdk/emsdk/upstream/bin/clang+++0x2119c6)
#23 0x00007ff073dae09b __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409b)
#24 0x000000000020eeca _start (/src/emsdk/emsdk/upstream/bin/clang+++0x20eeca)
clang-14: error: clang integrated assembler command failed with exit code 134 (use -v to see invocation)
clang version 14.0.0 (https://github.com/llvm/llvm-project 78e87970af888bbbd5652c31f3a8454e8e9dd5b8)
```

</details>

**Comment by hoodmane** [comment]
Okay the problem is in `avx512/svml_z0_asinh_s_la.s` so the problem is I haven't disabled vectorization correctly.

**Comment by ryanking13** [comment]
> We really need to figure out a way to deal with all these `sys.platform == "linux"` style checks which pass because our build machine is a linux even though our target is not.

Maybe we can try mocking the platform string before running the build, though I think it will probably break builds of some other packages...

**Review by rth — APPROVED** [review]
Thanks for migrating all the patches!

**Pull request merged**
