### PR TITLE
Add descr_get handler to JsMethod

### PR DESCRIPTION
**Pull request by hoodmane**
This is the converse of #3103. It allows a JavaScript function to be used as a Python method. When it is called, `this` will be a `PyProxy` pointing to the Python object the method is called on.

### Checklists

- [x] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry
- [x] Add / update tests

### CODE REVIEW

**Review by ryanking13 — APPROVED** [review]
It looks good to me. Thanks @hoodmane!

**Comment by rth** [comment]
Thank you!

**Comment by hoodmane** [comment]
It seems like this introduced a regression in the matplotlib canvas backend. So far it is nontrivial to reproduce.

**Comment by ryanking13** [comment]
> It seems like this introduced a regression in the matplotlib canvas backend. So far it is nontrivial to reproduce.

Yes, It seems like the error doesn't always happen so it is not easy to analyze.

**Comment by hoodmane** [comment]
Yeah I was unable to reproduce it locally either. When I run benchmarks they all work. Strange...

**Pull request merged**
