### PR TITLE
MAINT micropip: move most methods from `PackageManager` to `Transaction` and remove `PackageManager`

### PR DESCRIPTION
**Pull request by hoodmane**
This is more reorganization of `micropip` to try to make the logic easier to follow. I turned `INSTALLED_PACKAGES` into a global variable. I turned `_install` into a top level function definition and merged it with `install` rather than a class method. The other methods of `PackageManager` turned into `Transaction` methods. I removed `PackageManager` entirely.

### CODE REVIEW

**Comment by hoodmane** [comment]
I'm not really sure why `matplotlib` fails to build on this branch...

**Review by ryanking13 — APPROVED** [review]
> I turned `_install` into a top level function definition and merged it with `install` rather than a class method.

I was always thinking of this but never worked on it, thanks @hoodmane!
I didn't review the detail, I guess code details are not changed much right?

There is a failure in CI, but the matplotlib build failure doesn't seem related to this PR.

**Comment by hoodmane** [comment]
Yeah it seems that matplotlib is failing on a bunch of my branches with `micropip`-related changes.

> code details are not changed much right?

No, it's just a refactoring. I consolidated `PackageManager.install` with `install` functions, moved the other methods from `PackageManager` to `Transaction`, and moved `PackageManager.installed_packages` to `INSTALLED_PACKAGES` global variables.

**Comment by hoodmane** [comment]
Thanks for the review @ryanking13!

**Comment by ryanking13** [comment]
It seems like recent release of setuptools is causing un error https://github.com/pyodide/pyodide/issues/2567

**Pull request merged**
