### PR TITLE
ENH Update sqlite

### PR DESCRIPTION
**Pull request by amitsaha**
### Description

Fix for https://github.com/pyodide/pyodide/issues/2469

### Checklists

- [x] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry

### CODE REVIEW

**Review by ryanking13 — APPROVED** [review]
Thanks, @amitsaha! LGTM.

**Comment by hoodmane** [comment]
Hmmm ideally we should be checking the integrity... (No action needed in this PR.)

**Comment by stonebig** [comment]
sqlite-3380500 is out

**Comment by ryanking13** [comment]
@stonebig Thanks for the information. Are you interested in opening a PR?

**Comment by stonebig** [comment]
hummm. will have a look if I can do it in 5', not very good at GIT

**Pull request merged**
