### PR TITLE
Version update for python-sat.

### PR DESCRIPTION
**Pull request by alexeyignatiev**
This updates the version of python-sat. No changes are made in the compilation process for the package itself, i.e. I am hopeful it will successfully pyodide-compile "as is".

### Checklists

- [ ] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry
- [ ] Add / update tests
- [ ] Add new / update outdated documentation

### CODE REVIEW

**Comment by rth** [comment]
Thanks @alexeyignatiev ! LGTM.

Looks like I broke CircleCI OAuth recently, I'll push a few commits to this PR to try to debug it. (I cannot debug it from a different PR I open since that would use a different CircleCI account).

**Comment by alexeyignatiev** [comment]
Thank you, @rth. Please let me know if I need to do something on my end.

**Comment by hoodmane** [comment]
Looks like it worked. Thanks @alexeyignatiev!

**Comment by alexeyignatiev** [comment]
Thanks!

**Comment by hoodmane** [comment]
Uh oh looks like circleci still has trouble on the main branch.

**Comment by rth** [comment]
The added the CiercleCI SSH key again. Looks like it's OK now.

**Pull request merged**
