### PR TITLE
Enable python_solvespace

### PR DESCRIPTION
**Pull request by fuyb1992**
The building process works fine on docker pyodide/pyodide:0.20.0, try to test if it works on build-packages-no-numpy-dependents,  issue related: https://github.com/pyodide/pyodide/pull/2308.

### CODE REVIEW

**Comment by fuyb1992** [comment]
Error when builing python_solvespace in  `build-packages-no-numpy-dependents`  process:
```
cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DM_PI=PI -D_USE_MATH_DEFINES -DISOLATION_AWARE_ENABLED -DLIBRARY -DEXPORT_DLL -D_CRT_SECURE_NO_WARNINGS -DUNIX_DATADIR=\"solvespace\" -Ipython_solvespace/include -Ipython_solvespace/src -Ipython_solvespace/extlib/mimalloc/include -Ipython_solvespace/extlib/mimalloc/src -I/tmp/build-env-l5uxtidc/include -I/usr/local/include/python3.10 -c python_solvespace/slvs.cpp -o build/temp.emscripten_wasm32-3.10/python_solvespace/slvs.o -O3 -Wno-cpp -g -Wno-write-strings -fpermissive -fPIC -std=c++17
em++: error: python_solvespace/slvs.cpp: No such file or directory ("python_solvespace/slvs.cpp" was expected to be an input file, based on the commandline arguments provided)
```
The missing file python_solvespace/slvs.cpp comes from cythoning:
image

`build-packages-no-numpy-dependents`  process skips the `cythoning` step, `build-packages` works fine (maybe changes  in https://github.com/pyodide/pyodide/pull/2126 cause this).

I don't know if there is a switch in `meta.yaml` that can control the build process  so I add `numpy` to `requirements` temporarily.

**Comment by hoodmane** [comment]
Huh. It would be helpful if we could tell it to hard fail rather than skipping Cython because it has caused a fair amount of confusion. Try adding:
```
build:
	script:
		pip install -t $HOSTSITEPACKAGES cython
```

**Comment by fuyb1992** [comment]
CI timeout, need re-triggering CI.

**Review by ryanking13 — APPROVED** [review]
Thanks, @fuyb1992. I retriggered the CI. The timeout is not related to the `python_solvespace`, so generally LGTM.

**Comment by fuyb1992** [comment]
Thanks, @ryanking13

**Pull request merged**
