### PR TITLE
Emscripten 3.1.23

### PR DESCRIPTION
**Pull request by hoodmane**
### Checklists

- [ ] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry

### CODE REVIEW

**Comment by ryanking13** [comment]
I guess the build error is related to the change that Emscripten's default C++ standard is changed to `c++17` and `random_shuffle` [has been removed](https://en.cppreference.com/w/cpp/algorithm/random_shuffle) in c++17.

**Comment by ryanking13** [comment]
It looks like we are adding `std=c++14` in [LDFLAGS](https://github.com/pyodide/pyodide/blob/9a3365a6d0325caec5c609967c11edc041cb6d99/Makefile.envs#L95) but not in CFLAGS now. I'm not sure why.

**Comment by hoodmane** [comment]
I opened an issue about it here:
https://github.com/matplotlib/matplotlib/issues/24010

**Comment by ryanking13** [comment]
Thanks, probably we need to add `std=c++14` (or `std=c++17` if it works) in our CFLAGS.

**Comment by ryanking13** [comment]
Hmm it seems like the build.log is not created after the build.

**Comment by CallumJHays** [comment]
The issue seems to be typer not parsing the "-std=c++14" correctly as the value of the argument "--cxxflags" .
This throws an error, stopping the build before build.log is ever created for that module.

I was able to get typer to parse it correctly by making the following changes to `pyodide_build/buildall.py`:

image

**Comment by hoodmane** [comment]
Thanks for looking into this. I guess we should change all the arguments
like that...

**Comment by ryanking13** [comment]
The CI failures are not from this PR and are fixed in main branch, I synced to the main and rerun CI. Fingers crossed 🤞

**Comment by hoodmane** [comment]
Thanks @CallumJHays and @ryanking13!

**Pull request merged**
