### PR TITLE
Catch KeyError in importhook

### PR DESCRIPTION
**Pull request by hoodmane**
- [x] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry
- [x] Add / update tests

### CODE REVIEW

**Review by ryanking13 — COMMENTED** [review]
Could you please give a little bit more context around this change?

**Comment by hoodmane** [comment]
I got a `KeyError` error here when doing test collection for matplotlib. I'll try to make a repro when I have a moment.

**Comment by hoodmane** [comment]
But it's not clear to me why parent *should* be in `sys.modules` here.

**Review by ryanking13 — APPROVED** [review]
> But it's not clear to me why parent should be in sys.modules here.

Hmm, I see. That code was added too long ago, so I am not sure about that, too. The change looks okay anyways.

**Comment by hoodmane** [comment]
A reproduction for this looks like:
```py
import sys

def _import_module_using_spec(module_name):
    for meta_importer in sys.meta_path:
        spec = meta_importer.find_spec(module_name, path=[])

 _import_module_using_spec("a.b")
```
This is a fragment of what pytest does here:
https://github.com/pytest-dev/pytest/blob/main/src/_pytest/pathlib.py#L693-L698

These calls will never come from importlib, when processing `a.b` importlib will always look at `a` first and then `a.b`.

**Pull request merged**
