### PR TITLE
Keep webpackIgnore comments in pyodide.js

### LINKED ISSUE #4174: Cannot find module 'https://cdn.jsdelivr.net/pyodide/dev/full/pyodide.asm.js'
Hi all. I have the following problem: I'm trying to use pyodide in a react. I installed the package using npm install, and imported the loadPyodide function from it. I have this code:
```
const pyodide = await loadPyodide({
             indexURL: "https://cdn.jsdelivr.net/pyodide/v0.24.0/full/",
             fullStdLib: true,
             stdin: window.prompt,
             stdout: (text) => {
                 if (text !== "Python initialization complete") {
                     setResult(prevState => prevState + text + "\n")
                 }
             },
             stderr: (text) => {
                 setResult(prevState => prevState + text + "\n")
             }
         });
```
However I get an error:
```
Cannot find module 'https://cdn.jsdelivr.net/pyodide/dev/full/pyodide.asm.js'
     at http://localhost:3000/static/js/bundle.js:277779:11
     at async loadScript (http://localhost:3000/static/js/bundle.js:317327:43)
     at async loadPyodide (http://localhost:3000/static/js/bundle.js:317657:5)
     at async loadPython (http://localhost:3000/static/js/bundle.js:41685:21)
     at async run (http://localhost:3000/static/js/bundle.js:41761:24)
```
How can you solve it? I would appreciate your answer.

### PR DESCRIPTION
**Pull request by ryanking13**
### Description

Resolve #4174

After we changed our build system to esbuild (https://github.com/pyodide/pyodide/pull/3679), `/* webpackIgnore */` comments were stripped out after the build.

Since we dynamically import pyodide.asm.js from pyodide.[m]js, this comment is required for webpack bundler (unless we find a better way to deal with this... like merging pyodide.js and pyodide.mjs? I don't know.)

This PR fixes it by putting webpackIgnore comments for every `import()` statement after building pyodide.js.
A user can do this by adding a webpack plugin, as described in [pyodide-webpack-plugin](https://github.com/pyodide/pyodide-webpack-plugin/blob/9112d85cfe45325d43b73301a10c1202f1570f78/README.md?plain=1#L100-L119), but I think it is better if we can handle it.

Related:

- https://github.com/pyodide/pyodide/issues/4004
- https://github.com/pyodide/pyodide/issues/4174
- https://github.com/evanw/esbuild/issues/2721: esbuild added support for preserving magic comments, but it is not compatible with some `minify` flags.

### Checklists

- [x] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry

### CODE REVIEW

**Comment by hoodmane** [comment]
@mneil What's your thought on `webpackIgnore` comments? Do you think we should just drop them and encourage people to use your plugin?

**Comment by mneil** [comment]
My opinion is that the library should not make any assumptions about how it will be consumed. Users choosing to bundle with webpack need to understand the implications of choosing that tool and how to work with it. Rollup, Turbopack, esbuild, Webpack, and other tools exist to do the same thing. I'm not sure pyodide should attempt to do anything specifically for one or more of these tools. 

The plugin now has a custom loader that skips parsing by webpack so that it doesn't import anything. It's close to adding the ignore comments on the imports. It also handles copying the necessary dependencies like pyodide.asm.js and other files. Obviously I'm biased in favor of the plugin :)

**Comment by hoodmane** [comment]
> close to adding the ignore comments on the imports

Meaning it doesn't do this yet? So maybe we should leave them in for now and then drop all of these once the plugin adds support for this?

**Comment by mneil** [comment]
No, I'm sorry for the confusion. What I meant by "close to adding" is that the functionality is similar, but it is accomplished in a different way. It does not need to add those comments because it doesn't go through webpack's javascript parser anymore. 

The comments are not necessary for the plugin to work correctly.

**Comment by hoodmane** [comment]
Ok then I vote to drop these because they are a wart. If we want to provide webpack-specific support, we should focus on improving the discoverability of the plugin.

**Comment by ryanking13** [comment]
Thanks for the info! I agree that the handling of bundler-specific things should be handled in the plugin. Maybe let's include this to 0.25.0 for now, and find a way to improve the discoverability of the plugin + test the plugin in the Pyodide repository.

**Comment by hoodmane** [comment]
> include this to 0.25.0 for now, and find a way to improve the discoverability of the plugin + test the plugin in the Pyodide repository

Should we open one or more followup issues for these tasks?

**Comment by ryanking13** [comment]
I opened a followup issue (https://github.com/pyodide/pyodide/issues/4361)

**Pull request merged**
