### PR TITLE
Deploy a debug version of Pyodide to the CDN

### PR DESCRIPTION
**Pull request by hoodmane**
At end of deploy stage, rebuild Pyodide with debug symbols and deploy it.

Closes https://github.com/pyodide/pyodide/issues/366

### CODE REVIEW

**Comment by hoodmane** [comment]
@rth

**Comment by ryanking13** [comment]
I think Roman wanted to drop `pyodide-cdn2.iodide.io`. Perhaps we can deploy it to jsdelivr?
BTW, I can't find a CI job which deploys to the jsdelivr.

**Comment by hoodmane** [comment]
I think jsdelivr is currently set up to mirror `pyodide-cdn2.iodide.io`?

**Comment by rth** [comment]
> I think jsdelivr is currently set up to mirror pyodide-cdn2.iodide.io?

No. What happens is that we have a S3 buckets named that way for historical reasons that we, unfortunately, can't easily rename. The bucket name doesn't really matter and it's distinct from a domain name. It is then,
 - exposed via this iodide.io domain name through Cloudflare however caching doesn't work as expected.
 - exposed via jsdelivr with proper caching.

So the bottom line is we should never use the pyodide-cdn2.iodide.io domain name. I need to ask [wlach](https://github.com/wlach)  to setup a redirect to jsdelivr.

**Review by rth — APPROVED** [review]
Thanks! Yes, having a debug build has been discussed for a while https://github.com/pyodide/pyodide/issues/366 though we mostly managed without so far.

**Comment by hoodmane** [comment]
Oops we're in the wrong docker image. I guess I'll have to rearrange it a bit.

**Pull request merged**
