### PR TITLE
fix for half of pyodide/pyodide#2505

### PR DESCRIPTION
**Pull request by dragoncoder047**
applied patch here: https://github.com/pyodide/pyodide/issues/2505#issuecomment-1118591356

### CODE REVIEW

**Comment by rth** [comment]
Thanks @dragoncoder047 ! Could you please post a screenshot or copy-paste of the REPL result when using input with this change?

**Comment by rth** [comment]
You can copy `src/templates/console.html` in a different folder. Update the Podide download link to `https://cdn.jsdelivr.net/pyodide/dev/full/pyodide.js`, then start a local HTTP server with `python -m http.server` and open the console.html in your browser.

**Comment by ryanking13** [comment]
Here is the REPL result.

https://user-images.githubusercontent.com/24893111/167232548-1d05d5d6-7ba5-4888-b6de-041d45fa634c.mp4

I'm not sure if this is what we want. WDYT @rth?

**Comment by hoodmane** [comment]
I think it's better than the current behavior, I'm +1 to merge it.

**Comment by hoodmane** [comment]
Thanks for testing it @ryanking13!

**Review by rth — APPROVED** [review]
> I think it's better than the current behavior, I'm +1 to merge it.

Agreed. It is indeed closer to the standard REPL behavior. Thanks @dragoncoder047 and @ryanking13 !

**Pull request merged**
