### PR TITLE
Hide deprecated arguments from docs

### PR DESCRIPTION
**Pull request by hoodmane**
This adds a mechanism to hide deprecated or private arguments from the documentation and 
applies it to `errorCallbackDeprecated`.

Also, the positional callback deprecation was not working correctly so I fixed it.

- [x] Add / update tests

### CODE REVIEW

**Review by ryanking13 — APPROVED** [review]
Thanks @hoodmane!

**Comment by ryanking13** [comment]
I guess the test failure is a bug in our NodeRunner in pytest-pyodide, so maybe we can skip that test for this PR?

**Comment by ryanking13** [comment]
I did some minor modifications in your branch to make mypy happy. I hope I didn't messed up.

**Comment by hoodmane** [comment]
Thanks!

**Pull request merged**
