### PR TITLE
Pin types-setuptools to fix mypy build

### PR DESCRIPTION
**Pull request by hoodmane**
Doesn't seem to work without:
https://github.com/pyodide/pyodide-build/pull/49

@agriyakhetarpal @ryanking13

### CODE REVIEW

**Comment by agriyakhetarpal** [comment]
Thanks, @hoodmane! I've proposed a fix earlier today upstream so that we can unpin this later: https://github.com/python/typeshed/pull/12958

**Review by agriyakhetarpal — APPROVED** [review]

**Comment by hoodmane** [comment]
Can you also review the pyodide-build PR?

**Comment by agriyakhetarpal** [comment]
Yes, did that already – I approved both that PR and this one

**Comment by ryanking13** [comment]
A new version of types-setuptools is released so I think we don't need this PR

**Comment by hoodmane** [comment]
Great

**Pull request closed without merging**
