### PR TITLE
Local cache for downloads with Node.js

### PR DESCRIPTION
**Pull request by rth**
The general idea is to,
 - expose as private API `pyodide_js._fetch_cached` which would transparently call fetch API in the browser and some fetch like function with local caching in Node.
 - Use this function everywhere we currently use fetch, including in micropip. This in particular avoids having to expose a global `fetch` function in Node.

The main motivation is to make sure we are not repeatedly re-downloading the same packages from micropip and JsDelivr CDN in Node.

TODO:
 - [ ] pick a good fetch library in library with caching. So far I tried,
   - node-fetch: this works fine, however caching is not supported and won't be https://github.com/node-fetch/node-fetch/issues/68
   - [node-fetch-cache](https://github.com/mistval/node-fetch-cache) fairly new, not very popular, maintained -> fails when loading node-fetch as a ES6 module in the dependencies. Probably needs reporting upstream.
   - [make-fetch-happen](https://github.com/npm/make-fetch-happen) -> currently used, I still need to debug some issues.
   - Maybe in the long term it would make sense to [axios](https://github.com/axios/axios) but not in this PR.
  
**Secondary goals:**
 - ideally this should also allow to use,
   ```
   let pyodide = await pyodide_pkg.loadPyodide({
     indexURL: "<remote JsDelivr URL>", 
   })
   ```
   in Node. Technically most code parts should be implemented for it to work, however I'm currently getting an error about `require not defined` in pyodide.asm.js because apparently it considers that it's a ES6 module (https://github.com/nodejs/node/issues/33741#issuecomment-639463213). I'm not sure what's different in that aspect between loading local or remote file, it needs more debugging.

  The mocha test suite can also be run with a remote URL by setting the `PYODIDE_BASE_URL` env variable.

### CODE REVIEW

**Comment by grimmer0125** [comment]
Hi @rth, I just want to submit the same thing in discussions and found out this PR. From my perspective, 
- Pyodide packages: The ideal situation is to install them via npm packages for both browser and Node.js usages. For example, like `@pyodie/core`, `@pyodide/numpy`, if it is doable.  
- Users' Python scripts: as proposed in https://github.com/pyodide/pyodide/discussions/1876, already some actions: #1917 and #1935
- Third-party Python packages on PyPI: It may be a normal Python package or even somebody wants to publish a Python package used in Pyodide environment. For PyPI packages, I think of the same re-downloading issue, it feels it can be improved although browsers sometimes will use built-in cache. Some cases. 
    1.  Browser + no self-hosted Pyodide: I'm not sure if this #1776 is also for browser caching or not and I think some caching mechanism is good, either some JS implementation (e.g. using IndexedDB directly) or via #1715 pyodide File system API. 
    2. Browser + self-hosted Pydoide: It can be a Browser extension or mobile environment. People may adopt the same 1. approach or prefer to bundle everything inside. For the latter case, e.g. my Chrome extension, I manually download some Python wheel package and host it. If there is a tool that is able to automate it, it will be great. 
    3. Use Pyodide in Node.js: Just like this PR, it will be great. Besides HTTP caching, I'm not sure using the 2. approach + some `micropip_load_local_file` is a good idea or not. I don know much about the current design/flow of Pyodide Node.js support.

I saw `require not define` error in my tests in #1949. It is apparent that browsers do not support `CommonJS` require syntax and only support `ES6 import` to load a module. There are three difficulties
- How Pyodide JS import these third-party packages. Some cases:
    1. ES6 import to use http fetch packages, not local file protocol. 
    2. CommonJS `require` (not work in browser)
    3. Bundle them (traditional way) into Pyodide JS. 
- These third-party packages may use other packages, either Node.js built-in packages or other npm packages. Usually, they will not bundle these `node_moduels` so that people (e.g. Pyodide JS) need to install their dependencies.  But this comes to a problem. Some cases:
    1. Pyodide JS does not bundle external dependencies and their dependencies, it can not work directly in browsers since browsers can not natively install npm package (<-CDN way). It may only work if Pyodide users use some bundler (e.g. parcel/webpack) and have a proper setting. 
    2. Pyodide JS bundles these packages and dependencies. In this way, there is no `require not defined` issue. 
    3. *Pyodide only bundle these packages but exclude dependencies <- I think it probably will not happen in any bundler settings.
- Node.js only API does not work in browsers. Need to find out polyfill package/usage.
 
 If adding npm dependency in Pyoide npm package or PyodideJS use some Node.js only API, some of these issues may happen in browsers. I encounter these issues when publishing my @d4c/numjs package. So I just share the thoughts which you may already know these.

**Comment by rth** [comment]
Thanks for your analysis @grimmer0125 !

> Pyodide packages: The ideal situation is to install them via npm

I'll open an issue about it.

> Browser + no self-hosted Pyodide: I'm not sure if this Local cache for downloads with Node.js is also for browser caching or not

I admit I have not tested all browsers, but in my tests `fetch` was fully cached by the browser (or at least it respects the `Cache-Control` headers in the response it gets). So this means that micropip downloads and Pyodide packages should be cached. I'm not sure what happens in the browser extensions, worth checking.

> Browser + self-hosted Pydoide

The above should apply, provided that you serve files with appropriate `Cache-Control` headers. For instance, in Pyodide deployed packages, it's done [here](https://github.com/pyodide/pyodide/blob/main/.circleci/config.yml#L290) (`--cache-control 'max-age=30758400, immutable, public'`)

Thanks for the rest of your comment. I have to think about it. I'm not really using JS much in my everyday work, and your analysis is definitely appreciated. Also, if you are interested in continuing this PR let me know (otherwise I'll get to it eventually).

**Comment by grimmer0125** [comment]
> The above should apply, provided that you serve files with appropriate `Cache-Control` headers. For instance, in Pyodide deployed packages, it's done [here](https://github.com/pyodide/pyodide/blob/main/.circleci/config.yml#L290) (`--cache-control 'max-age=30758400, immutable, public'`)

Originally I guess `an error about require not defined in pyodide.asm.js` is talking about the fetch_cache npm package you tried not working in the browser. So this PR is also for the browser and already got initial working in the browser. The error about `pyodide.asm.js` is a different thing? 

> Thanks for the rest of your comment. I have to think about it. I'm not really using JS much in my everyday work, and your analysis is definitely appreciated. Also, if you are interested in continuing this PR let me know (otherwise I'll get to it eventually).

I would like to help but I can not guarantee how much time I can work on it. I start https://github.com/pyodide/pyodide-webpack-example/pull/4 and I think I can finish that first? Or if you think this local cache has a higher priority and we can discuss. 

BTW, it seems that this PR does not need a local Pyodide building environment (either building core or using emcc  preprocess to generate `pyproxy.gen.js`), isn't it? I can not build Pyodide on my mac M1.

**Comment by rth** [comment]
> I start pyodide/pyodide-webpack-example#4 and I think I can finish that first?

Yes, let's finish that first.

> BTW, it seems that this PR does not need a local Pyodide building environment (either building core or using emcc preprocess to generate pyproxy.gen.js), isn't it?

Likely not, but you might still need to re-build the pyproxy.gen.js, the first time, not sure.

>  I can not build Pyodide on my mac M1.

We need to improve the situation there. I'm a bit stuck on https://github.com/pyodide/pyodide/pull/1912 right now, but it should be fixable. Once that works one should be able to get the x86_64 conda for Mac, and rely on x86_64 emulation on M1 which is pretty good. I guess one could do that with homebrew as well, but because it doesn't have virtual env for system packages, I'm less certain about recommending that as a general solution.

**Comment by grimmer0125** [comment]
> homebrew as well, but because it doesn't have virtual env for system packages
Is the virtual env referring to Python virtual environment? I do not use `conda` and usually, I use homebrew to install some non-python packages and `pyenv` for global interpreters. Then use poetry which uses Python built-in `venv`. This is my habit and it is acceptable to use conda for Pyodide development for me. Either #1386 (arm64 docker) or native build on Mac (x86 or emulation) should be good enough.

**Comment by ryanking13** [comment]
Just for an update: Node.js is started to [experimentally support fetch API](https://github.com/nodejs/node/commit/6ec225392675c92b102d3caad02ee3a157c9d1b7), though it looks like there is no local cache support (yet?).

**Comment by rth** [comment]
This is actually already implemented. When loading packages with the node module, they will be put to node_modules/pyodide/ the first time they are downloaded, then reused. Closing.

**Pull request closed without merging**
