### PR TITLE
Upgrade msgpack to 1.1.0

### PR DESCRIPTION
**Pull request by riyavsinha**
### Description

Update Pyodide version to 1.1.0. 

Trying to install the version currently gives the error that a pure python package is not available, and the maintainer has stated that they will not be releasing one: https://github.com/msgpack/msgpack-python/issues/627. 

### Checklists

- [x] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry
- [x] Add / update tests
- [x] Add new / update outdated documentation

### CODE REVIEW

**Comment by riyavsinha** [comment]
Hi, it seems like the `build_packages` timed out. Is there anything that can be done about that? FWIW I did build the upgraded `msgpack` locally and it worked, and the test passed.

**Comment by hoodmane** [comment]
Thanks @riyavsinha! The CI failure is a flake, I reran it.

**Comment by hoodmane** [comment]
Hmm seems like build-libraries is really failing a lot recently @ryanking13  =(

**Comment by ryanking13** [comment]
> Hmm seems like build-libraries is really failing a lot recently @ryanking13 =(

Yes =(. I'll work on unvendoring recipes (https://github.com/pyodide/pyodide/pull/4987) after 0.27 release.

**Comment by hoodmane** [comment]
Though this split doesn't quite work since you have to take deps into account.

**Comment by hoodmane** [comment]
Though this split doesn't quite work since you have to take deps into account.

**Comment by ryanking13** [comment]
Okay, then let's split the jobs first as we are getting too much timeouts these days. Let me work on it.

**Review by ryanking13 — APPROVED** [review]
Looks good to me. Could you resolve the merge conflict?

**Comment by riyavsinha** [comment]
Done! Thank you @ryanking13 and @hoodmane for the reviews :)

**Comment by ryanking13** [comment]
Thanks again @riyavsinha!

**Comment by ryanking13** [comment]
There is a failure in safari but it seems like it is upstream Selenium issue and it is already fixed (https://github.com/SeleniumHQ/selenium/pull/14699)

**Pull request merged**
