### PR TITLE
Package unvendored CPython stdlibs in wheel format

### PR DESCRIPTION
**Pull request by ryanking13**
### Description

Related: https://github.com/pyodide/pyodide/issues/4748

Packages all unvendored cpython modules in a wheel format, instead of using a custom zipfile.  Unvendored stdlibs are considered as a normal python package and installed in site-packages directory.

The package_type == 'cpython_module' still remains to distinguish it from normal packages (we are using it for custom import hook and in `fullstdlib` flag), but except for that, it works just like a normal python package.

__Possible Drawbacks__

1. Unvendored stdlibs now contain wheel metadata files. So packages like `importlib` wheel grap those metadata and consider it like a normal python package.
2. The installation directory for stdlibs is changed, previously `/lib/python3.12/`, now `/lib/python3.12/site-packages`.

### Checklists

- [x] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry
- [x] Add new / update outdated documentation
- [x] fix tests

### CODE REVIEW

**Comment by ryanking13** [comment]
https://github.com/pyodide/pyodide/pull/4911 will fix `build-test-pyc-packages` failure.

**Comment by ryanking13** [comment]
I think I can merge #4882 after merging this. @hoodmane could you review this when you have time?

**Review by hoodmane — APPROVED** [review]
This introduces a lot of extra duplicated code. But I guess it's alright. TH

**Comment by ryanking13** [comment]
Thanks for the review!

> This introduces a lot of extra duplicated code. But I guess it's alright.

Yes, it does, but I guess it won't increase the maintenance burden that much.

**Pull request merged**
