### PR TITLE
Another update of python-sat.

### PR DESCRIPTION
**Pull request by alexeyignatiev**
Hey guys, here is another version bump for the python-sat package. I fixed a couple of bugs in the toolkit, hence this update.

### Checklists

- [ ] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry
- [ ] Add / update tests
- [ ] Add new / update outdated documentation

### CODE REVIEW

**Comment by hoodmane** [comment]
@rth more oauth trouble

**Comment by hoodmane** [comment]
Interestingly @dcherian did not have this problem.

**Comment by alexeyignatiev** [comment]
What should be the source of the issue, @hoodmane?

**Comment by hoodmane** [comment]
I was hoping @rth would know...

**Comment by rth** [comment]
Sigh, looks like it's still not fixed. And I cannot reproduce it because if I push a commit apparently it uses my oauth token . 
I'll have a look tomorrow, sorry about that.

**Comment by hoodmane** [comment]
Okay I just triggered the CI myself. Sorry to keep you waiting on this @alexeyignatiev.

**Comment by alexeyignatiev** [comment]
No worries at all, @hoodmane! Thanks!

**Comment by hoodmane** [comment]
Thanks @alexeyignatiev!

**Comment by rth** [comment]
Yes, sorry for the delay. Opened https://github.com/pyodide/pyodide/issues/3492 about it. Short answer next time it happens @alexeyignatiev try to login into CircleCI. For now I don't have another solution.

**Comment by alexeyignatiev** [comment]
Thanks for the suggestion, @rth. I will definitely do it next time this happens.

**Pull request merged**
