### PR TITLE
Update coolprop to 6.6.0

### PR DESCRIPTION
**Pull request by dvd101x**
Updated the coolprop version and changed source according to https://github.com/pyodide/pyodide/pull/4028#issuecomment-1761751800

### Description

- Updated coolprop version to 6.6.0
- Changed source from sourceforge to pypi

### Checklists

- [x] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry
- [x] Add / update tests
- [x] Add new / update outdated documentation

### CODE REVIEW

**Comment by hoodmane** [comment]
Thanks @dvd101x!

**Comment by hoodmane** [comment]
You'll need to merge main to get #4396 which fixes the build.

**Comment by dvd101x** [comment]
Thanks! I did the merge and it seems to be working!

**Comment by dvd101x** [comment]
Hi Hood,

Thanks for the help with the merge suggestion.

Sadly I might need help on this one. I'm really new to this. Could you give me some pointers on my mistake?

**Comment by hoodmane** [comment]
> Error building sourmash.

Not sure, looks unrelated to you since sourmash doesn't depend on coolprop. I restarted the CI, hopefully it was a flake. If not a flake and there was a change outside of this repo that caused sourmash build to persistently fail, then you could try disabling sourmash to see what happens with coolprop.

**Comment by hoodmane** [comment]
Okay on rerun we get an actual failure:
```
FileNotFoundError: [Errno 2] No such file or directory:
'/root/repo/packages/coolprop/build/coolprop-6.6.0/wrappers/Python'
```
I guess when I get a chance I'll have to try to build it locally and see what happens. Did you build it locally and succeed or are you unable to do local builds?

**Comment by hoodmane** [comment]
I can reproduce the failure locally. It seems that Coolprop does some file rearrangement on its sdist when you run `setup.py` and somehow our build system isn't reproducing it properly. Maybe one of the Coolprop maintainers (@ibell or @jowr) could give us some guidance, or maybe comparing the build logs between building a native wheel and a Pyodide wheel will show the steps that we're missing.

**Comment by ryanking13** [comment]
Could you try removing these two line and see what happens?

https://github.com/pyodide/pyodide/blob/e586e7c0f267759ce47cab11dc283b2655953946/packages/coolprop/meta.yaml#L13-L14

The coolprop archive from Sourceforge and from PyPI have different structures. I guess the line above was to workaround for the Sourceforge archive so you might not need it for PyPI archive.

**Comment by dvd101x** [comment]
I tried removing the lines for setup.py but it seems to fail quicker.

I don't have a setup ready to reproduce locally, but there is also a newer version in sourceforge that I could try instead of the GitHub.

**Comment by hoodmane** [comment]
Most recent failure was in scikit-image with:
```
http.client.IncompleteRead: IncompleteRead(11534336 bytes read, 11186083 more
```
Which looks like another flake regarding some sort of failed http request unrelated to this PR. I don't know why we're getting so many failed requests on this PR, it's not usually very common.

**Comment by ryanking13** [comment]
The build was successful, but there are test failures. Could you check and fix the test failure?

**Comment by dvd101x** [comment]
It seems it was missing some sources as mentioned in here, had to revert back to sourceforge
https://github.com/CoolProp/CoolProp/issues/2305#issuecomment-1807998129

**Review by ryanking13 — APPROVED** [review]
Thanks!

**Pull request merged**
