### PR TITLE
Add `sisl` package

### PR DESCRIPTION
**Pull request by pfebrer**
### Description

This PR adds the [sisl](https://github.com/zerothi/sisl) package, a scientific package for electronic structure simulations. It would be very cool to have it on `pyodide` so that we can design a standalone web application with it.

The package has C and fortran sources and it is built with `scikit-build-core`. For now, I turned off the fortran functionality since it is only IO of fortran files, which probably would be complicated to make it work with the browser's virtual filesystem anyway (?).

I don't know how to add and check the tests, since when I run `pytest` from `pyodide`'s directory on the docker image package tests are skipped saying that the package is not built (it is in `dist` and also in `packages/sisl/dist`, and I get the error also for the other built packages). If someone could help me with that it would be great.

### Checklists

- [x] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry
- [x] Add / update tests
- [x] Add new / update outdated documentation

### CODE REVIEW

**Comment by hoodmane** [comment]
You have to say `PYODIDE_PACKAGES='tag:core,sisl' make -C packages`. That should fix the package not built problem.

**Comment by pfebrer** [comment]
I ran `PYODIDE_PACKAGES='tag:core,sisl' make -C packages` and I got (it seems everything went fine):

```
make: Entering directory '/src/packages'
mkdir -p /src/packages/.artifacts /src/packages/.libs
PYODIDE_ROOT=/src pyodide build-recipes \
"tag:core,sisl" \
--recipe-dir=./ \
--install \
--install-dir=../dist \
--metadata-files \
--n-jobs ${PYODIDE_JOBS:-4} \
--log-dir=./build-logs \
--compression-level "6"
The following packages are already built: Pillow, boost-cpp, cycler, distutils, 
fonttools, hashlib, kiwisolver, libf2c, liblzma, libtiff, libwebp, lzma,        
matplotlib, matplotlib-pyodide, micropip, numpy, openblas, openssl, packaging,  
pandas, pydecimal, pydoc_data, pyparsing, python-dateutil, pytz, scipy, sisl,   
six, sqlite3, ssl, test, tqdm, and xarray                                       
Building the following packages: Jinja2, MarkupSafe, atomicwrites, attrs,       
cpp-exceptions-test, exceptiongroup, fpcast-test, iniconfig, more-itertools,    
pluggy, py, pyodide-tblib, pytest, regex, setuptools, sharedlib-test, and       
sharedlib-test-py                                                               
[2/17] (thread 2) built py in 1s                                                
[1/17] (thread 1) built sharedlib-test in 2s                                    
[5/17] (thread 2) built setuptools in 2s                                        
[7/17] (thread 2) built exceptiongroup in 1s                                    
[4/17] (thread 4) built MarkupSafe in 6s                                        
[8/17] (thread 2) built pluggy in 1s                                            
[3/17] (thread 3) built fpcast-test in 6s                                       
[6/17] (thread 1) built atomicwrites in 5s                                      
[11/17] (thread 3) built iniconfig in 1s                                        
[13/17] (thread 3) built attrs in 1s                                            
[12/17] (thread 1) built cpp-exceptions-test in 1s                              
[15/17] (thread 1) built pyodide-tblib in 1s                                    
[14/17] (thread 3) built Jinja2 in 1s                                           
[9/17] (thread 4) built sharedlib-test-py in 5s                                 
[16/17] (thread 1) built more-itertools in 1s                                   
[17/17] (thread 3) built pytest in 1s                                           
[10/17] (thread 2) built regex in 17s                                           
                                                                                
Building packages... ━━━━━━━━━━━━━━━━━━━━━━━━━━ 17/17 100% Time elapsed: 0:00:23
Copying build logs to /src/packages/build-logs                                  
Copying built packages to /src/dist                                             
Writing pyodide-lock.json to /src/dist/pyodide-lock.json                        
make: Leaving directory '/src/packages'
```

Then `pytest -rs packages/sisl`:

```
============================= test session starts ==============================
platform linux -- Python 3.11.3, pytest-7.3.1, pluggy-1.0.0
benchmark: 4.0.0 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /src
configfile: pyproject.toml
plugins: benchmark-4.0.0, httpserver-1.0.6, asyncio-0.21.0, cov-4.0.0, hypothesis-6.75.2, pyodide-0.23.2
asyncio: mode=Mode.STRICT
collected 1 item                                                               

packages/sisl/test_sisl.py s                                             [100%]

============================== 1 skipped in 0.03s ==============================
pfebrer@966b13fddced:/src$ pytest packages/sisl/ -rs
============================= test session starts ==============================
platform linux -- Python 3.11.3, pytest-7.3.1, pluggy-1.0.0
benchmark: 4.0.0 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /src
configfile: pyproject.toml
plugins: benchmark-4.0.0, httpserver-1.0.6, asyncio-0.21.0, cov-4.0.0, hypothesis-6.75.2, pyodide-0.23.2
asyncio: mode=Mode.STRICT
collected 1 item                                                               

packages/sisl/test_sisl.py s                                             [100%]

=========================== short test summary info ============================
SKIPPED [1] ../usr/local/lib/python3.11/site-packages/pytest_pyodide/decorator.py: package 'sisl' is not built.
============================== 1 skipped in 0.03s ==============================
```

I get the same if I try to test any other package, this is not particular to `sisl`. E.g.: `pytest -rs packages/numpy` also says that `numpy` is not built, but it is.

**Comment by pfebrer** [comment]
Ok, solved it, sorry.  `pytest-pyodide` was not installed in the docker image

**Comment by ryanking13** [comment]
Thanks!

> Ok, solved it, sorry. pytest-pyodide was not installed in the docker image

Yes, the docker image has an old version of `pytest-pyodide` so you need to update it.

> Ok, this is ready! (unless CI says otherwise)

It looks like the tests are failing.

> I tried to pick the tests from the package that are the most important (depend on cython code). It still takes 1 minute and 43 seconds. Is it too much?

Well, it is not too much but it would be nice if you could make it run faster by picking a smaller set to test. If you would like to run full test suite, maybe you can run it in a separate repository like [scikit-learn](https://github.com/lesteve/scikit-learn-tests-pyodide)

**Comment by pfebrer** [comment]
Thanks for the tips! I reduced it to around 50 seconds. And the only failing tests now I think have nothing to do with `sisl` (?).

**Comment by rth** [comment]
You cannot build a wheel out of this package out of tree with `pyodide build` ?  The thing is with the current build system it's not really sustainable to add more and more specialized packages, as it increases the compile time for each commit and the maintenance effort later on.

**Comment by pfebrer** [comment]
Yeah I guess I can do it, I have not tried.

I had the impression that your goal was also to provide a centralized source of wheels for pyodide. Perhaps you could clarify somewhere in the docs which packages you want to include in the repo and which you don't. And also some general recommendation on what to do to make the package available for pyodide if it does not fit in the main distribution.

I guess I could store the produced wheel in some place like github releases, but it is very odd that users need to know the exact URL of a package to load it. Couldn't you at least store in the pyodide distribution links that point to wheels for extra packages so that `pyodide.loadPackage("extra-package")` knows where to find `extra-package`? 

E.g. an `external-packages.yaml` file that looked something like:

```yaml
package1: https://link-to-wheels-package1
package2: https://link-to-wheels-package2
...

```

**Comment by pfebrer** [comment]
I mean it seems like the best solution would be to make `pypi` accept `wasm` wheels, but I've seen a few posts with very few activity.

I don't understand why, since it seems it would lift a big weight off of `pyodide`'s shoulders because you wouldn't need to implement and maintain an alternative package manager.

**Comment by pfebrer** [comment]
I would be happy to just wait if you think the `pypi` path is possible in the short term :)

**Comment by hoodmane** [comment]
Maybe by the summer. I think it's fine to merge this as-is in the meantime.

**Comment by rth** [comment]
Sounds good. Thanks!

**Comment by pfebrer** [comment]
Cool, thanks! Looking forward to build it with `cibuildwheel`.

**Pull request merged**
