### PR TITLE
MAINT Update Chrome, Firefox and Selenium

### PR DESCRIPTION
**Pull request by rth**
Updates to,
 - Chrome 94
 - Firefox 94
 - Selenium 4.0.0

### CODE REVIEW

**Comment by ryanking13** [comment]
I guess `cffi` test failure that we are experiencing recently can be resolved by updating chrome version.
(I'm not 100% sure but I am not experiencing this error when I run tests with chrome v98 with playwright framework)

@rth Do you mind if I continue this PR, if you are busy? Are there some blockers?

**Comment by rth** [comment]
Yes, sure feel free to take it over @ryanking13 Thanks!

**Comment by hoodmane** [comment]
> I guess `cffi` test failure that we are experiencing recently can be resolved by updating chrome version.

I think so too. Thanks for working on this @ryanking13! I tried to work on it but I got frustrated before I made any real progress.

**Comment by rth** [comment]
Closing in favor of https://github.com/pyodide/pyodide/pull/2152

**Pull request closed without merging**
