### PR TITLE
updated pyb2d version

### PR DESCRIPTION
**Pull request by DerThorsten**
### Description
Updated pyb2d from 0.4 to 0.7.2

### Checklists

- [x] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry
- [x] Add / update tests (tests are still fine, no need for update)
- [x] Add new / update outdated documentation (nothing outdated, no need for changes)

### CODE REVIEW

**Comment by hoodmane** [comment]
Pydantic seems to have a missing dependency on typing_extensions.

**Comment by DerThorsten** [comment]
I was a bit surprised that pure python dependencies need to be added…

**Comment by DerThorsten** [comment]
@hoodmane  this seems to be good to go, the errors in the ci (https://app.circleci.com/pipelines/github/pyodide/pyodide/3386/workflows/03d5a682-8a81-4824-9894-0381902cc68e/jobs/36251) seem unrelated to my changes.
Nevertheless I triggered an empty commit to rerun the CI

**Comment by DerThorsten** [comment]
and again....

**Comment by DerThorsten** [comment]
jay, green light =)

**Review by rth — APPROVED** [review]
Thanks @DerThorsten !

**Comment by DerThorsten** [comment]
looking forward to a new release!
Just FYI with pyb2d one can do [such things](https://pyb2d.github.io/pyb2d/auto_examples/index.html) in the browser with jupyterlite

**Comment by rth** [comment]
> Just FYI with pyb2d one can do such things in the browser with jupyterlite

Very nice indeed! The readme and the documentation could use a more detailed description as after skimming through it I'm still not sure how it does what it does :)  The sphinx gallery examples are pure JS, right? It doesn't look like you are loading pyodide there unless I missed it?

**Pull request merged**
