### PR TITLE
Fix Pillow JPEG encode/decode error

### LINKED ISSUE #1201: TST test_pillow fails on Chrome
Following the update to the upstream emscripten backend https://github.com/iodide-project/pyodide/pull/1102 test_pillow seems now to fail consistently on chrome,

```
pytest packages/pillow/test_pillow.py -v -k chrome
```
currently produces for me locally,

```
__________________________________________________________________________________________ test_pillow[chrome] __________________________________________________________________________________________
Error running function in pyodide

RuntimeError: memory access out of bounds
    at jpeg_fdct_1x1 (<anonymous>:wasm-function[413]:0x51fe7)
    at dynCall (http://127.0.0.1:44693/pyodide.asm.js:9:390707)
    at http://127.0.0.1:44693/pyodide.asm.js:9:176868
    at obj.<computed> (http://127.0.0.1:44693/pyodide.asm.js:9:181678)
    at ImagingJpegEncode (<anonymous>:wasm-function[999]:0x9e6f1)
    at byn$fpcast-emu$ImagingJpegEncode (<anonymous>:wasm-function[1580]:0xb005f)
    at __static_309 (<anonymous>:wasm-function[687]:0x7a227)
    at byn$fpcast-emu$__static_309 (<anonymous>:wasm-function[2022]:0xb1b04)
    at __static_235 (http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[938]:0x1cf4f4)
    at byn$fpcast-emu$__static_235 (http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[23410]:0x6be5b4)
    at http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[2794]:0x2a9cfb
    at _PyEval_EvalFrameDefault (http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[2787]:0x2a714c)
    at byn$fpcast-emu$_PyEval_EvalFrameDefault (http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[17241]:0x6a81b1)
    at _PyEval_EvalCodeWithName (http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[2783]:0x2a1f40)
    at _PyFunction_Vectorcall (http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[799]:0x1c6713)
    at byn$fpcast-emu$_PyFunction_Vectorcall (http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[16478]:0x6a56b1)
    at http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[2794]:0x2a9cfb
    at _PyEval_EvalFrameDefault (http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[2787]:0x2a712c)
    at byn$fpcast-emu$_PyEval_EvalFrameDefault (http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[17241]:0x6a81b1)
    at PyEval_EvalFrameEx (http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[2786]:0x2a2179)
    at http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[798]:0x1c658d
    at _PyFunction_Vectorcall (http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[799]:0x1c6688)
    at byn$fpcast-emu$_PyFunction_Vectorcall (http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[16478]:0x6a56b1)
    at http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[2794]:0x2a9cfb
    at _PyEval_EvalFrameDefault (http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[2787]:0x2a71a7)
    at byn$fpcast-emu$_PyEval_EvalFrameDefault (http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[17241]:0x6a81b1)
    at _PyEval_EvalCodeWithName (http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[2783]:0x2a1f40)
    at _PyFunction_Vectorcall (http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[799]:0x1c6713)
    at byn$fpcast-emu$_PyFunction_Vectorcall (http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[16478]:0x6a56b1)
    at __static_187 (http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[846]:0x1c8fe8)
    at byn$fpcast-emu$__static_187 (http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[23362]:0x6be338)
    at http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[2794]:0x2a9cfb
    at _PyEval_EvalFrameDefault (http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[2787]:0x2a71eb)
    at byn$fpcast-emu$_PyEval_EvalFrameDefault (http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[17241]:0x6a81b1)
    at PyEval_EvalFrameEx (http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[2786]:0x2a2179)
    at http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[798]:0x1c658d
    at _PyFunction_Vectorcall (http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[799]:0x1c6688)
    at byn$fpcast-emu$_PyFunction_Vectorcall (http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[16478]:0x6a56b1)
    at http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[2794]:0x2a9cfb
    at _PyEval_EvalFrameDefault (http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[2787]:0x2a71a7)
    at byn$fpcast-emu$_PyEval_EvalFrameDefault (http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[17241]:0x6a81b1)
    at _PyEval_EvalCodeWithName (http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[2783]:0x2a1f40)
    at PyEval_EvalCode (http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[2782]:0x2a130f)
    at __static_1144 (http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[2727]:0x29e9f7)
    at byn$fpcast-emu$__static_1144 (http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[24319]:0x6c1529)
    at __static_684 (http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[1656]:0x20c860)
    at byn$fpcast-emu$__static_684 (http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[23859]:0x6bfd03)
    at http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[2794]:0x2a9cfb
    at _PyEval_EvalFrameDefault (http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[2787]:0x2a71a7)
    at byn$fpcast-emu$_PyEval_EvalFrameDefault (http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[17241]:0x6a81b1)
    at PyEval_EvalFrameEx (http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[2786]:0x2a2179)
    at http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[798]:0x1c658d
    at _PyFunction_Vectorcall (http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[799]:0x1c6688)
    at byn$fpcast-emu$_PyFunction_Vectorcall (http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[16478]:0x6a56b1)
    at http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[2794]:0x2a9cfb
    at _PyEval_EvalFrameDefault (http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[2787]:0x2a714c)
    at byn$fpcast-emu$_PyEval_EvalFrameDefault (http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[17241]:0x6a81b1)
    at _PyEval_EvalCodeWithName (http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[2783]:0x2a1f40)
    at _PyFunction_Vectorcall (http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[799]:0x1c6713)
    at byn$fpcast-emu$_PyFunction_Vectorcall (http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[16478]:0x6a56b1)
    at PyVectorcall_Call (http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[794]:0x1c5eee)
    at PyObject_Call (http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[795]:0x1c5fa9)
    at _pyproxy_apply (http://127.0.0.1:44693/pyodide.asm.wasm:wasm-function[388]:0x1a5197)
    at Function.apply (http://127.0.0.1:44693/pyodide.asm.js:9:170980)
    at Object.apply (http://127.0.0.1:44693/pyodide.asm.js:9:174424)
    at run (eval at executeAsyncScript (:457:5), <anonymous>:5:64)
    at eval (eval at executeAsyncScript (:457:5), <anonymous>:8:40)
    at eval (eval at executeAsyncScript (:457:5), <anonymous>:24:15)
    at eval (eval at executeAsyncScript (:457:5), <anonymous>:25:12)
    at executeAsyncScript (<anonymous>:457:26)
    at <anonymous>:473:29
    at callFunction (<anonymous>:361:33)
    at <anonymous>:371:23
    at <anonymous>:372:3
```

or alternatively it times out in other CI runs. 

**Edit:** This in particular appears to be related to the following code snippet,
```py
    with io.BytesIO() as asjpg:                                         
        img.save(asjpg, format="JPEG")
``` 

the error in https://github.com/iodide-project/pyodide/pull/1198#issuecomment-774662148 is likely relevant.

### LINKED ISSUE #1781: Convert (JPEG) PIL image to NumPy array
Hi everyone!

I am having issues with the PIL Image to NumPy array conversion when the original image comes from a JPEG file. The code

    from PIL import Image
    import numpy as np
    
    image = Image.open("image.jpg")
    array = np.array(image)

generates an array whose shape is `()` and dtype is `object`, instead of something like `(480, 640, 3)` and `dtype('uint8')`.

The complete executable example is available here: https://starboard.gg/nb/ntZSsIp

Any idea what the issue could be?

Cheers,

SB

### PR DESCRIPTION
**Pull request by ryanking13**
This PR fixes JPEG encode/decode errors in python pillow module.

See: #1817

Closes #1201

**Edit:** Related #1781, #1632 (I'll close them manually after checking that the issue is fixed there).

### CODE REVIEW

**Review by rth — COMMENTED** [review]
Thanks @ryanking13 ! Could you please confirm that this resolves minimal example in https://github.com/pyodide/pyodide/issues/1632#issuecomment-856204831 ?

**Comment by rth** [comment]
Also please add a [changelog](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry.

**Comment by hoodmane** [comment]
It would be nice to add tests for imsave and imread even.

**Comment by ryanking13** [comment]
>  Could you please confirm that this resolves minimal example in #1632 (comment)?

The example in the comment still invokes an error.

image

RGB image works fine, while grayscale image generates an error.
I'll investigate more about this.

**Comment by rth** [comment]
We can address that in a separate PR. This just needs a changelog entry and we can merge it. Fixing the test is already very useful.

**Review by rth — APPROVED** [review]

**Comment by ryanking13** [comment]
Alright, I'll make a separate PR for it!

**Pull request merged**
