### PR TITLE
Update changelog about runPythonAsync

### PR DESCRIPTION
**Pull request by hugeen**

### CODE REVIEW

**Comment by hugeen** [comment]
I don't know if this is right, I'm kinda new with PRs

**Comment by hoodmane** [comment]
@rth there is also no changelog entry for 0.17.0 about the `globals` argument in `runPython`. Should we add one in 0.17.0 while we're at it?

**Comment by hoodmane** [comment]
Thanks @hugeen!

**Review by rth — APPROVED** [review]
Thanks @hugeen !

**Pull request merged**
