### PR TITLE
PKG add wordcloud

### LINKED ISSUE #3169: Add wordcloud package
## 🐍 Package Request

- Package Name and Version : wordcloud / latest
- Package URL : https://github.com/amueller/word_cloud
- Package Dependencies that needs to be resolved first: N/A

### PR DESCRIPTION
**Pull request by eagleoflqj**
### Description

Closes #3169
### Checklists

- [x] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry
- [x] Add / update tests

### CODE REVIEW

**Review by ryanking13 — APPROVED** [review]
Thanks @eagleoflqj! It looks good to me. I'm not sure what the CI failure is about. Could you push an empty commit to re-trigger the CI just in case?

**Comment by ryanking13** [comment]
Hmm... It seems like the CI is still not running. Could you "Please sign out of CircleCI and log back in with your VCS before triggering a new pipeline" as the error message says?

**Comment by eagleoflqj** [comment]
Circle CI refused to test all 3 commits authored by me. Only the one by pre-commit is tested.
Though, I don't think it an issue on my side. I don't have Circle CI logged in.
As the last 2 commits don't have code change, I think success of https://github.com/pyodide/pyodide/pull/3173/commits/5cc2fb3a7886625c709b9f497cc50e384955c78f could be a green light for this PR.

**Comment by ryanking13** [comment]
>  I think success of [5cc2fb3](https://github.com/pyodide/pyodide/commit/5cc2fb3a7886625c709b9f497cc50e384955c78f) could be a green light for this PR.

Yes, CI success in that commit by pre-commit bot can prove that this PR works. I was just curious why CircleCI keeps complaining. Thanks @eagleoflqj!

**Pull request merged**
