### PR TITLE
JSPI Improve support for runtimes that don't allow dynamic eval

### PR DESCRIPTION
**Pull request by hoodmane**
This fixes it so that if `new WebAssembly.Module` fails, we don't try to use it in JSPI. This doesn't 100% fix no-dynamic-eval but it makes it work a lot better.

- [x] Add / update tests

### CODE REVIEW

**Review by ryanking13 — COMMENTED** [review]
Thanks @hoodmane! However, the test you added didn't seem to pass the CI?

**Comment by hoodmane** [comment]
It passes:
```
test_syncify.py::syncify_not_supported2[chrome] PASSED
test_syncify.py::syncify_not_supported2[firefox] PASSED
```
There was a flake on Safari but it's unrelated.

**Comment by ryanking13** [comment]
> There was a flake on Safari but it's unrelated.

Could you please double-check that this is a flake on Safari? It seems to be failing consistently from what I can see, with the following error message:

```
wasm instantiation failed!
```

**Comment by hoodmane** [comment]
Oh, interesting. I don't have a way to test things on Safari so we can just xfail it there.

**Comment by hoodmane** [comment]
Ah I added a comment here:
```js
// Note: only will work with newer runtimes that have WebAssembly.Function
```
Probably the trouble is that our safari doesn't have `WebAssembly.Function`.

**Pull request merged**
