### PR TITLE
Do not strip -shared flag

### PR DESCRIPTION
**Pull request by ryanking13**
I think it is no more required and is malfunctioning in #2892

### CODE REVIEW

**Comment by hoodmane** [comment]
But if emscripten sees the shared flag all it does is strip it and print a warning that it is ignoring it right?

**Comment by hoodmane** [comment]
Though if it doesn't cause extra warnings then this is an improvement since it reduces the amount of logic in pywasmcross.

**Comment by ryanking13** [comment]
> But if emscripten sees the shared flag all it does is strip it and print a warning that it is ignoring it right?

It seems like the behavior of emcc [differs when there exists a `-shared` flag or not](https://github.com/emscripten-core/emscripten/blob/d947b506149902497628c3114dbb89e50ee12c0a/emcc.py#L1669-L1679), which is what I think is happening in #2892. `libz3.so` needs to be an object file, but it currently emits JavaScript code since we strip `-shared` flag.

```
- The default output format is now executable JavaScript.  Previously we would
  default to output objecting files unless, for example, the output name ended
  in `.js`.  This is contrary to behaviour of clang and gcc.  Now emscripten
  will always produce and executable unless the `-c`, `-r` or `-shared` flags
  are given.  This is true even when the name of the output file ends in `.o`.
  e.g, `emcc foo.c -o foo.o` will produce a JavaScript file called `foo.o`.
  This might surprise some users (although it matches the behavior of existing
  toolchains) so we now produce a warning in this case.
```

**Comment by tiran** [comment]
Python 3.11 builds shared extensions with ``-shared -sSIDE_MODULE=1``. It works fine with Emscripten 3.1.x.

**Pull request merged**
