### PR TITLE
Backports for v0.21.3

### PR DESCRIPTION
**Pull request by hoodmane**
Reminder to self: merge this, don't squash!

### CODE REVIEW

**Comment by rth** [comment]
Thanks for doing this release!

**Comment by hoodmane** [comment]
This time I actually got the sqlite fix.

**Comment by hoodmane** [comment]
> pytest: error: argument --rt/--runtime: invalid choice: 'src' (choose from 'firefox', 'chrome', 'safari', 'node', 'host', 'firefox-no-host', 'chrome-no-host', 'safari-no-host', 'node-no-host')

Are we not pinning the version of `pytest-pyodide`?!

**Comment by rth** [comment]
+1 to pin to pytest-pyodide to the minor version but leave the patch release unconstrained (e.g. `v0.21.*`) so we can do other bug fixes if necessary.

**Comment by hoodmane** [comment]
Though I'm not sure that that is the problem. For instance:
```
tools/pytest_wrapper.py \
  --junitxml=test-results/junit.xml \
  --verbose \
  --durations 50 \
  --runtime chrome packages/*/test* \
  -o cache_dir=$CACHE_DIR
```
Causes the error:
```
pytest: error: argument --rt/--runtime: invalid choice: 'packages/Jinja2/test_jinja2.py' (choose from 'firefox', 'chrome', 'safari', 'node', 'host', 'firefox-no-host', 'chrome-no-host', 'safari-no-host', 'node-no-host')
```

**Comment by hoodmane** [comment]
Oh we need some `=` signs.

**Pull request merged**
