### PR TITLE
Bump `crc32c` to version 2.7.1

### PR DESCRIPTION
**Pull request by agriyakhetarpal**
### Description

This PR bumps [`crc32c`](https://pypi.org/project/crc32c/) to the latest available version, 2.7.1. I'm updating this in accordance with https://github.com/zarr-developers/numcodecs/pull/529, where we previously added this package in-tree (#4787, #4789), but they are requiring a later version now. The package has no dependencies that need to be updated or otherwise.

### Checklists

- [x] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry
- [ ] Add / update tests

### CODE REVIEW

**Comment by agriyakhetarpal** [comment]
I also planned to add https://github.com/LLNL/zfp (`zfpy`) but they don't have a source distribution available on PyPI yet: https://pypi.org/project/zfpy/#files. It is a dependency for `numcodecs`, albeit not a required one (but still good enough to test for). Should I create a dummy sdist for it, or perhaps we can experiment with the GitHub tarball until I request that they publish one for the next release? Adding the package would also block #4925, though, because they don't support NumPy v2 yet (https://github.com/LLNL/zfp/issues/210), but there's a chance it might just work. I'll comment on that issue about both of these aspects. In the meantime, bumping just `crc32c` would here should suffice for `numcodecs`, since it seems to be required for the test suite (the tests that use it are not skipped), even though it's listed as an optional dependency.

**Comment by agriyakhetarpal** [comment]
I also planned to add https://github.com/LLNL/zfp (`zfpy`) but they don't have a source distribution available on PyPI yet: https://pypi.org/project/zfpy/#files. It is a dependency for `numcodecs`, albeit not a required one (but still good enough to test for). Should I create a dummy sdist for it, or perhaps we can experiment with the GitHub tarball until I request that they publish one for the next release? Adding the package would also block #4925, though, because they don't support NumPy v2 yet (https://github.com/LLNL/zfp/issues/210), but there's a chance it might just work. I'll comment on that issue about both of these aspects. In the meantime, bumping just `crc32c` would here should suffice for `numcodecs`, since it seems to be required for the test suite (the tests that use it are not skipped if it isn't available), even though it's listed as an optional dependency.

**Review by ryanking13 — APPROVED** [review]
Thanks!

**Comment by agriyakhetarpal** [comment]
Thanks for the review!

**Pull request merged**
