### PR TITLE
Reduce pyodide.asm.js by factor of 2 with sed

### PR DESCRIPTION
**Pull request by hoodmane**
I stripped out C++ names with:
`sed -i 's/var __ZN[1KS][^;]*;//g' build/pyodide.asm.js`

Turns out that reduces pyodide.asm.js from 3.6Mb to 1.9Mb.

### CODE REVIEW

**Comment by rth** [comment]
Cool! Note however that `pyodide.asm.js` is only 361 KB once compressed (see the network tab when loading the REPL from the CDN). So large files locally are not necessarily large to download. It would still take time to process them I imagine though.

**Comment by rth** [comment]
Could you add a comment how you deteremined which symbols to strip please as well?

**Comment by hoodmane** [comment]
@rth How do I tell how big something will be from the CDN?

**Comment by hoodmane** [comment]
240K now brotli compressed using defaults: `brotli build/pyodide.asm.js`. 120kb isn't as exciting as 1.8MB but it's still something.

**Comment by rth** [comment]
It's the "Transferred" column if you click on "Disable cache",

image

and yes `brotli` applied to that file.

**Comment by rth** [comment]
> 120kb isn't as exciting as 1.8MB but it's still something.

Absolutely, I may not be download time so much, but I imagine parsing 1.8MB of JS still takes time. So it's good to reduce it.

**Comment by hoodmane** [comment]
In any case it's much lower hanging fruit to cut down `pyodide.asm.js` because it's a text file.

**Pull request merged**
