### PR TITLE
API Rework _base.py and console.py

### LINKED ISSUE #1516: InteractiveConsole API is not ready for public use
Trying to subclass the `InteractiveConsole` from `pyodide.console`, it looks like the signature of the `runcode` method might be misleading.

With `0.17.0a2`, the parameter `code` would be pass to the parent for execution and be taken into account:

https://github.com/pyodide/pyodide/blob/afb522ed59a08dc7edd0ae7935ec2999d55ed544/src/pyodide-py/pyodide/console.py#L228

With the latest (fetching from https://pyodide-cdn2.iodide.io/dev/full/pyodide.js), it doesn't seem to be the case anymore with the `code` parameter being ignored:

https://github.com/pyodide/pyodide/blob/60100c8fc66d3acffdca79e6ff3f1d4dd2200a09/src/pyodide-py/pyodide/console.py#L212-L225

Maybe the  `runcode` method could simply be replaced by the following?

```python
def runcode(self, code):
    self.run_complete = ensure_future(
        self.load_packages_and_run(self.run_complete, code)
    )
```

### PR DESCRIPTION
**Pull request by hoodmane**
Fixes #1516.
WIP.
Opening this now so I can put a link into v0.17.0 docs.

### CODE REVIEW

**Comment by rth** [comment]
Thanks for this works. 

That's a fairly large code diff and a number of backward compatible API changes. What's the motivation behind it aside from fixing https://github.com/pyodide/pyodide/issues/1516 ? For that issue we could very well say that `runcode` is not exposed and users have to use the `push` method otherwise.

**Comment by hoodmane** [comment]
This is just scratch work, usually I would put things back / select a subset of the changes that are actually good before opening a PR, but I want to link it in the docs.

**Comment by hoodmane** [comment]
But my motivation is to simplify the code and add features. In particular, I would like to be able to use the `_base` AST manipulation with `code.InteractiveConsole`, but without parsing the code twice and compiling it twice. I think the fact that we have to recompute a bunch of stuff is a sign of a poor design.

**Comment by hoodmane** [comment]
To avoid repeated compilation, we need something like the`parse_and_compile` method I've added here.

**Comment by hoodmane** [comment]
Two of the problems are:
1. `code.InteractiveConsole` doesn't pass through enough data
2. `eval_code` and `eval_code_async` are not very well designed

Together, 1 & 2 force pervasive use of class-scoped variables. Note that only instance of `InteractiveConsole` is expected to exist at most times, since `InteractiveConsole` is effectively a singleton so all of these class-scoped variables are actually global variables in disguise.

**Comment by hoodmane** [comment]
Another issue is that `InteractiveConsole` is too opinionated about output. When it gets a result or error, it should pass it directly to the user rather than automatically formatting a traceback or printing it. We should move the more opinionated part to a subclass.

**Comment by rth** [comment]
For functions that were added in this release, if you have concerns, it might be better to make them private before the release. That would make it more explicit that changes are likely in the future.

**Comment by hoodmane** [comment]
Working on that. `CodeRunner` and `InteractiveConsole` are not ready, I'm going to strip the docs and add a message.

`eval_code` and `eval_code_async` won't change their API, only implementation.

**Comment by rth** [comment]
> I'm going to strip the docs and add a message.

Making them private (e.g. `_InteractiveConsole`) and removing them from `__all__` so they are not part of the documentation might be better. In 0.16 we had only [1 function in console.py](https://github.com/pyodide/pyodide/blob/0d10cfaded5586ffc21ed38c7b2d392490871c6e/src/pyodide-py/pyodide/console.py)

**Comment by hoodmane** [comment]
Okay. (Actually docs unconditionally ignore things with a leading semicolon due to my monkeypatch.)

**Comment by rth** [comment]
Sounds good. Let me know if you need help there. I'd like to release so we can change the documentation links in the announcement post.

**Comment by hoodmane** [comment]
> Let me know if you need help there.

Yeah if you did it that would be good. As I said, I think it's just `InteractiveConsole` and `CodeRunner` that need to be private.

**Comment by hoodmane** [comment]
Wow, the way the Python REPL works is pretty darn janky:
<details>
<summary>Details</summary>

> Approach:
> 
> First, check if the source consists entirely of blank lines and
> comments; if so, replace it with 'pass', because the built-in
> parser doesn't always do the right thing for these.
> 
> Compile three times: as is, with \n, and with \n\n appended.  If it
> compiles as is, it's complete.  If it compiles with one \n appended,
> we expect more.  If it doesn't compile either way, we compare the
> error we get when compiling with \n or \n\n appended.  If the errors
> are the same, the code is broken.  But if the errors are different, we
> expect more.  Not intuitive; not even guaranteed to hold in future
> releases; but this matches the compiler's behavior from Python 1.4
> through 2.2, at least.

</details>

**Pull request closed without merging**
