### PR TITLE
 Automatic detection using podman

### PR DESCRIPTION
**Pull request by mokeyish**
### Description
If docker does not exist, podman is used instead.

### CODE REVIEW

**Comment by agriyakhetarpal** [comment]
The `awkward-cpp` build failure looks like it should be fixed by https://github.com/pybind/pybind11/pull/5301

**Review by ryanking13 — APPROVED** [review]
I never tried podman before TBH, but it looks okay to me.

**Review by agriyakhetarpal — COMMENTED** [review]
This looks good to me as well, but if we are to provide this, could we make `podman` an alternative CLI option instead of a fallback? It won't add any extra complexity, and something like `./run_docker --engine docker,podman` would be great (with the default being Docker).

**Comment by mokeyish** [comment]
> This looks good to me as well, but if we are to provide this, could we make `podman` an alternative CLI option instead of a fallback? It won't add any extra complexity, and something like `./run_docker --engine docker,podman` would be great (with the default being Docker).

Currently, docker is used by default, and podman will be tried only if docker does not exist. My personal preference is podman, because docker has permission vulnerabilities and is unsafe, so I basically won't install it.


I think automatic detection is good, adding an option to select manually is a bit troublesome.

**Review by agriyakhetarpal — APPROVED** [review]
That sounds good to me; thanks for the explanation, @mokeyish! Yes, I'm probably one of those who has both tools installed, but I guess there won't be many others. We can provide the choice of runtime if someone requests it.

**Pull request merged**
