### PR TITLE
DOC Add project roadmap

### PR DESCRIPTION
**Pull request by rth**
This is an initial draft/proposal for a Pyodide roadmap.

Clearly none of this constitutes a promise that it will be developed (as stated there), however it's useful to give a high level overview of things that could be improved for the upcoming 0.17 release (https://github.com/pyodide/pyodide/issues/1331).

As far as I can tell, missing from the current list are,
 - better Node.js integration (and generally JavaScript packaging)
 - improving the build setup

but we already have 7 points there, and maybe some of these could be merged together to have more general sections.

Feel free to push changes to this document directly.

cc @pyodide/core

### CODE REVIEW

**Comment by hoodmane** [comment]
> Feel free to push changes to this document directly.

I still haven't figured out how to do this from the git CLI, the push always fails.

**Comment by rth** [comment]
Just sent you an invite for my fork. Which should also allow you to restart/stop CI that runs there.

**Comment by rth** [comment]
Though you should be able to do it even without.
For me,
```
gh pr checkout #...
git commit -a
git push
```
works on PRs.

**Comment by rth** [comment]
Thanks for the improvements @hoodmane ! Good to merge? We can always iterate on it in the future.

**Comment by hoodmane** [comment]
> Good to merge?

Yeah, go ahead.

**Pull request merged**
