### PR TITLE
Ipython dep

### PR DESCRIPTION
**Pull request by mhochsteger**
Description
Fixes https://github.com/pyodide/pyodide/issues/4603

Duplicate/follow up to https://github.com/pyodide/pyodide/pull/4605, since @mkoeppe didn't react and I would like to see matplotlib working in the next pyodide/jupyterlite release.
I set the `maintainer` (myself) and `requirements` fields,

### CODE REVIEW

**Comment by mkoeppe** [comment]
Thanks for taking over! LGTM.

**Comment by hoodmane** [comment]
CI is mad that ipython and matplotlib-inline have a circular dependency.

**Comment by mhochsteger** [comment]
I added Ipython and matplotlib as dependencies because the import test won't work without it (see the original  PR). The upstream pip package only depends on traitlets (but makes no sense on it's own).
Is there a way to skip import tests for this package?

**Comment by mhochsteger** [comment]
The import tests are now running locally (matplotlib-inline import tests is not testing anything because `package.top-level` is not set).

It seems to me that the pipeline failures have nothing to do with the changes in this branch.

**Comment by mhochsteger** [comment]
@hoodmane I think it's now just unrelated tests that are failing. The circular dependency is fixed, and the import test for matplotlib-inline is skipped (as it's not working on its own). Is there anything else I can prepare/do?

**Pull request merged**
