### PR TITLE
FIX Handle EAGAIN when writing as well as when reading

### LINKED ISSUE #4089: New Pyodide fatal error in scipy tests: Error: EAGAIN: resource temporarily unavailable, write
This started to happen two days ago in https://github.com/lesteve/scipy-tests-pyodide, here is [a build log](https://github.com/lesteve/scipy-tests-pyodide/actions/runs/5946896593/job/16128148017).

The stack trace looks like this:
```
Error: EAGAIN: resource temporarily unavailable, write
    at Object.writeSync (node:fs:936:3)
    at ue.write (/home/runner/work/scipy-tests-pyodide/scipy-tests-pyodide/node_modules/pyodide/pyodide.asm.js:6566:23)
    at Object.write (/home/runner/work/scipy-tests-pyodide/scipy-tests-pyodide/node_modules/pyodide/pyodide.asm.js:6301:28)
    at Object.write (/home/runner/work/scipy-tests-pyodide/scipy-tests-pyodide/node_modules/pyodide/pyodide.asm.js:12457:46)
    at doWritev (/home/runner/work/scipy-tests-pyodide/scipy-tests-pyodide/node_modules/pyodide/pyodide.asm.js:19506:23)
    at _fd_write (/home/runner/work/scipy-tests-pyodide/scipy-tests-pyodide/node_modules/pyodide/pyodide.asm.js:19589:19)
    at write (wasm://wasm/025b4bda:wasm-function[9088]:0x45849f)
    at _Py_write (wasm://wasm/025b4bda:wasm-function[4144]:0x2d9eec)
    at _io_FileIO_write (wasm://wasm/025b4bda:wasm-function[6443]:0x39de9f)
    at _PyCFunctionWithKeywords_TrampolineCall (/home/runner/work/scipy-tests-pyodide/scipy-tests-pyodide/node_modules/pyodide/pyodide.asm.js:6855:33) {
  errno: -11,
  syscall: 'write',
  code: 'EAGAIN',
  pyodide_fatal_error: true
}
```

For some reason, it seems to happen right at the end of `scipy.special.tests` when pytest is printing its summary. In my experience, the timing of stdout vs stderr can not be fully trusted so maybe it happens in a test towards the end of scipy.special.tests. I'll be able to look into it more next week.

My wild guess is that this could be related to #4035?

### PR DESCRIPTION
**Pull request by hoodmane**
Fixes #4089.

@lesteve Does this fix the problem?

- [x] Add / update tests

### CODE REVIEW

**Comment by lesteve** [comment]
I am currently on holidays with a very spotty internet access, so I guess one way would be to merge and see if the next scheduled run of this [action](https://github.com/lesteve/scipy-tests-pyodide/actions/workflows/run-tests.yml) turns green.

If that doesn't sound acceptable, I'll be able to have a closer look next week.

**Comment by hoodmane** [comment]
That's acceptable. I'm pretty sure this is the solution. Hope you are having a good holiday!

**Comment by hoodmane** [comment]
But we'll have to see if I get around to it before next week...

**Review by ryanking13 — APPROVED** [review]
Thanks!

**Comment by lesteve** [comment]
I built this PR locally, and I can confirm this gets rid of the issue in https://github.com/lesteve/scipy-tests-pyodide.

What I noticed in case you want to add a test for this:
this happens for a test that fails and prints a lot of stuff (~100k lines of floating point differences)

I don't get the issue when running my js script with node (that essentially runs pytest inside Pyodide):
```
node scipy-pytest.js --pyargs scipy.special.tests.test_round
```

but I do get the issue when piping the process into `tee`:
```
node scipy-pytest.js --pyargs scipy.special.tests.test_round | tee test.log
```

**Comment by hoodmane** [comment]
Thanks for the investigation @lesteve! It sounds too complicated to reproduce organically, I think I'll just mock it.

**Comment by lesteve** [comment]
Great, thanks for the fix!

**Pull request merged**
