### PR TITLE
Update NumPy to 1.24.2

### PR DESCRIPTION
**Pull request by martinRenou**
### Description

Update NumPy.

Remove patches which were introduced in https://github.com/numpy/numpy/pull/21732 https://github.com/numpy/numpy/pull/21733 and https://github.com/numpy/numpy/pull/21894

### CODE REVIEW

**Comment by ryanking13** [comment]
Thanks, @martinRenou! It seems like galpy 1.8.1 is incompatible with numpy 1.24. Though it is already [fixed in upstream main branch](https://github.com/jobovy/galpy/commit/576f22c11d6c4c140771d14ca679ab3a885405cc).

@jobovy Hi, do you plan to release a new version of galpy soon?

**Comment by hoodmane** [comment]
Why don't we disable galpy for now? I'd like to see these patches removed.

**Comment by ryanking13** [comment]
Thanks, @jobovy!

@martinRenou Could you please merge the upstream main branch? I've just merged a PR upgrading galpy.

**Comment by martinRenou** [comment]
Rebased :)

**Comment by hoodmane** [comment]
Thanks again @martinRenou and @jobovy!

**Pull request merged**
