### PR TITLE
Add default_converter argument to to_py

### PR DESCRIPTION
**Pull request by hoodmane**
See the discussion with @oeway here: #2067.

This adds a new `default_converter` argument to `JsProxy.to_py` and `pyodide.toPy` which can be used to control the conversion of objects with no standard conversion. It can be used for instance to ensure that no `JsProxy`s are left over in the converted object, by just raising an error:
```py
def default_converter(_value, _ignored1, _ignored2):
    raise Exception("Object was not completely converted")
some_jsproxy.to_py(default_converter=default_converter)
```
If `default_converter` returns `None`, then `value` will be proxied. If you want to convert `Date` to `datetime` that can be done as follows:
```py
from datetime import datetime
def default_converter(value, _ignored1, _ignored2):
    if value.constructor.name == "Date":
        return datetime.fromtimestamp(d.valueOf()/1000)
```
If we have a pair class:
```js
class Pair {
    constructor(first, second){
        this.first = first;
        this.second = second;
    }
}
```
we can convert that as follows:
```py
def default_converter(value, convert, cache):
    if value.constructor.name != "Pair":
        return None
    result = []
    cache(value, result);
    result.append(convert(value.first))
    result.append(convert(value.second))
    return result
```
Note that this will handle self referential pairs correctly:
```js
const p = new Pair(0,0);
p.first = p;
```
will be converted to a list like:
```py
l = [0,0]
l[0] = l
```

### Checklist

- [x] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry
- [x] Add / update tests
- [x] Add new / update outdated documentation

### CODE REVIEW

**Comment by oeway** [comment]
Great feature!

Regarding "return None", maybe it's more intuitive to just return  the value? Then, if we return None, it means we want to encode the value as None. It seems the default JSONEncoder in python does this too. Are you try to make sure a converter without explicit return to work by default?

**Comment by hoodmane** [comment]
> Regarding "return None", maybe it's more intuitive to just return the value? Then, if we return None, it means we want to encode the value as None. It seems the default JSONEncoder in python does this too.

Yeah, that is a sensible suggestion.

**Comment by ryanking13** [comment]
Thanks, @hoodmane! Generally LGTM, except one thing to ask.

```python
def default_converter(_value, _ignored1, _ignored2):
    raise Exception("Object was not completely converted")
some_jsproxy.to_py(default_converter=default_converter)
```

The example you've provided above and the name `default_converter` and is somewhat misleading to me.

If it's a "default" converter, I think it should have a priority to default conversion rules like Array to list or Map to dict.
Otherwise, if the default conversion rules always precede, we probably need other name then a default_converter.

WDYT?

**Comment by hoodmane** [comment]
Well I can see how that's a bit confusing of a name but it is consistent with how the argument to `json.dumps` is named. Also I think default often means a fallback after trying other stuff.

Though rather than mimicking the `json.dumps` API another approach could be to mimick [`JSON.stringify`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#the_replacer_parameter).

**Comment by ryanking13** [comment]
> it is consistent with how the argument to `json.dumps` is named. Also I think default often means a fallback after trying other stuff.

Oh yes, that seems reasonable. Thanks for the explanation.

**Review by ryanking13 — APPROVED** [review]

**Comment by hoodmane** [comment]
> wouldn't it be better to have a global setting somewhere

Maybe. I'm good with including something like that if someone else wants to do it but I'm more interested in getting the basic feature set first. In the meantime people can define a helper function with the appropriate settings.

**Comment by hoodmane** [comment]
> So in practice what's the difference between, `some_jsproxy.to_py(default_converter=default_converter)` and `default_converter(some_jsproxy.to_py())` ?

Well the second thing only works on the outermost layer. This works for deep conversions (say you have an object where one of the values is a list of some class). It also can correctly handle reference loops -- see the last example I gave of a self referential `Pair`.

**Comment by rth** [comment]
OK, it's clear, thanks for the explanation. +1 then to add it as an argument first, and we can always some global settings to be able to modify the default value.

**Pull request merged**
