### PR TITLE
FIX Fix micropip version comparison with prerelease version

### LINKED ISSUE #2487: micropip didn't resolve package versions correctly
## 🐛 Bug

Hi, I am using micropip to installs two pure python packages, but got the error message complaining:
```
ValueError: Requested 'imjoy-rpc>=0.5.7', but imjoy-rpc==0.5.10a2 is already installed
```

### To Reproduce

```
Welcome to the Pyodide terminal emulator 🐍
Python 3.10.2 (main, May  4 2022 10:50:05) on WebAssembly VM
Type "help", "copyright", "credits" or "license" for more information.
>>> import micropip
>>> await micropip.install("imjoy-rpc==0.5.10a2")
>>> await micropip.install("imjoy-rpc>=0.5.7")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 192, in install
    transaction = await self.gather_requirements(
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 174, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 302, in add_requirement
    raise ValueError(
ValueError: Requested 'imjoy-rpc>=0.5.7', but imjoy-rpc==0.5.10a2 is already installed
```

### Expected behavior

When I run the second install command, it should know that the version is already satisfied and do nothing instead of generating an error.

### Environment

Latest version at https://pyodide-cdn2.iodide.io/dev/full/console.html

### PR DESCRIPTION
**Pull request by ryanking13**
### Description

Previously,

```py
await micropip.install("package==1.2.3a1")
await micropip.install("package>=1.0.0")  # Error: "Requested package>=1.0.0 but package==1.2.3a1 is already installed"
```

raised an error because package specifier ignores prerelease versions in default.

Fix #2487

### Checklists

- [x] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry
- [x] Add / update tests

### CODE REVIEW

**Review by hoodmane — APPROVED** [review]

**Comment by ryanking13** [comment]
> I'm not sure about enabling this by default, as pre-releases can contain bugs and be not ready for production. It would be better to add an option similar to `pip install --pre` to enable the installation of prereleases explicitly,

This PR doesn't make micropip find and install the prereleased version in default (which `pip install --pre` does).
It handles a situation when:

1) a prereleased version of a package is already installed
2) trying to install that package again, but it is already satisfied with installed prereleased version.

Actually, this is the same behavior of pip. For example, in pip:

```sh
pip install package==1.2.3a1
pip install package>=1.2.0  # ignored because 1.2.3a1 is already installed.
```

**Comment by ryanking13** [comment]
Oh, @rth you are right. It was installing prerelease versions in default... I'll fix it

**Comment by rth** [comment]
Thanks for checking! You are right that when the pre-release version is passed explicitly it shouldn't require enabling this flag.

**Comment by ryanking13** [comment]
Okay, I think it is working as expected now.

**Comment by ryanking13** [comment]
Maybe we can add `pre` argument for `micropip.install` in a separate PR.

**Pull request merged**
