### PR TITLE
MAINT Use target sysconfigdata rather than host sysconfigdata when cross compiling

### PR DESCRIPTION
**Pull request by hoodmane**
### Description

`sysconfig.py` uses the environment variable `_PYTHON_SYSCONFIGDATA_NAME` to decide where to look for the sysconfig data file with relevant info about the compile target. We also need to separately insure that our sysconfig data file is on the path. We don't want the rest of our target stdlib on the path, so I made an extra sysconfigdata folder, copied the sysconfig data into it, and put it on the path.

I think this will improve things. Currently we have some hacky work-arounds for sysconfigdata but I can't remember where they are.

### Checklists

- [x] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry

### CODE REVIEW

**Comment by hoodmane** [comment]
We see another "it skips the compiler wrappers" problem here: the Emscripten sysconfigdata has the absolute paths for `emcc`, `em++`, etc. On the other hand, the information is *much* more accurate than in the host sysconfigdata so it is possible that if we appropriately shape the sysconfigdata we could simplify pywasmcross a lot. Ideally we could figure out how to fill the sysconfigdata in with paths to our compiler wrappers. Using `emconfigure` makes it hard to avoid the absolute paths to the compiler. 

I suppose good one option would be to write a python script to manually update the sysconfigdata at the end of the CPython Makefile rather than having to mess around with `emconfigure`. Idealy we could eventually get things like pkgconfig to work so that packages could correctly determine the paths for libraries to link rather than us needing to fix them manually. Probably there will always be some need for rewriting compiler args here.

**Comment by ryanking13** [comment]
> Idealy we could eventually get things like pkgconfig to work so that packages could correctly determine the paths for libraries to link rather than us needing to fix them manually.

I recently started to work on installing libraries in a single path (#2516). It would be great if pkg-config or other similar things work so that we don't have to patch paths.

> On the other hand, the information is _much_ more accurate than in the host sysconfigdata so it is possible that if we appropriately shape the sysconfigdata we could simplify pywasmcross a lot

That sounds really great. pywasmcross is our bottleneck of package build, so it would be great if we can simplify (or in the future remove) it.

**Comment by ryanking13** [comment]
Thanks, @hoodmane!

> We also need to separately insure that our sysconfig data file is on the path. We don't want the rest of our target stdlib on the path

Could you explain a little more about why it has to be placed in a separate path and how it is related to #2449?

**Comment by hoodmane** [comment]
I think #2449 is unrelated: this probably won't make it any better or any worse.

We need a separate path for the `sysconfigdata` because we don't want to put an entire second copy of the Python stdlib on `sys.path`.  I think this could cause trouble. We are just trying to use a different `sysconfig`. The sysconfig data needs to be on the path, so this requires copying the sysconfig data to its own separate folder.

In any case I think this PR is only a very minor improvement. #2550 is significantly more important.

**Comment by rth** [comment]
Thanks! The approach sounds good. I wonder if we could re-use part of https://github.com/benfogle/crossenv for cross-compilation (which also fixes the [target sysconfig](https://github.com/benfogle/crossenv/blob/master/docs/intro.rst#how-it-works)) that is in particular used by conda-forge. Otherwise, it feels like we are re-inventing some of these things though maybe our use case is different enough.

**Review by rth — APPROVED** [review]
Thanks, LGTM.

**Pull request merged**
