### PR TITLE
Update GitHub Workflows Image Build and Support ghcr.io

### LINKED ISSUE #1851: Rate Limiting in Docker Hub: Alternative Container Registries for pyodide/pyodide
The [rate limiting](https://www.docker.com/increase-rate-limits) issues for Docker Hub is recently getting notorious, especially in multi-user environments. This clearly affects IPs which downloads more than 100 containers (any container in Docker Hub) over 240 minutes. The most severely affected are bare metal Kubernetes clusters and self-hosted CI runners.
GitHub Packages Container Repository (ghcr.io) and quay.io are the most representative alternatives which host unlimited free containers for public code repositories. Out of the two, ghcr.io will be easiest to work with.
It can be paired with free CIs that are also free for public code repositories without limitations in build minutes, which includes GitHub Actions & [Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/licensing/concurrent-jobs?view=azure-devops&tabs=ms-hosted), GitLab/GitGud Pipelines, Buildkite, Cirrus CI, Semaphore, Travis CI, and others. Peakflow.io free for private repositories. [Reference](https://github.com/ligurio/awesome-ci)
Out of these, GitHub Actions or Azure Pipelines would be easiest to use.

Will it be possible to add the containers to GitHub Packages Container Registry (ghcr.io) in addition to Docker Hub?

### PR DESCRIPTION
**Pull request by ehfd**
### Description

PR based on issue #1851. Implemented trigger to tags and upload to ghcr.io for pre-built docker image, and to the non-prebuilt images also.

Closes #1851.

### Checklists

- [x] Configure the credentials for GitHub Container Repository correctly (requires admin intervention)
- [x] Implement pyodide/pyodide-env
- [x] Q. Does this workflow require QEMU? In other words alternative architectures such as aarch64, s390x, or others.
- [x] @rth should test everything works on his own environment

The default checklists:

- [x] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry
- [x] Add new / update outdated documentation

### CODE REVIEW

**Comment by rth** [comment]
Thanks for working on this @ehfd !

> Q. Does this workflow require QEMU? In other words alternative architectures such as aarch64, s390x, or others.

For now, I would say no. We already need to have better support of different OSs at x86_64, before trying different architecture. On new Mac M1 CPU people can use x86_64 emulation if needed.

> should test everything works on his own environment

So I should try to create tags on my fork and check that it's deploying with this setup? Have you tested it on your fork?

**Comment by ehfd** [comment]
> So I should try to create tags on my fork and check that it's deploying with this setup? Have you tested it on your fork?

In [Line 47](https://github.com/pyodide/pyodide/pull/1995/commits/69596d7ffad16b1bd501728dd7e61a7ad3b4444a#diff-e0ed06ed167d42ded61bb8913c0f02d8a691900a916546329d70b7ae1a14e994R47) of `docker_image.yml` and [Line 48](https://github.com/pyodide/pyodide/pull/1995/commits/2e78633e646cada20860f67d05bafcf36fce6f8f#diff-149b5ed316fe416fbc693b2cda7f11aa0ea9a69a780b63dfdf45b3c8c03f8bceR48) of `prebuilt_docker_image.yaml`, which username and password to use is the issue. If there is a token for the pyodide group itself, it would be best, and that must be tested.

**Comment by rth** [comment]
There is https://github.com/pyodide-ci-bot which was created for such tasks. Thanks I'll look into it.

**Comment by ehfd** [comment]
> There is https://github.com/pyodide-ci-bot which was created for such tasks. Thanks I'll look into it.

Yep. I expect everything to succeed elsewise. By the way, please squash merge when the PR is getting merged.

**Comment by ryanking13** [comment]
Thanks for the PR! I think it would be nice if this workflow pushes to both Docker hub and GitHub registry since we are using docker hub for now.

After that, I think this PR is ready to be tested by maintainers and be merged? (@rth)

**Comment by rth** [comment]
Yes, it's on my to do list. I'll look into it before the next release.

**Comment by ehfd** [comment]
```
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
```

Like what was done here, after adding a secret,

```
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}
```
This should probably do it for GitHub, where `secrets.GHCR_USERNAME` is `pyodide-ci-bot`, and `secrets.GHCR_TOKEN` is generated from https://github.com/settings/tokens with `write:packages` permission.

**Comment by rth** [comment]
I tested this in an upstream branch https://github.com/pyodide/pyodide/tree/docker-gh-test, because I couldn't figure out how to run GH actions in my fork. So this means that credentials and overall workflow should be OK, however, I couldn't test the specific version input passed via git tags or manual trigger. I find it a bit confusing how to find GH package list at https://github.com/orgs/pyodide/packages, but likely because I'm not used to it.

Overall it looks good. 

I'll update the changelog/docs then merge. Thanks @ehfd, it will certainly make the release process easier !

**Comment by rth** [comment]
Manual trigger also works as expected https://github.com/pyodide/pyodide/actions/runs/1665407074

**Comment by ehfd** [comment]
Excellent!
Delighted to make a substantial contribution to this repository.

**Pull request merged**
