### PR TITLE
Make matplotlib output figures resizable

### LINKED ISSUE #40: Make output figures resizable
The matplotlib figures should be resizable with a little "handle", like in the WebAgg backend.

### PR DESCRIPTION
**Pull request by ashutoshbsathe**
Fixes pyodide/matplotlib-pyodide#15 

Here's a working example.
(Sorry for bad quality of recording, I don't have proper GPU on my machine)

I would like if someone tests this on their local machine first and then merge.
I've made sure that it works fine on all my devices, but still would make me confident if someone tries on their machine as well.

Oh, and I didn't remove the commented placeholder functions present [here](https://github.com/iodide-project/pyodide/blob/60977f0db8a2a6bf308851e6227c3d61b22f831d/packages/matplotlib/src/wasm_backend.py#L406). I thought I would wait till the maintainers give me green signal for the current design and then before final merge I will remove the placeholders

Please review

### CODE REVIEW

**Comment by mdboom** [comment]
Thanks for the PR!

There's one key thing missing here: this doesn't actually tell matplotlib what the new size of the figure is and let it resize it -- it's just resizing the image returned from matplotlib within the browser.  When you resize a figure in matplotlib, it changes the output dimensions, but it doesn't actually change the size of the elements within the plot, size as text size or line width.  Look carefully at how it works in Jupyter -- you'll see that when you resize a plot, the size of the text doesn't change, just their positions.

This will require calling `set_size_inches` on the figure when the mouse events resize the figure, and then making sure that the resulting image data coming matplotlib is actually *never* resized by the browser.

I hope this makes sense.  Don't hesitate to reach out here or on gitter if you have further questions.

**Comment by ashutoshbsathe** [comment]
Hi,

(Sorry for late reply)
Actually yes, I did implement my solution `set_size_inches`  but it seems that after a resize, my new dimensions for canvas aren't exactly same in inches and the resize always goes out of scale.

What possibly can cause this ? I know this has  something to do with dpi, currently I'm dividing my width and height with figure's own dpi. I will try to get dpi from canvas itself using `get_dpi_ratio` and get back soon !

**Comment by ashutoshbsathe** [comment]
So right now I'm getting the size of wrapper `div` as width, height. I'm multiplying them both by `self._ratio` followed by a division of `fig.dpi` as described [here](https://github.com/matplotlib/matplotlib/blob/bf464c36add4c00c7ee8a10f811856d4571f5df6/lib/matplotlib/backends/backend_webagg_core.py#L317).
This produces following result which does not scale well at all.
Resize GIF
We can however see that, matplotlib is resizing the plot, from the axes ticks getting changed on resize.

**Comment by mdboom** [comment]
Hmm...  I'm not sure, but it's probably some detail in the math of conversion from pixels to inches.  It's a little complicated by the way browsers handle high-resolution (retina) displays, which is what the `ratio` value is for.  Can you push the current version of your code?

**Comment by ashutoshbsathe** [comment]
Hi, @mdboom I've been long due to my exams and unavailability of my buildbox
In the meantime, I looked for pixel conversion formulae and it seems the current implementation is correct and inline with the matplotlib's implementation(```fig.dpi```)
Any other resources where I can look to fix this ?
Thanks (and sorry for being away for long time)

**Comment by rth** [comment]
Closing as the matplotlib backeds were moved to https://github.com/pyodide/matplotlib-pyodide. So if we still want it this PR should be moved to that repo.

**Pull request closed without merging**
