### PR TITLE
Add generic typing for `create_proxy`, `create_once_callable` and `JsDoubleProxy`

### LINKED ISSUE #4832: Wrong typing for `create_proxy` and `create_once_callable`
## 🐛 Bug

`create_proxy` is often used to register a callback to a JavaScript instance, like `addeventlistener` or `some_promise.then`, and `create_once_callable` is often used to decorate single-use functions.

So I think their biggest usage is **to decorate callables**. But the typing is wrong. A callable decorated with it lose all of its typing signatures, makes type checkers keep throwing false positive errors.

### To Reproduce

```py
from typing import reveal_type
from pyodide.ffi import create_once_callable

@create_once_callable
def f(x: int) -> int:
    return x

a = f(123)

reveal_type(a)
```

```sh
> mypy ./test.py
error: Too many arguments for "__call__"  [call-arg]
test.py:13: note: Revealed type is "Any"

> pyright ./test.py
error: Expected 0 positional arguments (reportCallIssue)
information: Type of "a" is "Unknown"
```

### Expected behavior

1. No error
2. The revealed type should be `int`

### Environment

- Pyodide Version: `0.26.0`
- Browser version: none
- Any other relevant information: none

### Additional context

I think it is easy to solve this by generic typing. Also since pyodide is already using 3.12 (and pyodide-py has a `requires-python = ">=3.12"`), we can use python3.12's new type syntax to do this elegantly.

<details><summary>Like this</summary>
<p>

```py
from typing import Callable

class JsCallable[**P, T](JsProxy):
    def __init__(self, obj: Callable[P, T]): ...
    def __call__(self, *args: P.args, **kwargs: P.kwargs) -> T: ...
```

Instead of

```py
from typing import Callable, Generic, ParamSpec, TypeVar

P = ParamSpec("P")
T = TypeVar("T")

class JsCallable(JsProxy, Generic(P, T)):
    def __init__(self, obj: Callable[P, T]): ...
    def __call__(self, *args: P.args, **kwargs: P.kwargs) -> T: ...
```

</p>
</details> 

But I just noticed that **PEP 695 generics** are not yet supported by `mypy` yet, so maybe I shouldn't use it.

### PR DESCRIPTION
**Pull request by CNSeniorious000**
### Description

Fix #4832 

Source:

```py
from typing import TypeVar, reveal_type

from pyodide.ffi import create_once_callable, create_proxy

T = TypeVar("T", int, float, str, list)


@create_once_callable
def f(x: T) -> T:
    return x * 2


reveal_type(f)
reveal_type(f(0.2))
reveal_type(f(""))
reveal_type(f([]))


@create_proxy
def g(x: T) -> T:
    return x * 2


reveal_type(g)
reveal_type(g(0.2))
reveal_type(g(""))
reveal_type(g([]))

reveal_type(g.unwrap())
```

<details><summary>Before this PR:</summary>
<p>

```sh
> mypy test.py
test.py:13: note: Revealed type is "_pyodide._core_docs.JsOnceCallable"
test.py:14: error: Too many arguments for "__call__"  [call-arg]
test.py:14: note: Revealed type is "Any"
test.py:15: error: Too many arguments for "__call__"  [call-arg]
test.py:15: note: Revealed type is "Any"
test.py:16: error: Too many arguments for "__call__"  [call-arg]
test.py:16: note: Revealed type is "Any"
test.py:24: note: Revealed type is "_pyodide._core_docs.JsDoubleProxy"
test.py:25: error: "JsDoubleProxy" not callable  [operator]
test.py:25: note: Revealed type is "Any"
test.py:26: error: "JsDoubleProxy" not callable  [operator]
test.py:26: note: Revealed type is "Any"
test.py:27: error: "JsDoubleProxy" not callable  [operator]
test.py:27: note: Revealed type is "Any"
test.py:29: note: Revealed type is "Any"
Found 6 errors in 1 file (checked 1 source file)
```

```sh
> pyright test.py
test.py:13:13 - information: Type of "f" is "JsOnceCallable"
test.py:14:13 - information: Type of "f(0.2)" is "Unknown"
test.py:14:15 - error: Expected 0 positional arguments (reportCallIssue)
test.py:15:13 - information: Type of "f("")" is "Unknown"
test.py:15:15 - error: Expected 0 positional arguments (reportCallIssue)
test.py:16:13 - information: Type of "f([])" is "Unknown"
test.py:16:15 - error: Expected 0 positional arguments (reportCallIssue)
test.py:24:13 - information: Type of "g" is "JsDoubleProxy"
test.py:25:13 - error: Object of type "JsDoubleProxy" is not callable
    Attribute "__call__" is unknown (reportCallIssue)
test.py:25:13 - information: Type of "g(0.2)" is "Unknown"
test.py:26:13 - error: Object of type "JsDoubleProxy" is not callable
    Attribute "__call__" is unknown (reportCallIssue)
test.py:26:13 - information: Type of "g("")" is "Unknown"
test.py:27:13 - error: Object of type "JsDoubleProxy" is not callable
    Attribute "__call__" is unknown (reportCallIssue)
test.py:27:13 - information: Type of "g([])" is "Unknown"
test.py:29:13 - information: Type of "g.unwrap()" is "Any"
6 errors, 0 warnings, 9 informations
```

</p>
</details>

<details open><summary>After this PR:</summary>
<p>

```sh
> mypy test.py
test.py:13: note: Revealed type is "_pyodide._core_docs.JsOnceCallable[[x: T`55], T`55]"
test.py:14: note: Revealed type is "builtins.float"
test.py:15: note: Revealed type is "builtins.str"
test.py:16: note: Revealed type is "builtins.list[Any]"
test.py:24: note: Revealed type is "_pyodide._core_docs.JsCallableDoubleProxy[[x: T`62], T`62]"
test.py:25: note: Revealed type is "builtins.float"
test.py:26: note: Revealed type is "builtins.str"
test.py:27: note: Revealed type is "builtins.list[Any]"
test.py:29: note: Revealed type is "def [T in (builtins.int, builtins.float, builtins.str, builtins.list[Any])] (x: T`69) -> T`69"
```

```sh
> pyright test.py
test.py:13:13 - information: Type of "f" is "JsOnceCallable[(x: T@f), T@f]"
test.py:14:13 - information: Type of "f(0.2)" is "float"
test.py:15:13 - information: Type of "f("")" is "str"
test.py:16:13 - information: Type of "f([])" is "list[Unknown]"
test.py:24:13 - information: Type of "g" is "JsCallableDoubleProxy[(x: T@g), T@g]"
test.py:25:13 - information: Type of "g(0.2)" is "float"
test.py:26:13 - information: Type of "g("")" is "str"
test.py:27:13 - information: Type of "g([])" is "list[Unknown]"
test.py:29:13 - information: Type of "g.unwrap()" is "(x: T@g) -> T@g"
0 errors, 0 warnings, 9 informations
```

</p>
</details>

### Checklists

- [ ] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry
- [x] Add / update tests

### CODE REVIEW

**Review by hoodmane — APPROVED** [review]
Thanks @CNSeniorious000 looks great. Can you add some tests that require the new code to typecheck correctly?

**Comment by CNSeniorious000** [comment]
Okay, you mean testing mypy behavior with pytest?

**Comment by CNSeniorious000** [comment]
I added a [`src/tests/test_static_typing.py`](https://github.com/pyodide/pyodide/pull/4833/files#diff-81d80a044175a3815a48d3db7c11eab4e4adb19a5441d68b61efe6390b0ece14) to run type checks in pytest

**Comment by ryanking13** [comment]
Cool, thanks @CNSeniorious000!

> The downside is that in order to use mypy in pytest, we need to either include mypy into requirements.txt or install mypy in each CI configs.

I think it is totally okay to add mypy into requirements.txt.

**Comment by CNSeniorious000** [comment]
It's strange that in the test mypy says `sys.last_exc`'s type is None, and [setting its value to an Exception is an [assignment] error](https://github.com/pyodide/pyodide/actions/runs/9350115369/job/25732905450#step:5:2363).
```
src/py/pyodide/_state.py:43: error: Incompatible types in assignment (expression has type "None", variable has type "BaseException")  [assignment]
  src/py/pyodide/_state.py:43: note: Error code "assignment" not covered by "type: ignore" comment
  src/py/pyodide/_state.py:43: error: Unused "type: ignore" comment  [unused-ignore]
  Found 2 errors in 1 file (checked 1 source file)
```

After I changed it as it suggests, pre-commit complains about [`sys` has no attribute `last_exc`](https://results.pre-commit.ci/run/github/122663163/1717419428.K4kSfu5PQA-ZOMRQ9yPQAQ):
```
src/py/pyodide/_state.py:43: error: Module has no attribute "last_exc"  [attr-defined]
src/py/pyodide/_state.py:43: note: Error code "attr-defined" not covered by "type: ignore" comment
src/py/pyodide/_state.py:43: error: Unused "type: ignore" comment  [unused-ignore]
Found 2 errors in 1 file (checked 184 source files)
```

**Comment by hoodmane** [comment]
We can stick a `type:ignore` there and move on with it. Maybe report it to the stdlib typeshed people if you like =)

**Comment by hoodmane** [comment]
Have you tried using `pytest-mypy-testing`? I used it here and I think it's quite nice.
https://github.com/hoodmane/ts-to-python/blob/main/mypy-tests/test_types.py

**Comment by CNSeniorious000** [comment]
> stick a `type:ignore` there and move on with it

No, because a plain `type:ignore` violates `[ignore-without-code]`.

The real problem is, the pre-commit's mypy insist that `sys.last_exc = None` violates `[attr-defined]` and native mypy think it violates `[assignment]`.

Apparently this is caused by pre-commit is using mypy `1.9.0`, which don't support python 3.12 yet. And `sys.last_exc` is support since Python 3.12.

So I ended up with upgrading mypy to `1.10.0` in `.pre-commit-config.yaml`

**Comment by hoodmane** [comment]
Thanks so much for solving this mypy puzzle I really struggle with these sorts of problems.

**Comment by CNSeniorious000** [comment]
I think `pytest-mypy-testing` is quite nice. It's absolutely more pythonic way to integrate mypy with pytest. The only downside is that it rely on mypy's stringified message.

Since `pytest-mypy-testing` is a string equality assertion under the hood, I think there may be a risk if mypy changes the stringify format format in the future. Of course locking mypy to `==1.10.0` can avoid this.

I am trying now.

**Comment by CNSeniorious000** [comment]
It seems `conftest.py` needs modifying, but I'm not very confident about how to resolve it.

The pytest error stack is like:

```
/opt/conda/envs/pyodide-env/lib/python3.12/site-packages/_pytest/runner.py:341: in from_call
    result: Optional[TResult] = func()
...
/opt/conda/envs/pyodide-env/lib/python3.12/site-packages/pluggy/_callers.py:98: in _multicall
    next(function_gen)  # first yield
conftest.py:217: in pytest_runtest_call
    for fixture in item._fixtureinfo.argnames:
E   AttributeError: 'PytestMypyTestItem' object has no attribute '_fixtureinfo'
============= short test summary info =============
FAILED test_static_typing.py::[mypy]test_create_proxy - AttributeError: 'PytestMypyTestItem' object has no attribute '_fixtureinfo'
FAILED test_static_typing.py::[mypy]test_generic - AttributeError: 'PytestMypyTestItem' object has no attribute '_fixtureinfo'
FAILED test_static_typing.py::[mypy]test_callable_generic - AttributeError: 'PytestMypyTestItem' object has no attribute '_fixtureinfo'
FAILED test_static_typing.py::[mypy]test_decorator_usage - AttributeError: 'PytestMypyTestItem' object has no attribute '_fixtureinfo'
FAILED test_static_typing.py::create_proxy - AttributeError: 'int' object has no attribute 'unwrap'
```

<details><summary>Source in test_static_typing.py:</summary>
<p>

```py
from typing import TypeVar

import pytest

from pyodide.ffi import JsDoubleProxy, JsPromise, create_once_callable, create_proxy


@pytest.mark.mypy_testing
def test_create_proxy():
    _: int = create_proxy(42).unwrap()


@pytest.mark.mypy_testing
def test_generic():
    async def _(a: JsPromise[int]) -> str:
        return await a.then(str)

    def _(b: JsDoubleProxy[str]) -> str:
        return b.unwrap()


@pytest.mark.mypy_testing
def test_callable_generic():
    T = TypeVar("T", int, float, str)

    def f(x: T) -> T:
        return x * 2

    _: tuple[int, str] = create_once_callable(f)(2), create_proxy(f)("")


@pytest.mark.mypy_testing
def test_decorator_usage():
    T = TypeVar("T")

    @create_once_callable
    def f(x: T) -> list[T]:
        return [x]

    _: list[tuple[int, str]] = f((int("1"), str(1)))
```

</p>
</details>

**Comment by hoodmane** [comment]
Why don't we merge this as is and you can work on this in a followup if you feel like it?

**Comment by CNSeniorious000** [comment]
Sounds good to me. This is not that important and can be address in the future when necessary.

**Comment by hoodmane** [comment]
Thanks @CNSeniorious000!

**Pull request merged**
