### PR TITLE
xarray v2023.09.0

### PR DESCRIPTION
**Pull request by kmuehlbauer**
### Checklists

- [ ] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry
- [ ] Add / update tests
- [ ] Add new / update outdated documentation

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
It would be great, if someone can have a look at the failing tests. I've no idea what's going on here and would appreciate any help and suggestions. Thanks!

**Comment by hoodmane** [comment]
Test failures are caused by #4128 and not related to this PR.

**Comment by hoodmane** [comment]
Thanks @kmuehlbauer!

**Comment by kmuehlbauer** [comment]
Thanks for looking into this @hoodmane.

**Pull request merged**
