### PR TITLE
orjson package

### PR DESCRIPTION
**Pull request by spicy-sauce**
### Description

This PR adds `orjson` package support, see more details in #1282.

### Checklists

This is my first PR, so if I missed something or did it wrong, please let me know and I'll update accordingly. 

- [x] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry
Let me know if I should add the orjson and where, wasn't sure if it should be listed under `Packages` section at this point. 
- [x] Add / update tests - per @hoodmane's request, I added `test_orjson.py`.
- [ ] Add new / update outdated documentation
Let me know if this should be updated and where.

### CODE REVIEW

**Comment by hoodmane** [comment]
Uh oh it fails to load with "cannot resolve symbol yyjson_alc_pool_init"...

**Comment by spicy-sauce** [comment]
Seems like an issue build issue, right? Will you delve into it? Thanks.

**Comment by ryanking13** [comment]
I looked into this a bit, and it seems that the problem is caused by the `-Z link-native-libraries=no` option.

orjson needs to link a native library (libyyjson.a), which is written in c, but because of the `-Z link-native-libraries=no` option, it won't link to it.

The Pyodide part is solved by resetting RUSTFLAGS with `export RUSTFLAGS=""`, but maturin sets the same option, so it should be overridden too.

@messense Hi, looking at the maturin code, it seems that [a user can overwrite the link-native-libraries option](https://github.com/PyO3/maturin/blob/66a1511f9c22e3549fb1caa580ae213864560225/src/compile.rs#L241-L244), but I wasn't able to do it. I tried 1) setting the RUSTFLAGS env variable and 2) adding the following config to .cargo/config.toml

```
[target.wasm32-unknown-emscripten]
rustflags = [
    "-Zlink-native-librarie=no",
]
```

but both didn't work. What is the correct way of setting the flag?

**Comment by ryanking13** [comment]
@hoodmane by the way, maybe we don't need to set RUSTFLAGS anymore if maturin sets the same flags?

**Comment by messense** [comment]
@ryanking13 I think that check in maturin is a bit wrong: https://github.com/PyO3/maturin/pull/1724

**Comment by ryanking13** [comment]
@messense Thanks for the prompt fix! I'll try this again when a new version of maturin is released.

**Comment by spicy-sauce** [comment]
> @messense Thanks for the prompt fix! I'll try this again when a new version of maturin is released.

They released a new version 3 weeks ago, is it relevant?
https://github.com/PyO3/maturin/releases/tag/v1.2.3

**Comment by spicy-sauce** [comment]
> @spicy-sauce
> 
> Yes, thanks for the ping.
> 
> It seems like adding the following in `orjson` meta.yaml works now.
> 
> ```yaml
> build:
>   script:
>     export RUSTFLAGS="-Z link-native-libraries=yes"
> requirements:
>   executable:
>     - rustup
> ```
> 
> Could you add this to the meta.yaml + sync upstream/main branch of Pyodide in this PR?

done

**Comment by hoodmane** [comment]
Thanks @spicy-sauce, @ryanking13, and @messense!

**Comment by spicy-sauce** [comment]
Any plans to release a new version with this anytime soon? 
Thanks.

**Comment by rth** [comment]
This PR was included in the 0.24.0 release.

**Pull request merged**
