### PR TITLE
Update to emscripten 2.0.24

### PR DESCRIPTION
**Pull request by hoodmane**

### CODE REVIEW

**Comment by rth** [comment]
Could you change it to "Draft status" if it's not fully working yet?

**Comment by hoodmane** [comment]
Right as you say we probably need to update chrome to get this to work.

**Comment by rth** [comment]
CI looked mostly good, aside from some failures in chrome-packages. Merged main in to include node tests.

**Comment by hoodmane** [comment]
There's some significant issue here that will require work to debug. Segfaults occurring in `PyModule_ExecDef` in chrome. I bet I could reproduce locally and try to use dwarf / the debugger...

**Pull request closed without merging**
