### PR TITLE
fpcast2

### PR DESCRIPTION
**Pull request by hoodmane**
A second, much simpler approach to handling the bad fpcasts.
There are only a few problematic call sites, so just patch call trampolines into the interpreter at these locations.

### CODE REVIEW

**Comment by ryanking13** [comment]
I'm very looking forward to seeing this PR merged. Thank you for your efforts! 👍

**Comment by hoodmane** [comment]
There is still the problem of it breaking Chrome CI to deal with...

**Comment by hoodmane** [comment]
Okay, I think this is in good shape now:
1. All tests pass on node and firefox
2. All chrome tests time out. I still have no clue why. I tested locally on Chrome 90.0.4430.24, the version we use in CI. It works fine.

**Comment by hoodmane** [comment]
Closed in favor of #2019.

**Pull request closed without merging**
