### PR TITLE
Add scikit-bio v0.5.8

### PR DESCRIPTION
**Pull request by sminot**
### Description

I would like to add a recipe for scikit-bio (https://scikit-bio.org/), which provides a number of extremely useful functions for bioinformatics.
Because the dependencies for scikit-bio largely mirror those for scikit-learn (which has already been built for Pyodide), I was hoping that this would be relatively straightforward.

### Checklists

- [x] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry
- [ ] Add / update tests
- [ ] Add new / update outdated documentation

### CODE REVIEW

**Comment by lesteve** [comment]
scikit-bio depends on requests which is not packaged inside Pyodide, see https://github.com/pyodide/pyodide/issues/398. I am not sure about the way forward, others may jump in with suggestions ...

Maybe (probably a bit naive) requests and pyodide-http could be packaged in Pyodide so that the requests package inside Pyodide kind of works?

For more context, in a Pyodide console you can do things like:
```py
import micropip
await micropip.install(['requests', 'pyodide-http'])

import requests
import pyodide_http
pyodide_http.patch_all()

url = 'https://cdn.jsdelivr.net/pyodide/v0.23.1/full/pyodide.js'
# this will work with some limitations e.g. CORS headers need to be set by the server
r = requests.get(url)
print(r.content[:1000])
```

**Comment by rth** [comment]
Moving `import requests` into the two methods that need it should be enough. That way it wouldn't fail at import time if requests is not installed, and we could treat it as an optional dependency. For using that functionality in Pyodide one could then indeed micropip install `pyodide-http` and `requests`. 

This can be done initially via [a patch in this PR](https://pyodide.org/en/stable/development/new-packages.html#generating-patches), but ideally yes, should be done upstream. It wouldn't have any impact on users outside of Pyodide.

**Comment by sminot** [comment]
Thank you for providing more helpful details, @rth, I really appreciate it.

I'm more than happy to patch upstream, but I'm afraid that I don't completely understand the change that I would make to the code so that the `requests` package is patched appropriately by the `pyodide_http.patch_all()` method. Is there an easy way to modify the code so that it will work equally within or outside of Pyodide?

**Comment by rth** [comment]
You don't need to do anything about that. Normally once one installs `requests` and `pydide-http` it should just work  after one runs `pyodide_http.patch_all()`. Or at least that's what `pydide-http`  promises, worth double checking in this particular casr.

The reason for the necessary change is that we currently can't specify  `requests` as a mandatory requirement in Pyodide. So scikit-bio needs to be importable even if requests is not installed https://github.com/pyodide/pyodide/issues/3876

**Comment by agriyakhetarpal** [comment]
Hi @sminot, is this PR still relevant to you? `requests` is now available with Pyodide – thinks should work smoothly, unless there are new dependencies that need to be added.

**Comment by sminot** [comment]
Thanks for checking in. This is no longer a pressing issue, especially with `requests` available. I'll close this out.

**Pull request closed without merging**
