### PR TITLE
Update geopandas to 0.13.2

### PR DESCRIPTION
**Pull request by hoodmane**
Geopandas 0.13 unblocks pandas 2.0, cf https://github.com/pyodide/pyodide/issues/3734#issuecomment-1695941255

- [ ] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry

### CODE REVIEW

**Comment by ryanking13** [comment]
I think I failed to update geopandas in #4088, but I didn't look at the error messages in detail.

**Comment by hoodmane** [comment]
I think shapely 2.0 is a known troublesome upgrade.

**Comment by ryanking13** [comment]
> I think shapely 2.0 is a known troublesome upgrade.

Right. I recently tried and failed because of some symbol issues in geos.

**Comment by rth** [comment]
But so CI is passing here (aside from MacOS which fails for unrelated reasons) unless I'm missing something? Let me sync with upstream to see if it's still OK.

**Comment by rth** [comment]
The only failed package test is bokeh on firefox. There are also safari CI failures, but those sound unrelated (also broken on main). So it should be OK to merge this, no?

**Comment by ryanking13** [comment]
Oh, indeed, it is passing CI. Based on my previous comment, it looks like I was getting an error... but I don't remember. Then let's merge and see what happens.

**Pull request merged**
