### PR TITLE
Disable python_solvespace due to CI failures

### PR DESCRIPTION
**Pull request by hoodmane**

### CODE REVIEW

**Comment by ryanking13** [comment]
@fuyb1992 We've temporarily disabled the python-solvespace due to the CI failure, could you please investigate?

**Comment by fuyb1992** [comment]
Puzzled, build-core faild since commit https://github.com/pyodide/pyodide/pull/2265 , which is before PKG ADD python_solvespace, and worked again after disable python_solvespace. Is there any clue that may help me investigating the build-core failing?

**Comment by hoodmane** [comment]
CircleCI was failing because of an expired ssh key, not related to `python_solvespace`. But `python_solvespace` was causing `build_package_no_numpy_dependency` failures on PRs.

**Comment by hoodmane** [comment]
Here's an example CI failure in the `python_solvespace` build:
https://app.circleci.com/pipelines/github/hoodmane/pyodide/2557/workflows/fa7837fa-fd20-421d-9d3e-1dd3a6f9f3f7/jobs/27605

**Comment by hoodmane** [comment]
The specific error is:
```sh
cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DM_PI=PI -D_USE_MATH_DEFINES -DISOLATION_AWARE_ENABLED -DLIBRARY -DEXPORT_DLL -D_CRT_SECURE_NO_WARNINGS -DUNIX_DATADIR=\"solvespace\" -Ipython_solvespace/include -Ipython_solvespace/src -Ipython_solvespace/extlib/mimalloc/include -Ipython_solvespace/extlib/mimalloc/src -I/tmp/build-env-l5uxtidc/include -I/usr/local/include/python3.10 -c python_solvespace/slvs.cpp -o build/temp.emscripten_wasm32-3.10/python_solvespace/slvs.o -O3 -Wno-cpp -g -Wno-write-strings -fpermissive -fPIC -std=c++17
em++: error: python_solvespace/slvs.cpp: No such file or directory ("python_solvespace/slvs.cpp" was expected to be an input file, based on the commandline arguments provided)
```

**Comment by fuyb1992** [comment]
Thanks @hoodmane, I will investigate this issue asap

**Pull request merged**
