### PR TITLE
Add docstring for pyfetch

### PR DESCRIPTION
**Pull request by Martolivna**
### Description

This adds docstring example for `pyodide.http.pyfetch`.

#1955 

### Checklists

- [x] Add new / update outdated documentation

### CODE REVIEW

**Review by rth — APPROVED** [review]
Thanks @Martolivna ! We just need to merge https://github.com/pyodide/pyodide/pull/4007 first which contains some code logic to skip running such tests in CI which will fix the current failure. Otherwise LGTM.

**Comment by rth** [comment]
@Martolivna Could you merge `upstream/main` here and add this exception to the list added in https://github.com/pyodide/pyodide/pull/4007 ? It should fix CI. Thanks!

**Comment by Martolivna** [comment]
Oh, sorry for the force-push, did it by accident :)

**Comment by Martolivna** [comment]
@rth I couldn't figure it out myself. Is it my mistake? Could you give me a hint on how to fix it? Thanks!

**Comment by rth** [comment]
Thanks for your contribution @Martolivna , no worries. That CI failure is  unrelated, and we also saw it in other PRs.

**Pull request merged**
