### PR TITLE
Add recipe-maintainers section in meta.yaml

### PR DESCRIPTION
**Pull request by ryanking13**
### Description

This adds `recipe-maintainers` section in meta.yaml, inspired by conda-forge ([example](https://github.com/conda-forge/pkg-config-feedstock/blob/c7a98e5797cd5147bc72e45bf7bba3a31f0262af/recipe/meta.yaml#L45-L51)).

There is no usage for this section yet, but at least we can notify maintainers that something is wrong with a package.
In the future, we may make a tool that automatically notifies recipe maintainers, just like conda-forge.

### CODE REVIEW

**Comment by hoodmane** [comment]
Thanks @ryanking13 this is great. Though I would want something slightly broader: something like recipe maintainers or project contacts. I don't know if it matters to distinguish between these. I'll open an issue asking for permission to add people to this.

**Comment by ryanking13** [comment]
> Though I would want something slightly broader: something like recipe maintainers or project contacts. I don't know if it matters to distinguish between these. I'll open an issue asking for permission to add people to this.

Thanks for opening the issue! I am +1 for adding more information like project contacts, so feel free to overtake this PR if you want to add more information.

**Comment by jobovy** [comment]
@hoodmane --Did you want to put me down for ``galpy`` as well?

**Comment by hoodmane** [comment]
Yup thanks

**Comment by hoodmane** [comment]
@ryanking13 I'm going to go ahead and merge this now, we can add more in a followup.

**Pull request merged**
