### PR TITLE
Backports for 0.24.1

### PR DESCRIPTION
**Pull request by hoodmane**
- [ ] Update changelog
- [ ] Merge don't squash

### CODE REVIEW

**Comment by rth** [comment]
Thanks @hoodmane ! Maybe we could also include https://github.com/pyodide/pyodide/pull/4161 https://github.com/pyodide/pyodide/pull/4156 https://github.com/pyodide/pyodide/pull/4156 ? Those are patch version updates, so probably include some package bug fixes that shouldn't hurt.

**Comment by hoodmane** [comment]
Fine with me.

**Comment by ryanking13** [comment]
Thanks! Let's update micropip and include it as well.

**Review by rth — APPROVED** [review]

**Comment by lesteve** [comment]
Thanks for the bugfix release!

**Pull request merged**
